//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   float4 gFogColor;                  // Offset:  448 Size:    16
//   float gFogStart;                   // Offset:  464 Size:     4
//   float gFogRange;                   // Offset:  468 Size:     4
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gsamAnisotropicWrap               sampler      NA          NA             s4      1 
// gDiffuseMap                       texture  float4          2d             t0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
// cbMaterial                        cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB1[41], immediateIndexed
      dcl_constantbuffer CB2[2], immediateIndexed
      dcl_sampler s4, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xyz
      dcl_input_ps linear v3.xy
      dcl_output o0.xyzw
      dcl_temps 13
      dcl_indexableTemp x0[21], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   v3.x <- pin.TexC.x; v3.y <- pin.TexC.y; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 117 "C:\cg\DX12\Solution\Chap11\Chap11_11\Shaders\Default.hlsl"
   0: sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v3.xyxx, t0.xyzw, s4
   1: mul r0.xyzw, r0.xyzw, cb2[0].xyzw  // r0.x <- diffuseAlbedo.x; r0.y <- diffuseAlbedo.y; r0.z <- diffuseAlbedo.z; r0.w <- diffuseAlbedo.w

#line 123
   2: mov r1.x, l(-0.100000)
   3: add r1.x, r0.w, r1.x
   4: lt r1.x, r1.x, l(0.000000)
   5: and r1.x, r1.x, l(-1)
   6: discard_nz r1.x

#line 127
   7: dp3 r1.x, v2.xyzx, v2.xyzx
   8: rsq r1.x, r1.x
   9: mul r1.xyz, r1.xxxx, v2.xyzx  // r1.x <- pin.NormalW.x; r1.y <- pin.NormalW.y; r1.z <- pin.NormalW.z

#line 130
  10: mov r2.xyz, -v1.xyzx
  11: add r2.xyz, r2.xyzx, cb1[24].xyzx  // r2.x <- toEyeW.x; r2.y <- toEyeW.y; r2.z <- toEyeW.z

#line 131
  12: dp3 r1.w, r2.xyzx, r2.xyzx
  13: sqrt r1.w, r1.w  // r1.w <- distToEye

#line 132
  14: div r2.xyz, r2.xyzx, r1.wwww

#line 135
  15: mul r3.xyz, r0.xyzx, cb1[27].xyzx  // r3.x <- ambient.x; r3.y <- ambient.y; r3.z <- ambient.z

#line 137
  16: mov r2.w, -cb2[1].w
  17: add r4.w, r2.w, l(1.000000)  // r4.w <- shininess

#line 138
  18: mov r5.xyz, r0.xyzx  // r5.x <- mat.DiffuseAlbedo.x; r5.y <- mat.DiffuseAlbedo.y; r5.z <- mat.DiffuseAlbedo.z
  19: mov r5.w, cb2[1].x  // r5.w <- mat.FresnelR0.x
  20: mov r4.yz, cb2[1].yyzy  // r4.y <- mat.FresnelR0.y; r4.z <- mat.FresnelR0.z
  21: mov r4.w, r4.w  // r4.w <- mat.Shininess

#line 140
  22: nop 
  23: mov x0[0].xyz, cb1[30].xyzx
  24: mov x0[2].xyz, cb1[31].xyzx
  25: mov x0[4].xyz, cb1[32].xyzx
  26: mov x0[6].xyz, cb1[33].xyzx
  27: mov x0[8].xyz, cb1[34].xyzx
  28: mov x0[10].xyz, cb1[35].xyzx
  29: mov x0[12].xyz, cb1[36].xyzx
  30: mov x0[14].xyz, cb1[37].xyzx
  31: mov x0[16].xyz, cb1[38].xyzx
  32: mov x0[18].xyz, cb1[39].xyzx
  33: mov x0[20].xyz, cb1[40].xyzx
  34: mov r5.xyzw, r5.xyzw
  35: mov r4.yzw, r4.yyzw
  36: mov r1.xyz, r1.xyzx
  37: mov r2.xyz, r2.xyzx

#line 142 "LightingUtil.hlsl"
  38: mov r0.xyz, l(0,0,0,0)  // r0.x <- result.x; r0.y <- result.y; r0.z <- result.z

#line 147
  39: mov r2.w, l(0)  // r2.w <- i
  40: mov r6.xyz, r0.xyzx  // r6.x <- result.x; r6.y <- result.y; r6.z <- result.z
  41: mov r3.w, r2.w  // r3.w <- i
  42: loop 
  43:   ilt r4.x, r3.w, l(3)
  44:   breakc_z r4.x

#line 149
  45:   mov r4.x, l(1.000000)  // r4.x <- shadowFactor.x
  46:   nop 
  47:   imul null, r6.w, r3.w, l(6)
  48:   mov r7.xyz, x0[r6.w + 0].xyzx
  49:   mov r8.xyz, x0[r6.w + 2].xyzx
  50:   mov r9.x, r5.w
  51:   mov r9.yzw, r4.yyzw
  52:   mov r10.xyz, r5.xyzx
  53:   mov r11.xyz, r1.xyzx
  54:   mov r12.xyz, r2.xyzx

#line 67
  55:   mov r8.xyz, -r8.xyzx  // r8.x <- lightVec.x; r8.y <- lightVec.y; r8.z <- lightVec.z

#line 70
  56:   dp3 r6.w, r8.xyzx, r11.xyzx
  57:   max r6.w, r6.w, l(0.000000)  // r6.w <- ndotl

#line 71
  58:   mul r7.xyz, r6.wwww, r7.xyzx  // r7.x <- lightStrength.x; r7.y <- lightStrength.y; r7.z <- lightStrength.z

#line 73
  59:   nop 
  60:   mov r7.xyz, r7.xyzx
  61:   mov r8.xyz, r8.xyzx
  62:   mov r11.xyz, r11.xyzx
  63:   mov r12.xyz, r12.xyzx
  64:   mov r10.xyz, r10.xyzx
  65:   mov r9.xyzw, r9.xyzw

#line 46
  66:   mul r6.w, r9.w, l(256.000000)  // r6.w <- m

#line 47
  67:   add r12.xyz, r8.xyzx, r12.xyzx
  68:   dp3 r7.w, r12.xyzx, r12.xyzx
  69:   rsq r7.w, r7.w
  70:   mul r12.xyz, r7.wwww, r12.xyzx  // r12.x <- halfVec.x; r12.y <- halfVec.y; r12.z <- halfVec.z

#line 49
  71:   add r7.w, r6.w, l(8.000000)
  72:   dp3 r8.w, r12.xyzx, r11.xyzx
  73:   max r8.w, r8.w, l(0.000000)
  74:   log r8.w, r8.w
  75:   mul r6.w, r6.w, r8.w
  76:   exp r6.w, r6.w
  77:   mul r6.w, r6.w, r7.w
  78:   div r6.w, r6.w, l(8.000000)  // r6.w <- roughnessFactor

#line 50
  79:   nop 
  80:   mov r9.xyz, r9.xyzx
  81:   mov r12.xyz, r12.xyzx
  82:   mov r8.xyz, r8.xyzx

#line 36
  83:   dp3 r7.w, r12.xyzx, r8.xyzx
  84:   max r7.w, r7.w, l(0.000000)
  85:   min r7.w, r7.w, l(1.000000)  // r7.w <- cosIncidentAngle

#line 38
  86:   mov r7.w, -r7.w
  87:   add r7.w, r7.w, l(1.000000)  // r7.w <- f0

#line 39
  88:   mov r8.xyz, -r9.xyzx
  89:   add r8.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  90:   mul r8.w, r7.w, r7.w
  91:   mul r8.w, r7.w, r8.w
  92:   mul r8.w, r7.w, r8.w
  93:   mul r7.w, r7.w, r8.w
  94:   mul r8.xyz, r7.wwww, r8.xyzx
  95:   add r8.xyz, r8.xyzx, r9.xyzx  // r8.x <- reflectPercent.x; r8.y <- reflectPercent.y; r8.z <- reflectPercent.z

#line 41
  96:   mov r8.xyz, r8.xyzx  // r8.x <- <SchlickFresnel return value>.x; r8.y <- <SchlickFresnel return value>.y; r8.z <- <SchlickFresnel return value>.z

#line 50
  97:   mov r8.xyz, r8.xyzx  // r8.x <- fresnelFactor.x; r8.y <- fresnelFactor.y; r8.z <- fresnelFactor.z

#line 52
  98:   mul r8.xyz, r6.wwww, r8.xyzx  // r8.x <- specAlbedo.x; r8.y <- specAlbedo.y; r8.z <- specAlbedo.z

#line 56
  99:   add r9.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 100:   div r8.xyz, r8.xyzx, r9.xyzx

#line 58
 101:   add r8.xyz, r8.xyzx, r10.xyzx
 102:   mul r7.xyz, r7.xyzx, r8.xyzx  // r7.x <- <BlinnPhong return value>.x; r7.y <- <BlinnPhong return value>.y; r7.z <- <BlinnPhong return value>.z

#line 73
 103:   mov r7.xyz, r7.xyzx  // r7.x <- <ComputeDirectionalLight return value>.x; r7.y <- <ComputeDirectionalLight return value>.y; r7.z <- <ComputeDirectionalLight return value>.z

#line 149
 104:   mul r7.xyz, r4.xxxx, r7.xyzx
 105:   add r6.xyz, r6.xyzx, r7.xyzx

#line 150
 106:   iadd r3.w, r3.w, l(1)
 107: endloop 

#line 167
 108: mov r6.xyz, r6.xyzx  // r6.x <- <ComputeLighting return value>.x; r6.y <- <ComputeLighting return value>.y; r6.z <- <ComputeLighting return value>.z

#line 140 "C:\cg\DX12\Solution\Chap11\Chap11_11\Shaders\Default.hlsl"
 109: mov r6.xyz, r6.xyzx  // r6.x <- directLight.x; r6.y <- directLight.y; r6.z <- directLight.z

#line 143
 110: add r0.xyz, r3.xyzx, r6.xyzx  // r0.x <- litColor.x; r0.y <- litColor.y; r0.z <- litColor.z

#line 146
 111: mov r1.x, -cb1[29].x
 112: add r1.x, r1.x, r1.w
 113: div r1.x, r1.x, cb1[29].y
 114: max r1.x, r1.x, l(0.000000)
 115: min r1.x, r1.x, l(1.000000)  // r1.x <- fogAmount

#line 147
 116: mov r1.yzw, -r0.xxyz
 117: add r1.yzw, r1.yyzw, cb1[28].xxyz
 118: mul r1.xyz, r1.yzwy, r1.xxxx
 119: add r0.xyz, r0.xyzx, r1.xyzx

#line 151
 120: mov r0.w, r0.w  // r0.w <- litColor.w

#line 153
 121: mov o0.xyz, r0.xyzx
 122: mov o0.w, r0.w
 123: ret 
// Approximately 124 instruction slots used
 