//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPass                            cbuffer      NA          NA            cb1      1 
// cbMaterial                        cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB1[41], immediateIndexed
      dcl_constantbuffer CB2[2], immediateIndexed
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xyz
      dcl_output o0.xyzw
      dcl_temps 13
      dcl_indexableTemp x0[21], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 212 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap14\Chap14_Solution\Chap14_8\Shaders\BezierTessellation.hlsl"
   0: dp3 r0.x, v2.xyzx, v2.xyzx
   1: rsq r0.x, r0.x
   2: mul r0.xyz, r0.xxxx, v2.xyzx  // r0.x <- pin.NormalW.x; r0.y <- pin.NormalW.y; r0.z <- pin.NormalW.z

#line 214
   3: mov r1.xyz, -v1.xyzx
   4: add r1.xyz, r1.xyzx, cb1[24].xyzx
   5: dp3 r0.w, r1.xyzx, r1.xyzx
   6: rsq r0.w, r0.w
   7: mul r1.xyz, r0.wwww, r1.xyzx  // r1.x <- toEye.x; r1.y <- toEye.y; r1.z <- toEye.z

#line 216
   8: mul r2.xyz, cb1[27].xyzx, cb2[0].xyzx  // r2.x <- ambient.x; r2.y <- ambient.y; r2.z <- ambient.z

#line 218
   9: mov r0.w, -cb2[1].w
  10: add r3.w, r0.w, l(1.000000)  // r3.w <- shininess

#line 219
  11: mov r4.xyz, cb2[0].xyzx  // r4.x <- mat.DiffuseAlbedo.x; r4.y <- mat.DiffuseAlbedo.y; r4.z <- mat.DiffuseAlbedo.z
  12: mov r3.xyz, cb2[1].xyzx  // r3.x <- mat.FresnelR0.x; r3.y <- mat.FresnelR0.y; r3.z <- mat.FresnelR0.z
  13: mov r3.w, r3.w  // r3.w <- mat.Shininess

#line 221
  14: nop 
  15: mov x0[0].xyz, cb1[30].xyzx
  16: mov x0[2].xyz, cb1[31].xyzx
  17: mov x0[4].xyz, cb1[32].xyzx
  18: mov x0[6].xyz, cb1[33].xyzx
  19: mov x0[8].xyz, cb1[34].xyzx
  20: mov x0[10].xyz, cb1[35].xyzx
  21: mov x0[12].xyz, cb1[36].xyzx
  22: mov x0[14].xyz, cb1[37].xyzx
  23: mov x0[16].xyz, cb1[38].xyzx
  24: mov x0[18].xyz, cb1[39].xyzx
  25: mov x0[20].xyz, cb1[40].xyzx
  26: mov r4.xyz, r4.xyzx
  27: mov r3.x, r3.x
  28: mov r3.yzw, r3.yyzw
  29: mov r0.xyz, r0.xyzx
  30: mov r1.xyz, r1.xyzx

#line 142 "LightingUtil.hlsl"
  31: mov r5.xyz, l(0,0,0,0)  // r5.x <- result.x; r5.y <- result.y; r5.z <- result.z

#line 147
  32: mov r0.w, l(0)  // r0.w <- i
  33: mov r6.xyz, r5.xyzx  // r6.x <- result.x; r6.y <- result.y; r6.z <- result.z
  34: mov r1.w, r0.w  // r1.w <- i
  35: loop 
  36:   ilt r2.w, r1.w, l(3)
  37:   breakc_z r2.w

#line 149
  38:   mov r2.w, l(1.000000)  // r2.w <- shadowFactor.x
  39:   nop 
  40:   imul null, r4.w, r1.w, l(6)
  41:   mov r7.xyz, x0[r4.w + 0].xyzx
  42:   mov r8.xyz, x0[r4.w + 2].xyzx
  43:   mov r9.x, r3.x
  44:   mov r9.yzw, r3.yyzw
  45:   mov r10.xyz, r4.xyzx
  46:   mov r11.xyz, r0.xyzx
  47:   mov r12.xyz, r1.xyzx

#line 67
  48:   mov r8.xyz, -r8.xyzx  // r8.x <- lightVec.x; r8.y <- lightVec.y; r8.z <- lightVec.z

#line 70
  49:   dp3 r4.w, r8.xyzx, r11.xyzx
  50:   max r4.w, r4.w, l(0.000000)  // r4.w <- ndotl

#line 71
  51:   mul r7.xyz, r4.wwww, r7.xyzx  // r7.x <- lightStrength.x; r7.y <- lightStrength.y; r7.z <- lightStrength.z

#line 73
  52:   nop 
  53:   mov r7.xyz, r7.xyzx
  54:   mov r8.xyz, r8.xyzx
  55:   mov r11.xyz, r11.xyzx
  56:   mov r12.xyz, r12.xyzx
  57:   mov r10.xyz, r10.xyzx
  58:   mov r9.xyzw, r9.xyzw

#line 46
  59:   mul r4.w, r9.w, l(256.000000)  // r4.w <- m

#line 47
  60:   add r12.xyz, r8.xyzx, r12.xyzx
  61:   dp3 r5.w, r12.xyzx, r12.xyzx
  62:   rsq r5.w, r5.w
  63:   mul r12.xyz, r5.wwww, r12.xyzx  // r12.x <- halfVec.x; r12.y <- halfVec.y; r12.z <- halfVec.z

#line 49
  64:   add r5.w, r4.w, l(8.000000)
  65:   dp3 r6.w, r12.xyzx, r11.xyzx
  66:   max r6.w, r6.w, l(0.000000)
  67:   log r6.w, r6.w
  68:   mul r4.w, r4.w, r6.w
  69:   exp r4.w, r4.w
  70:   mul r4.w, r4.w, r5.w
  71:   div r4.w, r4.w, l(8.000000)  // r4.w <- roughnessFactor

#line 50
  72:   nop 
  73:   mov r9.xyz, r9.xyzx
  74:   mov r12.xyz, r12.xyzx
  75:   mov r8.xyz, r8.xyzx

#line 36
  76:   dp3 r5.w, r12.xyzx, r8.xyzx
  77:   max r5.w, r5.w, l(0.000000)
  78:   min r5.w, r5.w, l(1.000000)  // r5.w <- cosIncidentAngle

#line 38
  79:   mov r5.w, -r5.w
  80:   add r5.w, r5.w, l(1.000000)  // r5.w <- f0

#line 39
  81:   mov r8.xyz, -r9.xyzx
  82:   add r8.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  83:   mul r6.w, r5.w, r5.w
  84:   mul r6.w, r5.w, r6.w
  85:   mul r6.w, r5.w, r6.w
  86:   mul r5.w, r5.w, r6.w
  87:   mul r8.xyz, r5.wwww, r8.xyzx
  88:   add r8.xyz, r8.xyzx, r9.xyzx  // r8.x <- reflectPercent.x; r8.y <- reflectPercent.y; r8.z <- reflectPercent.z

#line 41
  89:   mov r8.xyz, r8.xyzx  // r8.x <- <SchlickFresnel return value>.x; r8.y <- <SchlickFresnel return value>.y; r8.z <- <SchlickFresnel return value>.z

#line 50
  90:   mov r8.xyz, r8.xyzx  // r8.x <- fresnelFactor.x; r8.y <- fresnelFactor.y; r8.z <- fresnelFactor.z

#line 52
  91:   mul r8.xyz, r4.wwww, r8.xyzx  // r8.x <- specAlbedo.x; r8.y <- specAlbedo.y; r8.z <- specAlbedo.z

#line 56
  92:   add r9.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  93:   div r8.xyz, r8.xyzx, r9.xyzx

#line 58
  94:   add r8.xyz, r8.xyzx, r10.xyzx
  95:   mul r7.xyz, r7.xyzx, r8.xyzx  // r7.x <- <BlinnPhong return value>.x; r7.y <- <BlinnPhong return value>.y; r7.z <- <BlinnPhong return value>.z

#line 73
  96:   mov r7.xyz, r7.xyzx  // r7.x <- <ComputeDirectionalLight return value>.x; r7.y <- <ComputeDirectionalLight return value>.y; r7.z <- <ComputeDirectionalLight return value>.z

#line 149
  97:   mul r7.xyz, r2.wwww, r7.xyzx
  98:   add r6.xyz, r6.xyzx, r7.xyzx

#line 150
  99:   iadd r1.w, r1.w, l(1)
 100: endloop 

#line 167
 101: mov r6.xyz, r6.xyzx  // r6.x <- <ComputeLighting return value>.x; r6.y <- <ComputeLighting return value>.y; r6.z <- <ComputeLighting return value>.z

#line 221 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap14\Chap14_Solution\Chap14_8\Shaders\BezierTessellation.hlsl"
 102: mov r6.xyz, r6.xyzx  // r6.x <- directLight.x; r6.y <- directLight.y; r6.z <- directLight.z

#line 224
 103: add r0.xyz, r2.xyzx, r6.xyzx  // r0.x <- litColor.x; r0.y <- litColor.y; r0.z <- litColor.z

#line 225
 104: mov r0.w, cb2[0].w  // r0.w <- litColor.w

#line 227
 105: mov o0.xyz, r0.xyzx
 106: mov o0.w, r0.w
 107: ret 
// Approximately 108 instruction slots used
 