//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPerObject                       cbuffer      NA          NA            cb0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TessFactor            0   x           0 QUADEDGE   float       
// SV_TessFactor            1   x           1 QUADEDGE   float       
// SV_TessFactor            2   x           2 QUADEDGE   float       
// SV_TessFactor            3   x           3 QUADEDGE   float       
// SV_InsideTessFactor      0   x           4  QUADINT   float       
// SV_InsideTessFactor      1   x           5  QUADINT   float       
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
//
// Tessellation Domain   # of control points
// -------------------- --------------------
// Quadrilateral                          16
//
      ds_5_0
      dcl_input_control_point_count 16
      dcl_tessellator_domain domain_quad
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[20], immediateIndexed
      dcl_input vDomain.xy
      dcl_input vicp[16][0].xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_temps 8
//
// Initial variable locations:
//   vpc0.x <- patchTess.EdgeTess[0]; 
//   vpc1.x <- patchTess.EdgeTess[1]; 
//   vpc2.x <- patchTess.EdgeTess[2]; 
//   vpc3.x <- patchTess.EdgeTess[3]; 
//   vpc4.x <- patchTess.InsideTess[0]; 
//   vpc5.x <- patchTess.InsideTess[1]; 
//   vDomain.x <- uv.x; vDomain.y <- uv.y; 
//   o2.x <- <DS return value>.NormalW.x; o2.y <- <DS return value>.NormalW.y; o2.z <- <DS return value>.NormalW.z; 
//   o1.x <- <DS return value>.PosW.x; o1.y <- <DS return value>.PosW.y; o1.z <- <DS return value>.PosW.z; 
//   o0.x <- <DS return value>.PosH.x; o0.y <- <DS return value>.PosH.y; o0.z <- <DS return value>.PosH.z; o0.w <- <DS return value>.PosH.w; 
//   vicp[0][0].x <- bezPatch[0].PosL.x; vicp[0][0].y <- bezPatch[0].PosL.y; vicp[0][0].z <- bezPatch[0].PosL.z; 
//   vicp[1][0].x <- bezPatch[1].PosL.x; vicp[1][0].y <- bezPatch[1].PosL.y; vicp[1][0].z <- bezPatch[1].PosL.z; 
//   vicp[2][0].x <- bezPatch[2].PosL.x; vicp[2][0].y <- bezPatch[2].PosL.y; vicp[2][0].z <- bezPatch[2].PosL.z; 
//   vicp[3][0].x <- bezPatch[3].PosL.x; vicp[3][0].y <- bezPatch[3].PosL.y; vicp[3][0].z <- bezPatch[3].PosL.z; 
//   vicp[4][0].x <- bezPatch[4].PosL.x; vicp[4][0].y <- bezPatch[4].PosL.y; vicp[4][0].z <- bezPatch[4].PosL.z; 
//   vicp[5][0].x <- bezPatch[5].PosL.x; vicp[5][0].y <- bezPatch[5].PosL.y; vicp[5][0].z <- bezPatch[5].PosL.z; 
//   vicp[6][0].x <- bezPatch[6].PosL.x; vicp[6][0].y <- bezPatch[6].PosL.y; vicp[6][0].z <- bezPatch[6].PosL.z; 
//   vicp[7][0].x <- bezPatch[7].PosL.x; vicp[7][0].y <- bezPatch[7].PosL.y; vicp[7][0].z <- bezPatch[7].PosL.z; 
//   vicp[8][0].x <- bezPatch[8].PosL.x; vicp[8][0].y <- bezPatch[8].PosL.y; vicp[8][0].z <- bezPatch[8].PosL.z; 
//   vicp[9][0].x <- bezPatch[9].PosL.x; vicp[9][0].y <- bezPatch[9].PosL.y; vicp[9][0].z <- bezPatch[9].PosL.z; 
//   vicp[10][0].x <- bezPatch[10].PosL.x; vicp[10][0].y <- bezPatch[10].PosL.y; vicp[10][0].z <- bezPatch[10].PosL.z; 
//   vicp[11][0].x <- bezPatch[11].PosL.x; vicp[11][0].y <- bezPatch[11].PosL.y; vicp[11][0].z <- bezPatch[11].PosL.z; 
//   vicp[12][0].x <- bezPatch[12].PosL.x; vicp[12][0].y <- bezPatch[12].PosL.y; vicp[12][0].z <- bezPatch[12].PosL.z; 
//   vicp[13][0].x <- bezPatch[13].PosL.x; vicp[13][0].y <- bezPatch[13].PosL.y; vicp[13][0].z <- bezPatch[13].PosL.z; 
//   vicp[14][0].x <- bezPatch[14].PosL.x; vicp[14][0].y <- bezPatch[14].PosL.y; vicp[14][0].z <- bezPatch[14].PosL.z; 
//   vicp[15][0].x <- bezPatch[15].PosL.x; vicp[15][0].y <- bezPatch[15].PosL.y; vicp[15][0].z <- bezPatch[15].PosL.z
//
#line 191 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap14\Chap14_Solution\Chap14_8\Shaders\BezierTessellation.hlsl"
   0: nop 
   1: mov r0.x, vDomain.x

#line 153
   2: mov r0.y, -r0.x
   3: add r0.y, r0.y, l(1.000000)  // r0.y <- invT

#line 155
   4: mul r0.z, r0.y, r0.y
   5: mul r1.x, r0.y, r0.z  // r1.x <- <BernsteinBasis return value>.x
   6: mul r0.z, r0.x, l(3.000000)
   7: mul r0.z, r0.y, r0.z
   8: mul r1.y, r0.y, r0.z  // r1.y <- <BernsteinBasis return value>.y
   9: mul r0.z, r0.x, l(3.000000)
  10: mul r0.z, r0.x, r0.z
  11: mul r1.z, r0.y, r0.z  // r1.z <- <BernsteinBasis return value>.z
  12: mul r0.y, r0.x, r0.x
  13: mul r1.w, r0.x, r0.y  // r1.w <- <BernsteinBasis return value>.w

#line 191
  14: mov r1.xyzw, r1.xyzw  // r1.x <- basisU.x; r1.y <- basisU.y; r1.z <- basisU.z; r1.w <- basisU.w

#line 192
  15: nop 
  16: mov r0.x, vDomain.y

#line 153
  17: mov r0.y, -r0.x
  18: add r0.y, r0.y, l(1.000000)  // r0.y <- invT

#line 155
  19: mul r0.z, r0.y, r0.y
  20: mul r2.x, r0.y, r0.z  // r2.x <- <BernsteinBasis return value>.x
  21: mul r0.z, r0.x, l(3.000000)
  22: mul r0.z, r0.y, r0.z
  23: mul r2.y, r0.y, r0.z  // r2.y <- <BernsteinBasis return value>.y
  24: mul r0.z, r0.x, l(3.000000)
  25: mul r0.z, r0.x, r0.z
  26: mul r2.z, r0.y, r0.z  // r2.z <- <BernsteinBasis return value>.z
  27: mul r0.y, r0.x, r0.x
  28: mul r2.w, r0.x, r0.y  // r2.w <- <BernsteinBasis return value>.w

#line 192
  29: mov r2.xyzw, r2.xyzw  // r2.x <- basisV.x; r2.y <- basisV.y; r2.z <- basisV.z; r2.w <- basisV.w

#line 193
  30: nop 
  31: mov r0.x, vDomain.x

#line 163
  32: mov r0.y, -r0.x
  33: add r0.y, r0.y, l(1.000000)  // r0.y <- invT

#line 165
  34: itof r0.z, l(-3)
  35: mul r0.z, r0.y, r0.z
  36: mul r3.x, r0.y, r0.z  // r3.x <- <dBernsteinBasis return value>.x
  37: itof r0.z, l(3)
  38: mul r0.z, r0.y, r0.z
  39: mul r0.z, r0.y, r0.z
  40: itof r0.w, l(6)
  41: mul r0.w, r0.x, r0.w
  42: mul r0.w, r0.y, r0.w
  43: mov r0.w, -r0.w
  44: add r3.y, r0.w, r0.z  // r3.y <- <dBernsteinBasis return value>.y
  45: itof r0.z, l(6)
  46: mul r0.z, r0.x, r0.z
  47: mul r0.y, r0.y, r0.z
  48: itof r0.z, l(3)
  49: mul r0.z, r0.x, r0.z
  50: mul r0.z, r0.x, r0.z
  51: mov r0.z, -r0.z
  52: add r3.z, r0.z, r0.y  // r3.z <- <dBernsteinBasis return value>.z
  53: itof r0.y, l(3)
  54: mul r0.y, r0.x, r0.y
  55: mul r3.w, r0.x, r0.y  // r3.w <- <dBernsteinBasis return value>.w

#line 193
  56: mov r3.xyzw, r3.xyzw  // r3.x <- dbasisU.x; r3.y <- dbasisU.y; r3.z <- dbasisU.z; r3.w <- dbasisU.w

#line 194
  57: nop 
  58: mov r0.x, vDomain.y

#line 163
  59: mov r0.y, -r0.x
  60: add r0.y, r0.y, l(1.000000)  // r0.y <- invT

#line 165
  61: itof r0.z, l(-3)
  62: mul r0.z, r0.y, r0.z
  63: mul r4.x, r0.y, r0.z  // r4.x <- <dBernsteinBasis return value>.x
  64: itof r0.z, l(3)
  65: mul r0.z, r0.y, r0.z
  66: mul r0.z, r0.y, r0.z
  67: itof r0.w, l(6)
  68: mul r0.w, r0.x, r0.w
  69: mul r0.w, r0.y, r0.w
  70: mov r0.w, -r0.w
  71: add r4.y, r0.w, r0.z  // r4.y <- <dBernsteinBasis return value>.y
  72: itof r0.z, l(6)
  73: mul r0.z, r0.x, r0.z
  74: mul r0.y, r0.y, r0.z
  75: itof r0.z, l(3)
  76: mul r0.z, r0.x, r0.z
  77: mul r0.z, r0.x, r0.z
  78: mov r0.z, -r0.z
  79: add r4.z, r0.z, r0.y  // r4.z <- <dBernsteinBasis return value>.z
  80: itof r0.y, l(3)
  81: mul r0.y, r0.x, r0.y
  82: mul r4.w, r0.x, r0.y  // r4.w <- <dBernsteinBasis return value>.w

#line 194
  83: mov r4.xyzw, r4.xyzw  // r4.x <- dbasisV.x; r4.y <- dbasisV.y; r4.z <- dbasisV.z; r4.w <- dbasisV.w

#line 196
  84: nop 
  85: mov r1.xyzw, r1.xyzw
  86: mov r2.xyzw, r2.xyzw

#line 174
  87: mul r0.xyz, r1.xxxx, vicp[0][0].xyzx
  88: mul r5.xyz, r1.yyyy, vicp[1][0].xyzx
  89: add r0.xyz, r0.xyzx, r5.xyzx
  90: mul r5.xyz, r1.zzzz, vicp[2][0].xyzx
  91: add r0.xyz, r0.xyzx, r5.xyzx
  92: mul r5.xyz, r1.wwww, vicp[3][0].xyzx
  93: add r0.xyz, r0.xyzx, r5.xyzx
  94: mul r0.xyz, r0.xyzx, r2.xxxx  // r0.x <- sum.x; r0.y <- sum.y; r0.z <- sum.z

#line 175
  95: mul r5.xyz, r1.xxxx, vicp[4][0].xyzx
  96: mul r6.xyz, r1.yyyy, vicp[5][0].xyzx
  97: add r5.xyz, r5.xyzx, r6.xyzx
  98: mul r6.xyz, r1.zzzz, vicp[6][0].xyzx
  99: add r5.xyz, r5.xyzx, r6.xyzx
 100: mul r6.xyz, r1.wwww, vicp[7][0].xyzx
 101: add r5.xyz, r5.xyzx, r6.xyzx
 102: mul r5.xyz, r2.yyyy, r5.xyzx
 103: add r0.xyz, r0.xyzx, r5.xyzx

#line 176
 104: mul r5.xyz, r1.xxxx, vicp[8][0].xyzx
 105: mul r6.xyz, r1.yyyy, vicp[9][0].xyzx
 106: add r5.xyz, r5.xyzx, r6.xyzx
 107: mul r6.xyz, r1.zzzz, vicp[10][0].xyzx
 108: add r5.xyz, r5.xyzx, r6.xyzx
 109: mul r6.xyz, r1.wwww, vicp[11][0].xyzx
 110: add r5.xyz, r5.xyzx, r6.xyzx
 111: mul r5.xyz, r2.zzzz, r5.xyzx
 112: add r0.xyz, r0.xyzx, r5.xyzx

#line 177
 113: mul r5.xyz, r1.xxxx, vicp[12][0].xyzx
 114: mul r6.xyz, r1.yyyy, vicp[13][0].xyzx
 115: add r5.xyz, r5.xyzx, r6.xyzx
 116: mul r6.xyz, r1.zzzz, vicp[14][0].xyzx
 117: add r5.xyz, r5.xyzx, r6.xyzx
 118: mul r6.xyz, r1.wwww, vicp[15][0].xyzx
 119: add r5.xyz, r5.xyzx, r6.xyzx
 120: mul r5.xyz, r2.wwww, r5.xyzx
 121: add r0.xyz, r0.xyzx, r5.xyzx

#line 179
 122: mov r0.xyz, r0.xyzx  // r0.x <- <CubicBezierSum return value>.x; r0.y <- <CubicBezierSum return value>.y; r0.z <- <CubicBezierSum return value>.z

#line 196
 123: mov r0.xyz, r0.xyzx  // r0.x <- p.x; r0.y <- p.y; r0.z <- p.z

#line 197
 124: nop 
 125: mov r3.xyzw, r3.xyzw

#line 174
 126: mul r5.xyz, r3.xxxx, vicp[0][0].zxyz
 127: mul r6.xyz, r3.yyyy, vicp[1][0].zxyz
 128: add r5.xyz, r5.xyzx, r6.xyzx
 129: mul r6.xyz, r3.zzzz, vicp[2][0].zxyz
 130: add r5.xyz, r5.xyzx, r6.xyzx
 131: mul r6.xyz, r3.wwww, vicp[3][0].zxyz
 132: add r5.xyz, r5.xyzx, r6.xyzx
 133: mul r5.xyz, r2.xxxx, r5.xyzx  // r5.x <- sum.z; r5.y <- sum.x; r5.z <- sum.y

#line 175
 134: mul r6.xyz, r3.xxxx, vicp[4][0].zxyz
 135: mul r7.xyz, r3.yyyy, vicp[5][0].zxyz
 136: add r6.xyz, r6.xyzx, r7.xyzx
 137: mul r7.xyz, r3.zzzz, vicp[6][0].zxyz
 138: add r6.xyz, r6.xyzx, r7.xyzx
 139: mul r7.xyz, r3.wwww, vicp[7][0].zxyz
 140: add r6.xyz, r6.xyzx, r7.xyzx
 141: mul r6.xyz, r2.yyyy, r6.xyzx
 142: add r5.xyz, r5.xyzx, r6.xyzx

#line 176
 143: mul r6.xyz, r3.xxxx, vicp[8][0].zxyz
 144: mul r7.xyz, r3.yyyy, vicp[9][0].zxyz
 145: add r6.xyz, r6.xyzx, r7.xyzx
 146: mul r7.xyz, r3.zzzz, vicp[10][0].zxyz
 147: add r6.xyz, r6.xyzx, r7.xyzx
 148: mul r7.xyz, r3.wwww, vicp[11][0].zxyz
 149: add r6.xyz, r6.xyzx, r7.xyzx
 150: mul r2.xyz, r2.zzzz, r6.xyzx
 151: add r2.xyz, r2.xyzx, r5.xyzx  // r2.x <- sum.z; r2.y <- sum.x; r2.z <- sum.y

#line 177
 152: mul r5.xyz, r3.xxxx, vicp[12][0].zxyz
 153: mul r6.xyz, r3.yyyy, vicp[13][0].zxyz
 154: add r5.xyz, r5.xyzx, r6.xyzx
 155: mul r3.xyz, r3.zzzz, vicp[14][0].zxyz
 156: add r3.xyz, r3.xyzx, r5.xyzx
 157: mul r5.xyz, r3.wwww, vicp[15][0].zxyz
 158: add r3.xyz, r3.xyzx, r5.xyzx
 159: mul r3.xyz, r2.wwww, r3.xyzx
 160: add r2.xyz, r2.xyzx, r3.xyzx

#line 179
 161: mov r2.xyz, r2.xyzx  // r2.x <- <CubicBezierSum return value>.z; r2.y <- <CubicBezierSum return value>.x; r2.z <- <CubicBezierSum return value>.y

#line 197
 162: mov r2.xyz, r2.xyzx  // r2.x <- dpdu.z; r2.y <- dpdu.x; r2.z <- dpdu.y

#line 198
 163: nop 
 164: mov r4.xyzw, r4.xyzw

#line 174
 165: mul r3.xyz, r1.xxxx, vicp[0][0].yzxy
 166: mul r5.xyz, r1.yyyy, vicp[1][0].yzxy
 167: add r3.xyz, r3.xyzx, r5.xyzx
 168: mul r5.xyz, r1.zzzz, vicp[2][0].yzxy
 169: add r3.xyz, r3.xyzx, r5.xyzx
 170: mul r5.xyz, r1.wwww, vicp[3][0].yzxy
 171: add r3.xyz, r3.xyzx, r5.xyzx
 172: mul r3.xyz, r3.xyzx, r4.xxxx  // r3.x <- sum.y; r3.y <- sum.z; r3.z <- sum.x

#line 175
 173: mul r5.xyz, r1.xxxx, vicp[4][0].yzxy
 174: mul r6.xyz, r1.yyyy, vicp[5][0].yzxy
 175: add r5.xyz, r5.xyzx, r6.xyzx
 176: mul r6.xyz, r1.zzzz, vicp[6][0].yzxy
 177: add r5.xyz, r5.xyzx, r6.xyzx
 178: mul r6.xyz, r1.wwww, vicp[7][0].yzxy
 179: add r5.xyz, r5.xyzx, r6.xyzx
 180: mul r5.xyz, r4.yyyy, r5.xyzx
 181: add r3.xyz, r3.xyzx, r5.xyzx

#line 176
 182: mul r5.xyz, r1.xxxx, vicp[8][0].yzxy
 183: mul r6.xyz, r1.yyyy, vicp[9][0].yzxy
 184: add r5.xyz, r5.xyzx, r6.xyzx
 185: mul r6.xyz, r1.zzzz, vicp[10][0].yzxy
 186: add r5.xyz, r5.xyzx, r6.xyzx
 187: mul r6.xyz, r1.wwww, vicp[11][0].yzxy
 188: add r5.xyz, r5.xyzx, r6.xyzx
 189: mul r4.xyz, r4.zzzz, r5.xyzx
 190: add r3.xyz, r3.xyzx, r4.xyzx

#line 177
 191: mul r4.xyz, r1.xxxx, vicp[12][0].yzxy
 192: mul r5.xyz, r1.yyyy, vicp[13][0].yzxy
 193: add r4.xyz, r4.xyzx, r5.xyzx
 194: mul r1.xyz, r1.zzzz, vicp[14][0].yzxy
 195: add r1.xyz, r1.xyzx, r4.xyzx
 196: mul r4.xyz, r1.wwww, vicp[15][0].yzxy
 197: add r1.xyz, r1.xyzx, r4.xyzx
 198: mul r1.xyz, r1.xyzx, r4.wwww
 199: add r1.xyz, r1.xyzx, r3.xyzx  // r1.x <- sum.y; r1.y <- sum.z; r1.z <- sum.x

#line 179
 200: mov r1.xyz, r1.xyzx  // r1.x <- <CubicBezierSum return value>.y; r1.y <- <CubicBezierSum return value>.z; r1.z <- <CubicBezierSum return value>.x

#line 198
 201: mov r1.xyz, r1.xyzx  // r1.x <- dpdv.y; r1.y <- dpdv.z; r1.z <- dpdv.x

#line 200
 202: mul r3.xyz, r1.yzxy, r2.zxyz
 203: mul r1.xyz, r1.xyzx, r2.xyzx
 204: mov r1.xyz, -r1.xyzx
 205: add r1.xyz, r1.xyzx, r3.xyzx
 206: dp3 r1.w, r1.xyzx, r1.xyzx
 207: rsq r1.w, r1.w
 208: mul r1.xyz, r1.wwww, r1.xyzx  // r1.x <- normal.x; r1.y <- normal.y; r1.z <- normal.z

#line 202
 209: mov r0.w, l(1.000000)
 210: dp4 r2.x, r0.xyzw, cb0[0].xyzw  // r2.x <- posW.x
 211: dp4 r2.y, r0.xyzw, cb0[1].xyzw  // r2.y <- posW.y
 212: dp4 r2.z, r0.xyzw, cb0[2].xyzw  // r2.z <- posW.z
 213: dp4 r2.w, r0.xyzw, cb0[3].xyzw  // r2.w <- posW.w

#line 203
 214: dp4 r0.x, r2.xyzw, cb1[16].xyzw  // r0.x <- dout.PosH.x
 215: dp4 r0.y, r2.xyzw, cb1[17].xyzw  // r0.y <- dout.PosH.y
 216: dp4 r0.z, r2.xyzw, cb1[18].xyzw  // r0.z <- dout.PosH.z
 217: dp4 r0.w, r2.xyzw, cb1[19].xyzw  // r0.w <- dout.PosH.w

#line 204
 218: mov r2.xyz, r2.xyzx  // r2.x <- dout.PosW.x; r2.y <- dout.PosW.y; r2.z <- dout.PosW.z

#line 205
 219: dp3 r3.x, r1.xyzx, cb0[0].xyzx  // r3.x <- dout.NormalW.x
 220: dp3 r3.y, r1.xyzx, cb0[1].xyzx  // r3.y <- dout.NormalW.y
 221: dp3 r3.z, r1.xyzx, cb0[2].xyzx  // r3.z <- dout.NormalW.z

#line 207
 222: mov o0.xyzw, r0.xyzw
 223: mov o1.xyz, r2.xyzx
 224: mov o2.xyz, r3.xyzx
 225: ret 
// Approximately 226 instruction slots used
 