//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPerObject                       cbuffer      NA          NA            cb0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TessFactor            0   x           0  TRIEDGE   float       
// SV_TessFactor            1   x           1  TRIEDGE   float       
// SV_TessFactor            2   x           2  TRIEDGE   float       
// SV_InsideTessFactor      0   x           3   TRIINT   float       
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
// Tessellation Domain   # of control points
// -------------------- --------------------
// Triangle                               10
//
      ds_5_0
      dcl_input_control_point_count 10
      dcl_tessellator_domain domain_tri
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[20], immediateIndexed
      dcl_input vDomain.xyz
      dcl_input vicp[10][0].xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 3
//
// Initial variable locations:
//   vpc0.x <- patchTess.EdgeTess[0]; 
//   vpc1.x <- patchTess.EdgeTess[1]; 
//   vpc2.x <- patchTess.EdgeTess[2]; 
//   vpc3.x <- patchTess.InsideTess[0]; 
//   vDomain.x <- uvw.x; vDomain.y <- uvw.y; vDomain.z <- uvw.z; 
//   o0.x <- <DS return value>.PosH.x; o0.y <- <DS return value>.PosH.y; o0.z <- <DS return value>.PosH.z; o0.w <- <DS return value>.PosH.w; 
//   vicp[0][0].x <- bezPatch[0].PosL.x; vicp[0][0].y <- bezPatch[0].PosL.y; vicp[0][0].z <- bezPatch[0].PosL.z; 
//   vicp[1][0].x <- bezPatch[1].PosL.x; vicp[1][0].y <- bezPatch[1].PosL.y; vicp[1][0].z <- bezPatch[1].PosL.z; 
//   vicp[2][0].x <- bezPatch[2].PosL.x; vicp[2][0].y <- bezPatch[2].PosL.y; vicp[2][0].z <- bezPatch[2].PosL.z; 
//   vicp[3][0].x <- bezPatch[3].PosL.x; vicp[3][0].y <- bezPatch[3].PosL.y; vicp[3][0].z <- bezPatch[3].PosL.z; 
//   vicp[4][0].x <- bezPatch[4].PosL.x; vicp[4][0].y <- bezPatch[4].PosL.y; vicp[4][0].z <- bezPatch[4].PosL.z; 
//   vicp[5][0].x <- bezPatch[5].PosL.x; vicp[5][0].y <- bezPatch[5].PosL.y; vicp[5][0].z <- bezPatch[5].PosL.z; 
//   vicp[6][0].x <- bezPatch[6].PosL.x; vicp[6][0].y <- bezPatch[6].PosL.y; vicp[6][0].z <- bezPatch[6].PosL.z; 
//   vicp[7][0].x <- bezPatch[7].PosL.x; vicp[7][0].y <- bezPatch[7].PosL.y; vicp[7][0].z <- bezPatch[7].PosL.z; 
//   vicp[8][0].x <- bezPatch[8].PosL.x; vicp[8][0].y <- bezPatch[8].PosL.y; vicp[8][0].z <- bezPatch[8].PosL.z; 
//   vicp[9][0].x <- bezPatch[9].PosL.x; vicp[9][0].y <- bezPatch[9].PosL.y; vicp[9][0].z <- bezPatch[9].PosL.z
//
#line 166 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap14\Chap14_Solution\Chap14_9\Shaders\BezierTessellation.hlsl"
   0: nop 
   1: mov r0.xyz, vDomain.xyzx

#line 142
   2: mov r0.x, r0.x  // r0.x <- u

#line 143
   3: mov r0.y, r0.y  // r0.y <- v

#line 144
   4: mov r0.z, r0.z  // r0.z <- w

#line 146
   5: mul r0.w, r0.x, r0.x
   6: mul r0.w, r0.x, r0.w
   7: mul r1.xyz, r0.wwww, vicp[0][0].xyzx
   8: mul r0.w, r0.y, r0.y
   9: mul r0.w, r0.y, r0.w
  10: mul r2.xyz, r0.wwww, vicp[1][0].xyzx
  11: add r1.xyz, r1.xyzx, r2.xyzx
  12: mul r0.w, r0.z, r0.z
  13: mul r0.w, r0.z, r0.w
  14: mul r2.xyz, r0.wwww, vicp[2][0].xyzx
  15: add r1.xyz, r1.xyzx, r2.xyzx
  16: mul r0.w, r0.x, l(3.000000)
  17: mul r0.w, r0.x, r0.w
  18: mul r0.w, r0.y, r0.w
  19: mul r2.xyz, r0.wwww, vicp[3][0].xyzx
  20: add r1.xyz, r1.xyzx, r2.xyzx
  21: mul r0.w, r0.x, l(3.000000)
  22: mul r0.w, r0.y, r0.w
  23: mul r0.w, r0.y, r0.w
  24: mul r2.xyz, r0.wwww, vicp[4][0].xyzx
  25: add r1.xyz, r1.xyzx, r2.xyzx
  26: mul r0.w, r0.y, l(3.000000)
  27: mul r0.w, r0.y, r0.w
  28: mul r0.w, r0.z, r0.w
  29: mul r2.xyz, r0.wwww, vicp[5][0].xyzx
  30: add r1.xyz, r1.xyzx, r2.xyzx
  31: mul r0.w, r0.y, l(3.000000)
  32: mul r0.w, r0.z, r0.w
  33: mul r0.w, r0.z, r0.w
  34: mul r2.xyz, r0.wwww, vicp[6][0].xyzx
  35: add r1.xyz, r1.xyzx, r2.xyzx
  36: mul r0.w, r0.x, l(3.000000)
  37: mul r0.w, r0.z, r0.w
  38: mul r0.w, r0.z, r0.w
  39: mul r2.xyz, r0.wwww, vicp[7][0].xyzx
  40: add r1.xyz, r1.xyzx, r2.xyzx
  41: mul r0.w, r0.x, l(3.000000)
  42: mul r0.w, r0.x, r0.w
  43: mul r0.w, r0.z, r0.w
  44: mul r2.xyz, r0.wwww, vicp[8][0].xyzx
  45: add r1.xyz, r1.xyzx, r2.xyzx
  46: mul r0.x, r0.x, l(6.000000)
  47: mul r0.x, r0.y, r0.x
  48: mul r0.x, r0.z, r0.x
  49: mul r0.xyz, r0.xxxx, vicp[9][0].xyzx
  50: add r0.xyz, r0.xyzx, r1.xyzx  // r0.x <- <CubicBezierTriangle return value>.x; r0.y <- <CubicBezierTriangle return value>.y; r0.z <- <CubicBezierTriangle return value>.z

#line 166
  51: mov r0.xyz, r0.xyzx  // r0.x <- p.x; r0.y <- p.y; r0.z <- p.z

#line 168
  52: mov r0.w, l(1.000000)
  53: dp4 r1.x, r0.xyzw, cb0[0].xyzw  // r1.x <- posW.x
  54: dp4 r1.y, r0.xyzw, cb0[1].xyzw  // r1.y <- posW.y
  55: dp4 r1.z, r0.xyzw, cb0[2].xyzw  // r1.z <- posW.z
  56: dp4 r1.w, r0.xyzw, cb0[3].xyzw  // r1.w <- posW.w

#line 169
  57: dp4 r0.x, r1.xyzw, cb1[16].xyzw  // r0.x <- dout.PosH.x
  58: dp4 r0.y, r1.xyzw, cb1[17].xyzw  // r0.y <- dout.PosH.y
  59: dp4 r0.z, r1.xyzw, cb1[18].xyzw  // r0.z <- dout.PosH.z
  60: dp4 r0.w, r1.xyzw, cb1[19].xyzw  // r0.w <- dout.PosH.w

#line 171
  61: mov o0.xyzw, r0.xyzw
  62: ret 
// Approximately 63 instruction slots used
 