//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64
//   float2 gDisplacementMapTexelSize;  // Offset:  128 Size:     8
//   float gGridSpatialStep;            // Offset:  136 Size:     4
//   float cbPerObjectPad1;             // Offset:  140 Size:     4 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerPassPad1;               // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerPassPad2;              // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768 [unused]
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16 [unused]
//   float3 gFresnelR0;                 // Offset:   16 Size:    12 [unused]
//   float gRoughness;                  // Offset:   28 Size:     4 [unused]
//   float4x4 gMatTransform;            // Offset:   32 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gsamPointClamp                    sampler      NA          NA             s1      1 
// gsamLinearWrap                    sampler      NA          NA             s2      1 
// gDisplacementMap                  texture  float4          2d             t1      1 
// cbPerObject                       cbuffer      NA          NA            cb0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
// cbMaterial                        cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
      vs_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[9], immediateIndexed
      dcl_constantbuffer CB1[20], immediateIndexed
      dcl_constantbuffer CB2[4], immediateIndexed
      dcl_sampler s1, mode_default
      dcl_sampler s2, mode_default
      dcl_resource_texture2d (float,float,float,float) t1
      dcl_input v0.xyz
      dcl_input v2.xy
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xy
      dcl_temps 5
//
// Initial variable locations:
//   v0.x <- vin.PosL.x; v0.y <- vin.PosL.y; v0.z <- vin.PosL.z; 
//   v1.x <- vin.NormalL.x; v1.y <- vin.NormalL.y; v1.z <- vin.NormalL.z; 
//   v2.x <- vin.TexC.x; v2.y <- vin.TexC.y; 
//   o3.x <- <VS return value>.TexC.x; o3.y <- <VS return value>.TexC.y; 
//   o2.x <- <VS return value>.NormalW.x; o2.y <- <VS return value>.NormalW.y; o2.z <- <VS return value>.NormalW.z; 
//   o1.x <- <VS return value>.PosW.x; o1.y <- <VS return value>.PosW.y; o1.z <- <VS return value>.PosW.z; 
//   o0.x <- <VS return value>.PosH.x; o0.y <- <VS return value>.PosH.y; o0.z <- <VS return value>.PosH.z; o0.w <- <VS return value>.PosH.w
//
#line 104 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap13\SobelFilter\Shaders\Default.hlsl"
   0: sample_l_indexable(texture2d)(float,float,float,float) r0.x, v2.xyxx, t1.xyzw, s2, l(1.000000)
   1: add r0.y, r0.x, v0.y  // r0.y <- vin.PosL.y

#line 107
   2: mov r1.x, cb0[8].x  // r1.x <- du

#line 108
   3: mov r2.y, cb0[8].y  // r2.y <- dv

#line 109
   4: mov r1.y, l(0)
   5: mov r1.zw, -r1.xxxy
   6: add r1.zw, r1.zzzw, v2.xxxy
   7: sample_l_indexable(texture2d)(float,float,float,float) r1.z, r1.zwzz, t1.yzxw, s1, l(0.000000)
   8: mov r1.z, r1.z  // r1.z <- l

#line 110
   9: add r1.xy, r1.xyxx, v2.xyxx
  10: sample_l_indexable(texture2d)(float,float,float,float) r1.x, r1.xyxx, t1.xyzw, s1, l(0.000000)
  11: mov r1.x, r1.x  // r1.x <- r

#line 111
  12: mov r2.x, l(0)
  13: mov r1.yw, -r2.xxxy
  14: add r1.yw, r1.yyyw, v2.xxxy
  15: sample_l_indexable(texture2d)(float,float,float,float) r1.y, r1.ywyy, t1.yxzw, s1, l(0.000000)
  16: mov r1.y, r1.y  // r1.y <- t

#line 112
  17: add r2.xy, r2.xyxx, v2.xyxx
  18: sample_l_indexable(texture2d)(float,float,float,float) r1.w, r2.xyxx, t1.yzwx, s1, l(0.000000)
  19: mov r1.w, r1.w  // r1.w <- b

#line 113
  20: mov r1.x, -r1.x
  21: add r2.x, r1.z, r1.x
  22: mul r2.y, cb0[8].z, l(2.000000)
  23: mov r1.x, -r1.y
  24: add r2.z, r1.x, r1.w
  25: dp3 r1.x, r2.xyzx, r2.xyzx
  26: rsq r1.x, r1.x
  27: mul r1.xyz, r1.xxxx, r2.xyzx  // r1.x <- vin.NormalL.x; r1.y <- vin.NormalL.y; r1.z <- vin.NormalL.z

#line 119
  28: mov r0.xz, v0.xxzx
  29: mov r0.w, l(1.000000)
  30: dp4 r2.x, r0.xyzw, cb0[0].xyzw  // r2.x <- posW.x
  31: dp4 r2.y, r0.xyzw, cb0[1].xyzw  // r2.y <- posW.y
  32: dp4 r2.z, r0.xyzw, cb0[2].xyzw  // r2.z <- posW.z
  33: dp4 r2.w, r0.xyzw, cb0[3].xyzw  // r2.w <- posW.w

#line 120
  34: mov r2.xyz, r2.xyzx  // r2.x <- vout.PosW.x; r2.y <- vout.PosW.y; r2.z <- vout.PosW.z

#line 123
  35: dp3 r0.x, r1.xyzx, cb0[0].xyzx  // r0.x <- vout.NormalW.x
  36: dp3 r0.y, r1.xyzx, cb0[1].xyzx  // r0.y <- vout.NormalW.y
  37: dp3 r0.z, r1.xyzx, cb0[2].xyzx  // r0.z <- vout.NormalW.z

#line 126
  38: dp4 r1.x, r2.xyzw, cb1[16].xyzw  // r1.x <- vout.PosH.x
  39: dp4 r1.y, r2.xyzw, cb1[17].xyzw  // r1.y <- vout.PosH.y
  40: dp4 r1.z, r2.xyzw, cb1[18].xyzw  // r1.z <- vout.PosH.z
  41: dp4 r1.w, r2.xyzw, cb1[19].xyzw  // r1.w <- vout.PosH.w

#line 129
  42: mov r3.xy, v2.xyxx
  43: mov r3.zw, l(0,0,0,1.000000)
  44: dp4 r4.x, r3.xyzw, cb0[4].xyzw  // r4.x <- texC.x
  45: dp4 r4.y, r3.xyzw, cb0[5].xyzw  // r4.y <- texC.y
  46: dp4 r4.z, r3.xyzw, cb0[6].xyzw  // r4.z <- texC.z
  47: dp4 r4.w, r3.xyzw, cb0[7].xyzw  // r4.w <- texC.w

#line 130
  48: dp4 r3.x, r4.xyzw, cb2[2].xyzw  // r3.x <- vout.TexC.x
  49: dp4 r3.y, r4.xyzw, cb2[3].xyzw  // r3.y <- vout.TexC.y

#line 132
  50: mov o0.xyzw, r1.xyzw
  51: mov o1.xyz, r2.xyzx
  52: mov o2.xyz, r0.xyzx
  53: mov o3.xy, r3.xyxx
  54: ret 
// Approximately 55 instruction slots used
 