//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   float4 gFogColor;                  // Offset:  448 Size:    16
//   float gFogStart;                   // Offset:  464 Size:     4
//   float gFogRange;                   // Offset:  468 Size:     4
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gsamAnisotropicWrap               sampler      NA          NA             s4      1 
// gTreeMapArray                     texture  float4     2darray             t0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
// cbMaterial                        cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
// SV_PrimitiveID           0   x           4   PRIMID    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB1[41], immediateIndexed
      dcl_constantbuffer CB2[2], immediateIndexed
      dcl_sampler s4, mode_default
      dcl_resource_texture2darray (float,float,float,float) t0
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xyz
      dcl_input_ps linear v3.xy
      dcl_input_ps_sgv constant v4.x, primitive_id
      dcl_output o0.xyzw
      dcl_temps 13
      dcl_indexableTemp x0[21], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   v3.x <- pin.TexC.x; v3.y <- pin.TexC.y; 
//   v4.x <- pin.PrimID; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 168 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap12\TreeBillboards\Shaders\TreeSprite.hlsl"
   0: mov r0.x, l(3)
   1: udiv null, r0.x, v4.x, r0.x
   2: utof r0.z, r0.x  // r0.z <- uvw.z

#line 169
   3: mov r0.xy, v3.xyxx
   4: sample_indexable(texture2darray)(float,float,float,float) r0.xyzw, r0.xyzx, t0.xyzw, s4
   5: mul r0.xyzw, r0.xyzw, cb2[0].xyzw  // r0.x <- diffuseAlbedo.x; r0.y <- diffuseAlbedo.y; r0.z <- diffuseAlbedo.z; r0.w <- diffuseAlbedo.w

#line 175
   6: mov r1.x, l(-0.100000)
   7: add r1.x, r0.w, r1.x
   8: lt r1.x, r1.x, l(0.000000)
   9: and r1.x, r1.x, l(-1)
  10: discard_nz r1.x

#line 179
  11: dp3 r1.x, v2.xyzx, v2.xyzx
  12: rsq r1.x, r1.x
  13: mul r1.xyz, r1.xxxx, v2.xyzx  // r1.x <- pin.NormalW.x; r1.y <- pin.NormalW.y; r1.z <- pin.NormalW.z

#line 182
  14: mov r2.xyz, -v1.xyzx
  15: add r2.xyz, r2.xyzx, cb1[24].xyzx  // r2.x <- toEyeW.x; r2.y <- toEyeW.y; r2.z <- toEyeW.z

#line 183
  16: dp3 r1.w, r2.xyzx, r2.xyzx
  17: sqrt r1.w, r1.w  // r1.w <- distToEye

#line 184
  18: div r2.xyz, r2.xyzx, r1.wwww

#line 187
  19: mul r3.xyz, r0.xyzx, cb1[27].xyzx  // r3.x <- ambient.x; r3.y <- ambient.y; r3.z <- ambient.z

#line 189
  20: mov r2.w, -cb2[1].w
  21: add r4.w, r2.w, l(1.000000)  // r4.w <- shininess

#line 190
  22: mov r5.xyz, r0.xyzx  // r5.x <- mat.DiffuseAlbedo.x; r5.y <- mat.DiffuseAlbedo.y; r5.z <- mat.DiffuseAlbedo.z
  23: mov r5.w, cb2[1].x  // r5.w <- mat.FresnelR0.x
  24: mov r4.yz, cb2[1].yyzy  // r4.y <- mat.FresnelR0.y; r4.z <- mat.FresnelR0.z
  25: mov r4.w, r4.w  // r4.w <- mat.Shininess

#line 192
  26: nop 
  27: mov x0[0].xyz, cb1[30].xyzx
  28: mov x0[2].xyz, cb1[31].xyzx
  29: mov x0[4].xyz, cb1[32].xyzx
  30: mov x0[6].xyz, cb1[33].xyzx
  31: mov x0[8].xyz, cb1[34].xyzx
  32: mov x0[10].xyz, cb1[35].xyzx
  33: mov x0[12].xyz, cb1[36].xyzx
  34: mov x0[14].xyz, cb1[37].xyzx
  35: mov x0[16].xyz, cb1[38].xyzx
  36: mov x0[18].xyz, cb1[39].xyzx
  37: mov x0[20].xyz, cb1[40].xyzx
  38: mov r5.xyzw, r5.xyzw
  39: mov r4.yzw, r4.yyzw
  40: mov r1.xyz, r1.xyzx
  41: mov r2.xyz, r2.xyzx

#line 142 "LightingUtil.hlsl"
  42: mov r0.xyz, l(0,0,0,0)  // r0.x <- result.x; r0.y <- result.y; r0.z <- result.z

#line 147
  43: mov r2.w, l(0)  // r2.w <- i
  44: mov r6.xyz, r0.xyzx  // r6.x <- result.x; r6.y <- result.y; r6.z <- result.z
  45: mov r3.w, r2.w  // r3.w <- i
  46: loop 
  47:   ilt r4.x, r3.w, l(3)
  48:   breakc_z r4.x

#line 149
  49:   mov r4.x, l(1.000000)  // r4.x <- shadowFactor.x
  50:   nop 
  51:   imul null, r6.w, r3.w, l(6)
  52:   mov r7.xyz, x0[r6.w + 0].xyzx
  53:   mov r8.xyz, x0[r6.w + 2].xyzx
  54:   mov r9.x, r5.w
  55:   mov r9.yzw, r4.yyzw
  56:   mov r10.xyz, r5.xyzx
  57:   mov r11.xyz, r1.xyzx
  58:   mov r12.xyz, r2.xyzx

#line 67
  59:   mov r8.xyz, -r8.xyzx  // r8.x <- lightVec.x; r8.y <- lightVec.y; r8.z <- lightVec.z

#line 70
  60:   dp3 r6.w, r8.xyzx, r11.xyzx
  61:   max r6.w, r6.w, l(0.000000)  // r6.w <- ndotl

#line 71
  62:   mul r7.xyz, r6.wwww, r7.xyzx  // r7.x <- lightStrength.x; r7.y <- lightStrength.y; r7.z <- lightStrength.z

#line 73
  63:   nop 
  64:   mov r7.xyz, r7.xyzx
  65:   mov r8.xyz, r8.xyzx
  66:   mov r11.xyz, r11.xyzx
  67:   mov r12.xyz, r12.xyzx
  68:   mov r10.xyz, r10.xyzx
  69:   mov r9.xyzw, r9.xyzw

#line 46
  70:   mul r6.w, r9.w, l(256.000000)  // r6.w <- m

#line 47
  71:   add r12.xyz, r8.xyzx, r12.xyzx
  72:   dp3 r7.w, r12.xyzx, r12.xyzx
  73:   rsq r7.w, r7.w
  74:   mul r12.xyz, r7.wwww, r12.xyzx  // r12.x <- halfVec.x; r12.y <- halfVec.y; r12.z <- halfVec.z

#line 49
  75:   add r7.w, r6.w, l(8.000000)
  76:   dp3 r8.w, r12.xyzx, r11.xyzx
  77:   max r8.w, r8.w, l(0.000000)
  78:   log r8.w, r8.w
  79:   mul r6.w, r6.w, r8.w
  80:   exp r6.w, r6.w
  81:   mul r6.w, r6.w, r7.w
  82:   div r6.w, r6.w, l(8.000000)  // r6.w <- roughnessFactor

#line 50
  83:   nop 
  84:   mov r9.xyz, r9.xyzx
  85:   mov r12.xyz, r12.xyzx
  86:   mov r8.xyz, r8.xyzx

#line 36
  87:   dp3 r7.w, r12.xyzx, r8.xyzx
  88:   max r7.w, r7.w, l(0.000000)
  89:   min r7.w, r7.w, l(1.000000)  // r7.w <- cosIncidentAngle

#line 38
  90:   mov r7.w, -r7.w
  91:   add r7.w, r7.w, l(1.000000)  // r7.w <- f0

#line 39
  92:   mov r8.xyz, -r9.xyzx
  93:   add r8.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  94:   mul r8.w, r7.w, r7.w
  95:   mul r8.w, r7.w, r8.w
  96:   mul r8.w, r7.w, r8.w
  97:   mul r7.w, r7.w, r8.w
  98:   mul r8.xyz, r7.wwww, r8.xyzx
  99:   add r8.xyz, r8.xyzx, r9.xyzx  // r8.x <- reflectPercent.x; r8.y <- reflectPercent.y; r8.z <- reflectPercent.z

#line 41
 100:   mov r8.xyz, r8.xyzx  // r8.x <- <SchlickFresnel return value>.x; r8.y <- <SchlickFresnel return value>.y; r8.z <- <SchlickFresnel return value>.z

#line 50
 101:   mov r8.xyz, r8.xyzx  // r8.x <- fresnelFactor.x; r8.y <- fresnelFactor.y; r8.z <- fresnelFactor.z

#line 52
 102:   mul r8.xyz, r6.wwww, r8.xyzx  // r8.x <- specAlbedo.x; r8.y <- specAlbedo.y; r8.z <- specAlbedo.z

#line 56
 103:   add r9.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 104:   div r8.xyz, r8.xyzx, r9.xyzx

#line 58
 105:   add r8.xyz, r8.xyzx, r10.xyzx
 106:   mul r7.xyz, r7.xyzx, r8.xyzx  // r7.x <- <BlinnPhong return value>.x; r7.y <- <BlinnPhong return value>.y; r7.z <- <BlinnPhong return value>.z

#line 73
 107:   mov r7.xyz, r7.xyzx  // r7.x <- <ComputeDirectionalLight return value>.x; r7.y <- <ComputeDirectionalLight return value>.y; r7.z <- <ComputeDirectionalLight return value>.z

#line 149
 108:   mul r7.xyz, r4.xxxx, r7.xyzx
 109:   add r6.xyz, r6.xyzx, r7.xyzx

#line 150
 110:   iadd r3.w, r3.w, l(1)
 111: endloop 

#line 167
 112: mov r6.xyz, r6.xyzx  // r6.x <- <ComputeLighting return value>.x; r6.y <- <ComputeLighting return value>.y; r6.z <- <ComputeLighting return value>.z

#line 192 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap12\TreeBillboards\Shaders\TreeSprite.hlsl"
 113: mov r6.xyz, r6.xyzx  // r6.x <- directLight.x; r6.y <- directLight.y; r6.z <- directLight.z

#line 195
 114: add r0.xyz, r3.xyzx, r6.xyzx  // r0.x <- litColor.x; r0.y <- litColor.y; r0.z <- litColor.z

#line 198
 115: mov r1.x, -cb1[29].x
 116: add r1.x, r1.x, r1.w
 117: div r1.x, r1.x, cb1[29].y
 118: max r1.x, r1.x, l(0.000000)
 119: min r1.x, r1.x, l(1.000000)  // r1.x <- fogAmount

#line 199
 120: mov r1.yzw, -r0.xxyz
 121: add r1.yzw, r1.yyzw, cb1[28].xxyz
 122: mul r1.xyz, r1.yzwy, r1.xxxx
 123: add r0.xyz, r0.xyzx, r1.xyzx

#line 203
 124: mov r0.w, r0.w  // r0.w <- litColor.w

#line 205
 125: mov o0.xyz, r0.xyzx
 126: mov o0.w, r0.w
 127: ret 
// Approximately 128 instruction slots used
 