//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPerObject                       cbuffer      NA          NA            cb0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TessFactor            0   x           0 QUADEDGE   float       
// SV_TessFactor            1   x           1 QUADEDGE   float       
// SV_TessFactor            2   x           2 QUADEDGE   float       
// SV_TessFactor            3   x           3 QUADEDGE   float       
// SV_InsideTessFactor      0   x           4  QUADINT   float       
// SV_InsideTessFactor      1   x           5  QUADINT   float       
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
// Tessellation Domain   # of control points
// -------------------- --------------------
// Quadrilateral                           9
//
      ds_5_0
      dcl_input_control_point_count 9
      dcl_tessellator_domain domain_quad
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[20], immediateIndexed
      dcl_input vDomain.xy
      dcl_input vicp[9][0].xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
//
// Initial variable locations:
//   vpc0.x <- patchTess.EdgeTess[0]; 
//   vpc1.x <- patchTess.EdgeTess[1]; 
//   vpc2.x <- patchTess.EdgeTess[2]; 
//   vpc3.x <- patchTess.EdgeTess[3]; 
//   vpc4.x <- patchTess.InsideTess[0]; 
//   vpc5.x <- patchTess.InsideTess[1]; 
//   vDomain.x <- uv.x; vDomain.y <- uv.y; 
//   o0.x <- <DS return value>.PosH.x; o0.y <- <DS return value>.PosH.y; o0.z <- <DS return value>.PosH.z; o0.w <- <DS return value>.PosH.w; 
//   vicp[0][0].x <- bezPatch[0].PosL.x; vicp[0][0].y <- bezPatch[0].PosL.y; vicp[0][0].z <- bezPatch[0].PosL.z; 
//   vicp[1][0].x <- bezPatch[1].PosL.x; vicp[1][0].y <- bezPatch[1].PosL.y; vicp[1][0].z <- bezPatch[1].PosL.z; 
//   vicp[2][0].x <- bezPatch[2].PosL.x; vicp[2][0].y <- bezPatch[2].PosL.y; vicp[2][0].z <- bezPatch[2].PosL.z; 
//   vicp[3][0].x <- bezPatch[3].PosL.x; vicp[3][0].y <- bezPatch[3].PosL.y; vicp[3][0].z <- bezPatch[3].PosL.z; 
//   vicp[4][0].x <- bezPatch[4].PosL.x; vicp[4][0].y <- bezPatch[4].PosL.y; vicp[4][0].z <- bezPatch[4].PosL.z; 
//   vicp[5][0].x <- bezPatch[5].PosL.x; vicp[5][0].y <- bezPatch[5].PosL.y; vicp[5][0].z <- bezPatch[5].PosL.z; 
//   vicp[6][0].x <- bezPatch[6].PosL.x; vicp[6][0].y <- bezPatch[6].PosL.y; vicp[6][0].z <- bezPatch[6].PosL.z; 
//   vicp[7][0].x <- bezPatch[7].PosL.x; vicp[7][0].y <- bezPatch[7].PosL.y; vicp[7][0].z <- bezPatch[7].PosL.z; 
//   vicp[8][0].x <- bezPatch[8].PosL.x; vicp[8][0].y <- bezPatch[8].PosL.y; vicp[8][0].z <- bezPatch[8].PosL.z
//
#line 186 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap14\Chap14_Solution\Chap14_7\Shaders\BezierTessellation.hlsl"
   0: nop 
   1: mov r0.x, vDomain.x

#line 140
   2: mov r0.y, -r0.x
   3: add r0.y, r0.y, l(1.000000)  // r0.y <- invT

#line 142
   4: mul r1.x, r0.y, r0.y  // r1.x <- <BernsteinBasisQuadratic return value>.x
   5: mul r0.z, r0.x, l(2.000000)
   6: mul r1.y, r0.y, r0.z  // r1.y <- <BernsteinBasisQuadratic return value>.y
   7: mul r1.z, r0.x, r0.x  // r1.z <- <BernsteinBasisQuadratic return value>.z

#line 186
   8: mov r1.xyz, r1.xyzx  // r1.x <- basisU.x; r1.y <- basisU.y; r1.z <- basisU.z

#line 187
   9: nop 
  10: mov r0.x, vDomain.y

#line 140
  11: mov r0.y, -r0.x
  12: add r0.y, r0.y, l(1.000000)  // r0.y <- invT

#line 142
  13: mul r2.x, r0.y, r0.y  // r2.x <- <BernsteinBasisQuadratic return value>.x
  14: mul r0.z, r0.x, l(2.000000)
  15: mul r2.y, r0.y, r0.z  // r2.y <- <BernsteinBasisQuadratic return value>.y
  16: mul r2.z, r0.x, r0.x  // r2.z <- <BernsteinBasisQuadratic return value>.z

#line 187
  17: mov r2.xyz, r2.xyzx  // r2.x <- basisV.x; r2.y <- basisV.y; r2.z <- basisV.z

#line 189
  18: nop 
  19: mov r1.xyz, r1.xyzx
  20: mov r2.xyz, r2.xyzx

#line 160
  21: mul r0.xyz, r1.xxxx, vicp[0][0].xyzx
  22: mul r3.xyz, r1.yyyy, vicp[1][0].xyzx
  23: add r0.xyz, r0.xyzx, r3.xyzx
  24: mul r3.xyz, r1.zzzz, vicp[2][0].xyzx
  25: add r0.xyz, r0.xyzx, r3.xyzx
  26: mul r0.xyz, r0.xyzx, r2.xxxx  // r0.x <- sum.x; r0.y <- sum.y; r0.z <- sum.z

#line 161
  27: mul r3.xyz, r1.xxxx, vicp[3][0].xyzx
  28: mul r4.xyz, r1.yyyy, vicp[4][0].xyzx
  29: add r3.xyz, r3.xyzx, r4.xyzx
  30: mul r4.xyz, r1.zzzz, vicp[5][0].xyzx
  31: add r3.xyz, r3.xyzx, r4.xyzx
  32: mul r2.xyw, r2.yyyy, r3.xyxz
  33: add r0.xyz, r0.xyzx, r2.xywx

#line 162
  34: mul r2.xyw, r1.xxxx, vicp[6][0].xyxz
  35: mul r1.xyw, r1.yyyy, vicp[7][0].xyxz
  36: add r1.xyw, r1.xyxw, r2.xyxw
  37: mul r2.xyw, r1.zzzz, vicp[8][0].xyxz
  38: add r1.xyz, r1.xywx, r2.xywx
  39: mul r1.xyz, r1.xyzx, r2.zzzz
  40: add r0.xyz, r0.xyzx, r1.xyzx

#line 164
  41: mov r0.xyz, r0.xyzx  // r0.x <- <CubicBezierSum return value>.x; r0.y <- <CubicBezierSum return value>.y; r0.z <- <CubicBezierSum return value>.z

#line 189
  42: mov r0.xyz, r0.xyzx  // r0.x <- p.x; r0.y <- p.y; r0.z <- p.z

#line 191
  43: mov r0.w, l(1.000000)
  44: dp4 r1.x, r0.xyzw, cb0[0].xyzw  // r1.x <- posW.x
  45: dp4 r1.y, r0.xyzw, cb0[1].xyzw  // r1.y <- posW.y
  46: dp4 r1.z, r0.xyzw, cb0[2].xyzw  // r1.z <- posW.z
  47: dp4 r1.w, r0.xyzw, cb0[3].xyzw  // r1.w <- posW.w

#line 192
  48: dp4 r0.x, r1.xyzw, cb1[16].xyzw  // r0.x <- dout.PosH.x
  49: dp4 r0.y, r1.xyzw, cb1[17].xyzw  // r0.y <- dout.PosH.y
  50: dp4 r0.z, r1.xyzw, cb1[18].xyzw  // r0.z <- dout.PosH.z
  51: dp4 r0.w, r1.xyzw, cb1[19].xyzw  // r0.w <- dout.PosH.w

#line 194
  52: mov o0.xyzw, r0.xyzw
  53: ret 
// Approximately 54 instruction slots used
 