//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  448
//       float FalloffStart;            // Offset:  460
//       float3 Direction;              // Offset:  464
//       float FalloffEnd;              // Offset:  476
//       float3 Position;               // Offset:  480
//       float SpotPower;               // Offset:  492
//
//   } gLights[16];                     // Offset:  448 Size:   768
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbMaterial                        cbuffer      NA          NA            cb1      1 
// cbPass                            cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB1[2], immediateIndexed
      dcl_constantbuffer CB2[30], immediateIndexed
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xyz
      dcl_output o0.xyzw
      dcl_temps 8
      dcl_indexableTemp x0[3], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 97 "C:\cg\DX12\Solution\Chap8\Chap8_LitWaves\Shaders\Default.hlsl"
   0: dp3 r0.x, v2.xyzx, v2.xyzx
   1: rsq r0.x, r0.x
   2: mul r0.xyz, r0.xxxx, v2.xyzx  // r0.x <- pin.NormalW.x; r0.y <- pin.NormalW.y; r0.z <- pin.NormalW.z

#line 100
   3: mov r1.xyz, -v1.xyzx
   4: add r1.xyz, r1.xyzx, cb2[24].xyzx
   5: dp3 r0.w, r1.xyzx, r1.xyzx
   6: rsq r0.w, r0.w
   7: mul r1.xyz, r0.wwww, r1.xyzx  // r1.x <- toEyeW.x; r1.y <- toEyeW.y; r1.z <- toEyeW.z

#line 103
   8: mul r2.xyz, cb1[0].xyzx, cb2[27].xyzx  // r2.x <- ambient.x; r2.y <- ambient.y; r2.z <- ambient.z

#line 105
   9: mov r0.w, -cb1[1].w
  10: add r3.w, r0.w, l(1.000000)  // r3.w <- shininess

#line 106
  11: mov r3.xyz, cb1[1].xyzx  // r3.x <- mat.FresnelR0.x; r3.y <- mat.FresnelR0.y; r3.z <- mat.FresnelR0.z
  12: mov r3.w, r3.w  // r3.w <- mat.Shininess
  13: mov r4.xyz, cb1[0].xyzx  // r4.x <- mat.DiffuseAlbedo.x; r4.y <- mat.DiffuseAlbedo.y; r4.z <- mat.DiffuseAlbedo.z

#line 108
  14: nop 
  15: mov x0[0].xyz, cb2[28].xyzx
  16: mov x0[2].xyz, cb2[29].xyzx
  17: mov r3.xyzw, r3.xyzw
  18: mov r4.xyz, r4.xyzx
  19: mov r0.xyz, r0.xyzx
  20: mov r1.xyz, r1.xyzx

#line 142 "LightingUtil.hlsl"
  21: mov r5.xyz, l(0,0,0,0)  // r5.x <- result.x; r5.y <- result.y; r5.z <- result.z

#line 149
  22: nop 
  23: mov r6.xyz, x0[0].xyzx
  24: mov r7.xyz, x0[2].xyzx
  25: mov r3.xyzw, r3.xyzw
  26: mov r4.xyz, r4.xyzx
  27: mov r0.xyz, r0.xyzx
  28: mov r1.xyz, r1.xyzx

#line 67
  29: mov r7.xyz, -r7.xyzx  // r7.x <- lightVec.x; r7.y <- lightVec.y; r7.z <- lightVec.z

#line 70
  30: dp3 r0.w, r7.xyzx, r0.xyzx
  31: max r0.w, r0.w, l(0.000000)  // r0.w <- ndotl

#line 71
  32: mul r6.xyz, r0.wwww, r6.xyzx  // r6.x <- lightStrength.x; r6.y <- lightStrength.y; r6.z <- lightStrength.z

#line 73
  33: nop 
  34: mov r6.xyz, r6.xyzx
  35: mov r7.xyz, r7.xyzx
  36: mov r0.xyz, r0.xyzx
  37: mov r1.xyz, r1.xyzx
  38: mov r4.xyz, r4.xyzx
  39: mov r3.xyzw, r3.xyzw

#line 46
  40: mul r0.w, r3.w, l(256.000000)  // r0.w <- m

#line 47
  41: add r1.xyz, r7.xyzx, r1.xyzx
  42: dp3 r1.w, r1.xyzx, r1.xyzx
  43: rsq r1.w, r1.w
  44: mul r1.xyz, r1.wwww, r1.xyzx  // r1.x <- halfVec.x; r1.y <- halfVec.y; r1.z <- halfVec.z

#line 49
  45: add r1.w, r0.w, l(8.000000)
  46: dp3 r0.x, r1.xyzx, r0.xyzx
  47: max r0.x, r0.x, l(0.000000)
  48: log r0.x, r0.x
  49: mul r0.x, r0.x, r0.w
  50: exp r0.x, r0.x
  51: mul r0.x, r0.x, r1.w
  52: div r0.x, r0.x, l(8.000000)  // r0.x <- roughnessFactor

#line 50
  53: nop 
  54: mov r3.xyz, r3.xyzx
  55: mov r1.xyz, r1.xyzx
  56: mov r7.xyz, r7.xyzx

#line 36
  57: dp3 r0.y, r1.xyzx, r7.xyzx
  58: max r0.y, r0.y, l(0.000000)
  59: min r0.y, r0.y, l(1.000000)  // r0.y <- cosIncidentAngle

#line 38
  60: mov r0.y, -r0.y
  61: add r0.y, r0.y, l(1.000000)  // r0.y <- f0

#line 39
  62: mov r1.xyz, -r3.xyzx
  63: add r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  64: mul r0.z, r0.y, r0.y
  65: mul r0.z, r0.y, r0.z
  66: mul r0.z, r0.y, r0.z
  67: mul r0.y, r0.y, r0.z
  68: mul r0.yzw, r0.yyyy, r1.xxyz
  69: add r0.yzw, r0.yyzw, r3.xxyz  // r0.y <- reflectPercent.x; r0.z <- reflectPercent.y; r0.w <- reflectPercent.z

#line 41
  70: mov r0.yzw, r0.yyzw  // r0.y <- <SchlickFresnel return value>.x; r0.z <- <SchlickFresnel return value>.y; r0.w <- <SchlickFresnel return value>.z

#line 50
  71: mov r0.yzw, r0.yyzw  // r0.y <- fresnelFactor.x; r0.z <- fresnelFactor.y; r0.w <- fresnelFactor.z

#line 52
  72: mul r0.xyz, r0.xxxx, r0.yzwy  // r0.x <- specAlbedo.x; r0.y <- specAlbedo.y; r0.z <- specAlbedo.z

#line 56
  73: add r1.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  74: div r0.xyz, r0.xyzx, r1.xyzx

#line 58
  75: add r0.xyz, r0.xyzx, r4.xyzx
  76: mul r0.xyz, r6.xyzx, r0.xyzx  // r0.x <- <BlinnPhong return value>.x; r0.y <- <BlinnPhong return value>.y; r0.z <- <BlinnPhong return value>.z

#line 73
  77: mov r0.xyz, r0.xyzx  // r0.x <- <ComputeDirectionalLight return value>.x; r0.y <- <ComputeDirectionalLight return value>.y; r0.z <- <ComputeDirectionalLight return value>.z

#line 149
  78: mul r0.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  79: add r0.xyz, r0.xyzx, r5.xyzx  // r0.x <- result.x; r0.y <- result.y; r0.z <- result.z

#line 167
  80: mov r0.xyz, r0.xyzx  // r0.x <- <ComputeLighting return value>.x; r0.y <- <ComputeLighting return value>.y; r0.z <- <ComputeLighting return value>.z

#line 108 "C:\cg\DX12\Solution\Chap8\Chap8_LitWaves\Shaders\Default.hlsl"
  81: mov r0.xyz, r0.xyzx  // r0.x <- directLight.x; r0.y <- directLight.y; r0.z <- directLight.z

#line 111
  82: add r0.xyz, r0.xyzx, r2.xyzx  // r0.x <- litColor.x; r0.y <- litColor.y; r0.z <- litColor.z

#line 114
  83: mov r0.w, cb1[0].w  // r0.w <- litColor.w

#line 116
  84: mov o0.xyz, r0.xyzx
  85: mov o0.w, r0.w
  86: ret 
// Approximately 87 instruction slots used
 