//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPerObject                       cbuffer      NA          NA            cb0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TEXCOORD                 0   xyz         2     NONE   float       
// SV_PrimitiveID           0    N/A   primID   PRIMID    uint    YES
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
// SV_PrimitiveID           0   x           4   PRIMID    uint   x   
//
      gs_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[3], immediateIndexed
      dcl_constantbuffer CB1[25], immediateIndexed
      dcl_input v[3][0].xyz
      dcl_input v[3][1].xyz
      dcl_input v[3][2].xyz
      dcl_input vPrim
      dcl_temps 16
      dcl_inputprimitive triangle 
      dcl_stream m0
      dcl_outputtopology trianglestrip 
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xy
      dcl_output_sgv o4.x, primitive_id
      dcl_maxout 48
//
// Initial variable locations:
//   vPrim <- primID; 
//   m0 <- triStream; 
//   v[0][0].x <- gin[0].PosW.x; v[0][0].y <- gin[0].PosW.y; v[0][0].z <- gin[0].PosW.z; 
//   v[0][1].x <- gin[0].normal.x; v[0][1].y <- gin[0].normal.y; v[0][1].z <- gin[0].normal.z; 
//   v[0][2].x <- gin[0].texC.x; v[0][2].y <- gin[0].texC.y; v[0][2].z <- gin[0].texC.z; 
//   v[1][0].x <- gin[1].PosW.x; v[1][0].y <- gin[1].PosW.y; v[1][0].z <- gin[1].PosW.z; 
//   v[1][1].x <- gin[1].normal.x; v[1][1].y <- gin[1].normal.y; v[1][1].z <- gin[1].normal.z; 
//   v[1][2].x <- gin[1].texC.x; v[1][2].y <- gin[1].texC.y; v[1][2].z <- gin[1].texC.z; 
//   v[2][0].x <- gin[2].PosW.x; v[2][0].y <- gin[2].PosW.y; v[2][0].z <- gin[2].PosW.z; 
//   v[2][1].x <- gin[2].normal.x; v[2][1].y <- gin[2].normal.y; v[2][1].z <- gin[2].normal.z; 
//   v[2][2].x <- gin[2].texC.x; v[2][2].y <- gin[2].texC.y; v[2][2].z <- gin[2].texC.z
//
#line 145 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap12\Chap12_2\Shaders\Sphere.hlsl"
   0: mov r0.xyz, v[0][0].xyzx  // r0.x <- a.x; r0.y <- a.y; r0.z <- a.z

#line 146
   1: mov r1.xyz, v[1][0].xyzx  // r1.x <- b.x; r1.y <- b.y; r1.z <- b.z

#line 147
   2: mov r2.xyz, v[2][0].xyzx  // r2.x <- c.x; r2.y <- c.y; r2.z <- c.z

#line 149
   3: dp3 r3.x, r0.xyzx, r0.xyzx
   4: sqrt r3.x, r3.x
   5: dp3 r3.y, r1.xyzx, r1.xyzx
   6: sqrt r3.y, r3.y
   7: add r3.x, r3.y, r3.x
   8: dp3 r3.y, r2.xyzx, r2.xyzx
   9: sqrt r3.y, r3.y
  10: add r3.x, r3.y, r3.x
  11: div r3.x, r3.x, l(3.000000)  // r3.x <- R

#line 151
  12: mov r3.yzw, -cb1[24].xxyz
  13: add r4.x, r3.y, cb0[0].w
  14: add r4.y, r3.z, cb0[1].w
  15: add r4.z, r3.w, cb0[2].w
  16: dp3 r3.y, r4.xyzx, r4.xyzx
  17: sqrt r3.y, r3.y  // r3.y <- dist

#line 153
  18: lt r3.z, r3.y, l(15.000000)
  19: if_nz r3.z

#line 155
  20:   nop 
  21:   add r4.xyz, r0.xyzx, r1.xyzx
  22:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  23:   mov r3.x, r3.x

#line 111
  24:   dp3 r3.z, r4.xyzx, r4.xyzx
  25:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
  26:   lt r3.w, r3.z, l(0.000001)
  27:   if_nz r3.w

#line 113
  28:     itof r5.yz, l(0, 0, 0, 0)  // r5.y <- <ProjectKeepRadius return value>.y; r5.z <- <ProjectKeepRadius return value>.z
  29:     mov r5.x, r3.x
  30:   endif   // r5.y <- <ProjectKeepRadius return value>.y; r5.z <- <ProjectKeepRadius return value>.z; r5.x <- <ProjectKeepRadius return value>.x

#line 114
  31:   if_z r3.w
  32:     div r4.xyz, r4.xyzx, r3.zzzz
  33:     mul r5.xyz, r3.xxxx, r4.xyzx
  34:   endif 

#line 155
  35:   mov r5.xyz, r5.xyzx  // r5.x <- ab.x; r5.y <- ab.y; r5.z <- ab.z

#line 156
  36:   nop 
  37:   add r4.xyz, r1.xyzx, r2.xyzx
  38:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  39:   mov r3.x, r3.x

#line 111
  40:   dp3 r3.z, r4.xyzx, r4.xyzx
  41:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
  42:   lt r3.w, r3.z, l(0.000001)
  43:   if_nz r3.w

#line 113
  44:     itof r6.yz, l(0, 0, 0, 0)  // r6.y <- <ProjectKeepRadius return value>.y; r6.z <- <ProjectKeepRadius return value>.z
  45:     mov r6.x, r3.x  // r5.y <- <ProjectKeepRadius return value>.y; r5.z <- <ProjectKeepRadius return value>.z
  46:   endif   // r6.y <- <ProjectKeepRadius return value>.y; r6.z <- <ProjectKeepRadius return value>.z; r6.x <- <ProjectKeepRadius return value>.x

#line 114
  47:   if_z r3.w
  48:     div r4.xyz, r4.xyzx, r3.zzzz
  49:     mul r6.xyz, r3.xxxx, r4.xyzx
  50:   endif 

#line 156
  51:   mov r6.xyz, r6.xyzx  // r6.x <- bc.x; r6.y <- bc.y; r6.z <- bc.z

#line 157
  52:   nop 
  53:   add r4.xyz, r0.xyzx, r2.xyzx
  54:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  55:   mov r3.x, r3.x

#line 111
  56:   dp3 r3.z, r4.xyzx, r4.xyzx
  57:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
  58:   lt r3.w, r3.z, l(0.000001)
  59:   if_nz r3.w

#line 113
  60:     itof r7.yz, l(0, 0, 0, 0)  // r7.y <- <ProjectKeepRadius return value>.y; r7.z <- <ProjectKeepRadius return value>.z
  61:     mov r7.x, r3.x  // r6.y <- <ProjectKeepRadius return value>.y; r6.z <- <ProjectKeepRadius return value>.z
  62:   endif   // r7.y <- <ProjectKeepRadius return value>.y; r7.z <- <ProjectKeepRadius return value>.z; r7.x <- <ProjectKeepRadius return value>.x

#line 114
  63:   if_z r3.w
  64:     div r4.xyz, r4.xyzx, r3.zzzz
  65:     mul r7.xyz, r3.xxxx, r4.xyzx
  66:   endif 

#line 157
  67:   mov r7.xyz, r7.xyzx  // r7.x <- ca.x; r7.y <- ca.y; r7.z <- ca.z

#line 159
  68:   mov r0.xyz, r0.xyzx  // r0.x <- a0.x; r0.y <- a0.y; r0.z <- a0.z
  69:   mov r5.xyz, r5.xyzx  // r5.x <- b0.x; r5.y <- b0.y; r5.z <- b0.z
  70:   mov r7.xyz, r7.xyzx  // r7.x <- c0.x; r7.y <- c0.y; r7.z <- c0.z

#line 160
  71:   nop 
  72:   add r4.xyz, r0.xyzx, r5.xyzx
  73:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  74:   mov r3.x, r3.x

#line 111
  75:   dp3 r3.z, r4.xyzx, r4.xyzx
  76:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
  77:   lt r3.w, r3.z, l(0.000001)
  78:   if_nz r3.w

#line 113
  79:     itof r8.yz, l(0, 0, 0, 0)  // r8.y <- <ProjectKeepRadius return value>.y; r8.z <- <ProjectKeepRadius return value>.z
  80:     mov r8.x, r3.x  // r7.y <- <ProjectKeepRadius return value>.y; r7.z <- <ProjectKeepRadius return value>.z
  81:   endif   // r8.y <- <ProjectKeepRadius return value>.y; r8.z <- <ProjectKeepRadius return value>.z; r8.x <- <ProjectKeepRadius return value>.x

#line 114
  82:   if_z r3.w
  83:     div r4.xyz, r4.xyzx, r3.zzzz
  84:     mul r8.xyz, r3.xxxx, r4.xyzx
  85:   endif 

#line 160
  86:   mov r8.xyz, r8.xyzx  // r8.x <- a0b0.x; r8.y <- a0b0.y; r8.z <- a0b0.z

#line 161
  87:   nop 
  88:   add r4.xyz, r5.xyzx, r7.xyzx
  89:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  90:   mov r3.x, r3.x

#line 111
  91:   dp3 r3.z, r4.xyzx, r4.xyzx
  92:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
  93:   lt r3.w, r3.z, l(0.000001)
  94:   if_nz r3.w

#line 113
  95:     itof r9.yz, l(0, 0, 0, 0)  // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z
  96:     mov r9.x, r3.x  // r8.y <- <ProjectKeepRadius return value>.y; r8.z <- <ProjectKeepRadius return value>.z
  97:   endif   // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z; r9.x <- <ProjectKeepRadius return value>.x

#line 114
  98:   if_z r3.w
  99:     div r4.xyz, r4.xyzx, r3.zzzz
 100:     mul r9.xyz, r3.xxxx, r4.xyzx
 101:   endif 

#line 161
 102:   mov r9.xyz, r9.xyzx  // r9.x <- b0c0.x; r9.y <- b0c0.y; r9.z <- b0c0.z

#line 162
 103:   nop 
 104:   add r4.xyz, r0.xyzx, r7.xyzx
 105:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 106:   mov r3.x, r3.x

#line 111
 107:   dp3 r3.z, r4.xyzx, r4.xyzx
 108:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 109:   lt r3.w, r3.z, l(0.000001)
 110:   if_nz r3.w

#line 113
 111:     itof r10.yz, l(0, 0, 0, 0)  // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z
 112:     mov r10.x, r3.x  // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z
 113:   endif   // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z; r10.x <- <ProjectKeepRadius return value>.x

#line 114
 114:   if_z r3.w
 115:     div r4.xyz, r4.xyzx, r3.zzzz
 116:     mul r10.xyz, r3.xxxx, r4.xyzx
 117:   endif 

#line 162
 118:   mov r10.xyz, r10.xyzx  // r10.x <- c0a0.x; r10.y <- c0a0.y; r10.z <- c0a0.z

#line 163
 119:   nop 
 120:   mov r0.xyz, r0.xyzx
 121:   mov r8.xyz, r8.xyzx
 122:   mov r10.xyz, r10.xyzx
 123:   nop 
 124:   mov r3.z, vPrim

#line 120
 125:   mov r3.z, r3.z  // r3.z <- o.PrimID

#line 122
 126:   mov r0.xyz, r0.xyzx  // r0.x <- o.PosW.x; r0.y <- o.PosW.y; r0.z <- o.PosW.z

#line 123
 127:   dp3 r3.w, r0.xyzx, r0.xyzx
 128:   rsq r3.w, r3.w
 129:   mul r4.xyz, r0.xyzx, r3.wwww  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 124
 130:   mov r11.xy, l(0,1.000000,0,0)  // r11.x <- o.TexC.x; r11.y <- o.TexC.y

#line 125
 131:   mov r0.w, l(1.000000)
 132:   dp4 r12.x, r0.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
 133:   dp4 r12.y, r0.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
 134:   dp4 r12.z, r0.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
 135:   dp4 r12.w, r0.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 126
 136:   mov o0.xyzw, r12.xyzw
 137:   mov o1.xyz, r0.xyzx
 138:   mov o2.xyz, r4.xyzx
 139:   mov o3.xy, r11.xyxx
 140:   mov o4.x, r3.z
 141:   emit_stream m0

#line 127
 142:   mov r8.xyz, r8.xyzx  // r8.x <- o.PosW.x; r8.y <- o.PosW.y; r8.z <- o.PosW.z

#line 128
 143:   dp3 r3.w, r8.xyzx, r8.xyzx
 144:   rsq r3.w, r3.w
 145:   mul r4.xyz, r3.wwww, r8.xyzx

#line 129
 146:   mov r11.xy, l(1.000000,1.000000,0,0)

#line 130
 147:   mov r8.w, l(1.000000)
 148:   dp4 r12.x, r8.xyzw, cb1[16].xyzw
 149:   dp4 r12.y, r8.xyzw, cb1[17].xyzw
 150:   dp4 r12.z, r8.xyzw, cb1[18].xyzw
 151:   dp4 r12.w, r8.xyzw, cb1[19].xyzw

#line 131
 152:   mov o0.xyzw, r12.xyzw
 153:   mov o1.xyz, r8.xyzx
 154:   mov o2.xyz, r4.xyzx
 155:   mov o3.xy, r11.xyxx
 156:   mov o4.x, r3.z
 157:   emit_stream m0

#line 132
 158:   mov r10.xyz, r10.xyzx  // r10.x <- o.PosW.x; r10.y <- o.PosW.y; r10.z <- o.PosW.z

#line 133
 159:   dp3 r3.w, r10.xyzx, r10.xyzx
 160:   rsq r3.w, r3.w
 161:   mul r4.xyz, r3.wwww, r10.xyzx

#line 134
 162:   mov r11.xy, l(0.500000,0,0,0)

#line 135
 163:   mov r10.w, l(1.000000)
 164:   dp4 r12.x, r10.xyzw, cb1[16].xyzw
 165:   dp4 r12.y, r10.xyzw, cb1[17].xyzw
 166:   dp4 r12.z, r10.xyzw, cb1[18].xyzw
 167:   dp4 r12.w, r10.xyzw, cb1[19].xyzw

#line 136
 168:   mov o0.xyzw, r12.xyzw
 169:   mov o1.xyz, r10.xyzx
 170:   mov o2.xyz, r4.xyzx
 171:   mov o3.xy, r11.xyxx
 172:   mov o4.x, r3.z
 173:   emit_stream m0

#line 163
 174:   nop 

#line 164
 175:   nop 
 176:   mov r4.xyz, r8.xyzx
 177:   mov r11.xyz, r5.xyzx
 178:   mov r9.xyz, r9.xyzx
 179:   nop 
 180:   mov r3.z, vPrim

#line 120
 181:   mov r3.z, r3.z

#line 122
 182:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
 183:   dp3 r3.w, r4.xyzx, r4.xyzx
 184:   rsq r3.w, r3.w
 185:   mul r12.xyz, r3.wwww, r4.xyzx  // r12.x <- o.NormalW.x; r12.y <- o.NormalW.y; r12.z <- o.NormalW.z

#line 124
 186:   mov r13.xy, l(0,1.000000,0,0)  // r13.x <- o.TexC.x; r13.y <- o.TexC.y

#line 125
 187:   mov r4.w, l(1.000000)
 188:   dp4 r14.x, r4.xyzw, cb1[16].xyzw  // r14.x <- o.PosH.x
 189:   dp4 r14.y, r4.xyzw, cb1[17].xyzw  // r14.y <- o.PosH.y
 190:   dp4 r14.z, r4.xyzw, cb1[18].xyzw  // r14.z <- o.PosH.z
 191:   dp4 r14.w, r4.xyzw, cb1[19].xyzw  // r14.w <- o.PosH.w

#line 126
 192:   mov o0.xyzw, r14.xyzw
 193:   mov o1.xyz, r4.xyzx
 194:   mov o2.xyz, r12.xyzx
 195:   mov o3.xy, r13.xyxx
 196:   mov o4.x, r3.z
 197:   emit_stream m0

#line 127
 198:   mov r11.xyz, r11.xyzx  // r11.x <- o.PosW.x; r11.y <- o.PosW.y; r11.z <- o.PosW.z

#line 128
 199:   dp3 r3.w, r11.xyzx, r11.xyzx
 200:   rsq r3.w, r3.w
 201:   mul r4.xyz, r3.wwww, r11.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
 202:   mov r12.xy, l(1.000000,1.000000,0,0)  // r12.x <- o.TexC.x; r12.y <- o.TexC.y

#line 130
 203:   mov r11.w, l(1.000000)
 204:   dp4 r13.x, r11.xyzw, cb1[16].xyzw  // r13.x <- o.PosH.x
 205:   dp4 r13.y, r11.xyzw, cb1[17].xyzw  // r13.y <- o.PosH.y
 206:   dp4 r13.z, r11.xyzw, cb1[18].xyzw  // r13.z <- o.PosH.z
 207:   dp4 r13.w, r11.xyzw, cb1[19].xyzw  // r13.w <- o.PosH.w

#line 131
 208:   mov o0.xyzw, r13.xyzw
 209:   mov o1.xyz, r11.xyzx
 210:   mov o2.xyz, r4.xyzx
 211:   mov o3.xy, r12.xyxx
 212:   mov o4.x, r3.z
 213:   emit_stream m0

#line 132
 214:   mov r9.xyz, r9.xyzx  // r9.x <- o.PosW.x; r9.y <- o.PosW.y; r9.z <- o.PosW.z

#line 133
 215:   dp3 r3.w, r9.xyzx, r9.xyzx
 216:   rsq r3.w, r3.w
 217:   mul r4.xyz, r3.wwww, r9.xyzx

#line 134
 218:   mov r11.xy, l(0.500000,0,0,0)  // r11.x <- o.TexC.x; r11.y <- o.TexC.y

#line 135
 219:   mov r9.w, l(1.000000)
 220:   dp4 r12.x, r9.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
 221:   dp4 r12.y, r9.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
 222:   dp4 r12.z, r9.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
 223:   dp4 r12.w, r9.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 136
 224:   mov o0.xyzw, r12.xyzw
 225:   mov o1.xyz, r9.xyzx
 226:   mov o2.xyz, r4.xyzx
 227:   mov o3.xy, r11.xyxx
 228:   mov o4.x, r3.z
 229:   emit_stream m0

#line 164
 230:   nop   // m0 <- triStream

#line 165
 231:   nop 
 232:   mov r4.xyz, r10.xyzx
 233:   mov r11.xyz, r9.xyzx
 234:   mov r12.xyz, r7.xyzx
 235:   nop 
 236:   mov r3.z, vPrim

#line 120
 237:   mov r3.z, r3.z

#line 122
 238:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
 239:   dp3 r3.w, r4.xyzx, r4.xyzx
 240:   rsq r3.w, r3.w
 241:   mul r13.xyz, r3.wwww, r4.xyzx  // r13.x <- o.NormalW.x; r13.y <- o.NormalW.y; r13.z <- o.NormalW.z

#line 124
 242:   mov r14.xy, l(0,1.000000,0,0)  // r14.x <- o.TexC.x; r14.y <- o.TexC.y

#line 125
 243:   mov r4.w, l(1.000000)
 244:   dp4 r15.x, r4.xyzw, cb1[16].xyzw  // r15.x <- o.PosH.x
 245:   dp4 r15.y, r4.xyzw, cb1[17].xyzw  // r15.y <- o.PosH.y
 246:   dp4 r15.z, r4.xyzw, cb1[18].xyzw  // r15.z <- o.PosH.z
 247:   dp4 r15.w, r4.xyzw, cb1[19].xyzw  // r15.w <- o.PosH.w

#line 126
 248:   mov o0.xyzw, r15.xyzw
 249:   mov o1.xyz, r4.xyzx
 250:   mov o2.xyz, r13.xyzx
 251:   mov o3.xy, r14.xyxx
 252:   mov o4.x, r3.z
 253:   emit_stream m0

#line 127
 254:   mov r11.xyz, r11.xyzx  // r11.x <- o.PosW.x; r11.y <- o.PosW.y; r11.z <- o.PosW.z

#line 128
 255:   dp3 r3.w, r11.xyzx, r11.xyzx
 256:   rsq r3.w, r3.w
 257:   mul r4.xyz, r3.wwww, r11.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
 258:   mov r13.xy, l(1.000000,1.000000,0,0)  // r13.x <- o.TexC.x; r13.y <- o.TexC.y

#line 130
 259:   mov r11.w, l(1.000000)
 260:   dp4 r14.x, r11.xyzw, cb1[16].xyzw  // r14.x <- o.PosH.x
 261:   dp4 r14.y, r11.xyzw, cb1[17].xyzw  // r14.y <- o.PosH.y
 262:   dp4 r14.z, r11.xyzw, cb1[18].xyzw  // r14.z <- o.PosH.z
 263:   dp4 r14.w, r11.xyzw, cb1[19].xyzw  // r14.w <- o.PosH.w

#line 131
 264:   mov o0.xyzw, r14.xyzw
 265:   mov o1.xyz, r11.xyzx
 266:   mov o2.xyz, r4.xyzx
 267:   mov o3.xy, r13.xyxx
 268:   mov o4.x, r3.z
 269:   emit_stream m0

#line 132
 270:   mov r12.xyz, r12.xyzx  // r12.x <- o.PosW.x; r12.y <- o.PosW.y; r12.z <- o.PosW.z

#line 133
 271:   dp3 r3.w, r12.xyzx, r12.xyzx
 272:   rsq r3.w, r3.w
 273:   mul r4.xyz, r3.wwww, r12.xyzx

#line 134
 274:   mov r11.xy, l(0.500000,0,0,0)  // r11.x <- o.TexC.x; r11.y <- o.TexC.y

#line 135
 275:   mov r12.w, l(1.000000)
 276:   dp4 r13.x, r12.xyzw, cb1[16].xyzw  // r13.x <- o.PosH.x
 277:   dp4 r13.y, r12.xyzw, cb1[17].xyzw  // r13.y <- o.PosH.y
 278:   dp4 r13.z, r12.xyzw, cb1[18].xyzw  // r13.z <- o.PosH.z
 279:   dp4 r13.w, r12.xyzw, cb1[19].xyzw  // r13.w <- o.PosH.w

#line 136
 280:   mov o0.xyzw, r13.xyzw
 281:   mov o1.xyz, r12.xyzx
 282:   mov o2.xyz, r4.xyzx
 283:   mov o3.xy, r11.xyxx
 284:   mov o4.x, r3.z
 285:   emit_stream m0

#line 165
 286:   nop   // m0 <- triStream

#line 166
 287:   nop 
 288:   mov r8.xyz, r8.xyzx
 289:   mov r9.xyz, r9.xyzx
 290:   nop 
 291:   mov r3.z, vPrim

#line 120
 292:   mov r3.z, r3.z

#line 122
 293:   mov r8.xyz, r8.xyzx  // r8.x <- o.PosW.x; r8.y <- o.PosW.y; r8.z <- o.PosW.z

#line 123
 294:   dp3 r3.w, r8.xyzx, r8.xyzx
 295:   rsq r3.w, r3.w
 296:   mul r4.xyz, r3.wwww, r8.xyzx

#line 124
 297:   mov r11.xy, l(0,1.000000,0,0)

#line 125
 298:   mov r8.w, l(1.000000)
 299:   dp4 r12.x, r8.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
 300:   dp4 r12.y, r8.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
 301:   dp4 r12.z, r8.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
 302:   dp4 r12.w, r8.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 126
 303:   mov o0.xyzw, r12.xyzw
 304:   mov o1.xyz, r8.xyzx
 305:   mov o2.xyz, r4.xyzx
 306:   mov o3.xy, r11.xyxx
 307:   mov o4.x, r3.z
 308:   emit_stream m0

#line 127
 309:   mov r9.xyz, r9.xyzx  // r9.x <- o.PosW.x; r9.y <- o.PosW.y; r9.z <- o.PosW.z

#line 128
 310:   dp3 r3.w, r9.xyzx, r9.xyzx
 311:   rsq r3.w, r3.w
 312:   mul r4.xyz, r3.wwww, r9.xyzx

#line 129
 313:   mov r8.xy, l(1.000000,1.000000,0,0)  // r8.x <- o.TexC.x; r8.y <- o.TexC.y

#line 130
 314:   mov r9.w, l(1.000000)
 315:   dp4 r11.x, r9.xyzw, cb1[16].xyzw  // r11.x <- o.PosH.x
 316:   dp4 r11.y, r9.xyzw, cb1[17].xyzw  // r11.y <- o.PosH.y
 317:   dp4 r11.z, r9.xyzw, cb1[18].xyzw  // r11.z <- o.PosH.z
 318:   dp4 r11.w, r9.xyzw, cb1[19].xyzw  // r11.w <- o.PosH.w

#line 131
 319:   mov o0.xyzw, r11.xyzw
 320:   mov o1.xyz, r9.xyzx
 321:   mov o2.xyz, r4.xyzx
 322:   mov o3.xy, r8.xyxx
 323:   mov o4.x, r3.z
 324:   emit_stream m0

#line 132
 325:   mov r10.xyz, r10.xyzx  // r10.x <- o.PosW.x; r10.y <- o.PosW.y; r10.z <- o.PosW.z

#line 133
 326:   dp3 r3.w, r10.xyzx, r10.xyzx
 327:   rsq r3.w, r3.w
 328:   mul r4.xyz, r3.wwww, r10.xyzx

#line 134
 329:   mov r8.xy, l(0.500000,0,0,0)

#line 135
 330:   mov r10.w, l(1.000000)
 331:   dp4 r9.x, r10.xyzw, cb1[16].xyzw  // r9.x <- o.PosH.x
 332:   dp4 r9.y, r10.xyzw, cb1[17].xyzw  // r9.y <- o.PosH.y
 333:   dp4 r9.z, r10.xyzw, cb1[18].xyzw  // r9.z <- o.PosH.z
 334:   dp4 r9.w, r10.xyzw, cb1[19].xyzw  // r9.w <- o.PosH.w

#line 136
 335:   mov o0.xyzw, r9.xyzw
 336:   mov o1.xyz, r10.xyzx
 337:   mov o2.xyz, r4.xyzx
 338:   mov o3.xy, r8.xyxx
 339:   mov o4.x, r3.z
 340:   emit_stream m0

#line 166
 341:   nop   // m0 <- triStream

#line 169
 342:   mov r4.xyz, r5.xyzx  // r4.x <- a0.x; r4.y <- a0.y; r4.z <- a0.z
 343:   mov r1.xyz, r1.xyzx  // r1.x <- b0.x; r1.y <- b0.y; r1.z <- b0.z
 344:   mov r6.xyz, r6.xyzx  // r6.x <- c0.x; r6.y <- c0.y; r6.z <- c0.z

#line 170
 345:   nop 
 346:   add r8.xyz, r1.xyzx, r4.xyzx
 347:   mul r8.xyz, r8.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 348:   mov r3.x, r3.x

#line 111
 349:   dp3 r3.z, r8.xyzx, r8.xyzx
 350:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 351:   lt r3.w, r3.z, l(0.000001)
 352:   if_nz r3.w

#line 113
 353:     itof r9.yz, l(0, 0, 0, 0)  // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z
 354:     mov r9.x, r3.x  // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z
 355:   endif   // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z; r9.x <- <ProjectKeepRadius return value>.x

#line 114
 356:   if_z r3.w
 357:     div r8.xyz, r8.xyzx, r3.zzzz
 358:     mul r9.xyz, r3.xxxx, r8.xyzx
 359:   endif 

#line 170
 360:   mov r9.xyz, r9.xyzx  // r9.x <- a0b0.x; r9.y <- a0b0.y; r9.z <- a0b0.z

#line 171
 361:   nop 
 362:   add r8.xyz, r1.xyzx, r6.xyzx
 363:   mul r8.xyz, r8.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 364:   mov r3.x, r3.x

#line 111
 365:   dp3 r3.z, r8.xyzx, r8.xyzx
 366:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 367:   lt r3.w, r3.z, l(0.000001)
 368:   if_nz r3.w

#line 113
 369:     itof r10.yz, l(0, 0, 0, 0)  // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z
 370:     mov r10.x, r3.x  // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z
 371:   endif   // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z; r10.x <- <ProjectKeepRadius return value>.x

#line 114
 372:   if_z r3.w
 373:     div r8.xyz, r8.xyzx, r3.zzzz
 374:     mul r10.xyz, r3.xxxx, r8.xyzx
 375:   endif 

#line 171
 376:   mov r10.xyz, r10.xyzx  // r10.x <- b0c0.x; r10.y <- b0c0.y; r10.z <- b0c0.z

#line 172
 377:   nop 
 378:   add r8.xyz, r4.xyzx, r6.xyzx
 379:   mul r8.xyz, r8.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 380:   mov r3.x, r3.x

#line 111
 381:   dp3 r3.z, r8.xyzx, r8.xyzx
 382:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 383:   lt r3.w, r3.z, l(0.000001)
 384:   if_nz r3.w

#line 113
 385:     itof r11.yz, l(0, 0, 0, 0)  // r11.y <- <ProjectKeepRadius return value>.y; r11.z <- <ProjectKeepRadius return value>.z
 386:     mov r11.x, r3.x  // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z
 387:   endif   // r11.y <- <ProjectKeepRadius return value>.y; r11.z <- <ProjectKeepRadius return value>.z; r11.x <- <ProjectKeepRadius return value>.x

#line 114
 388:   if_z r3.w
 389:     div r8.xyz, r8.xyzx, r3.zzzz
 390:     mul r11.xyz, r3.xxxx, r8.xyzx
 391:   endif 

#line 172
 392:   mov r11.xyz, r11.xyzx  // r11.x <- c0a0.x; r11.y <- c0a0.y; r11.z <- c0a0.z

#line 173
 393:   nop 
 394:   mov r4.xyz, r4.xyzx
 395:   mov r9.xyz, r9.xyzx
 396:   mov r11.xyz, r11.xyzx
 397:   nop 
 398:   mov r3.z, vPrim

#line 120
 399:   mov r3.z, r3.z  // r3.z <- o.PrimID

#line 122
 400:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
 401:   dp3 r3.w, r4.xyzx, r4.xyzx
 402:   rsq r3.w, r3.w
 403:   mul r8.xyz, r3.wwww, r4.xyzx  // r8.x <- o.NormalW.x; r8.y <- o.NormalW.y; r8.z <- o.NormalW.z

#line 124
 404:   mov r12.xy, l(0,1.000000,0,0)  // r12.x <- o.TexC.x; r12.y <- o.TexC.y

#line 125
 405:   mov r4.w, l(1.000000)
 406:   dp4 r13.x, r4.xyzw, cb1[16].xyzw  // r13.x <- o.PosH.x
 407:   dp4 r13.y, r4.xyzw, cb1[17].xyzw  // r13.y <- o.PosH.y
 408:   dp4 r13.z, r4.xyzw, cb1[18].xyzw  // r13.z <- o.PosH.z
 409:   dp4 r13.w, r4.xyzw, cb1[19].xyzw  // r13.w <- o.PosH.w

#line 126
 410:   mov o0.xyzw, r13.xyzw
 411:   mov o1.xyz, r4.xyzx
 412:   mov o2.xyz, r8.xyzx
 413:   mov o3.xy, r12.xyxx
 414:   mov o4.x, r3.z
 415:   emit_stream m0

#line 127
 416:   mov r9.xyz, r9.xyzx  // r9.x <- o.PosW.x; r9.y <- o.PosW.y; r9.z <- o.PosW.z

#line 128
 417:   dp3 r3.w, r9.xyzx, r9.xyzx
 418:   rsq r3.w, r3.w
 419:   mul r4.xyz, r3.wwww, r9.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
 420:   mov r8.xy, l(1.000000,1.000000,0,0)  // r8.x <- o.TexC.x; r8.y <- o.TexC.y

#line 130
 421:   mov r9.w, l(1.000000)
 422:   dp4 r12.x, r9.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
 423:   dp4 r12.y, r9.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
 424:   dp4 r12.z, r9.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
 425:   dp4 r12.w, r9.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 131
 426:   mov o0.xyzw, r12.xyzw
 427:   mov o1.xyz, r9.xyzx
 428:   mov o2.xyz, r4.xyzx
 429:   mov o3.xy, r8.xyxx
 430:   mov o4.x, r3.z
 431:   emit_stream m0

#line 132
 432:   mov r11.xyz, r11.xyzx  // r11.x <- o.PosW.x; r11.y <- o.PosW.y; r11.z <- o.PosW.z

#line 133
 433:   dp3 r3.w, r11.xyzx, r11.xyzx
 434:   rsq r3.w, r3.w
 435:   mul r4.xyz, r3.wwww, r11.xyzx

#line 134
 436:   mov r8.xy, l(0.500000,0,0,0)

#line 135
 437:   mov r11.w, l(1.000000)
 438:   dp4 r12.x, r11.xyzw, cb1[16].xyzw
 439:   dp4 r12.y, r11.xyzw, cb1[17].xyzw
 440:   dp4 r12.z, r11.xyzw, cb1[18].xyzw
 441:   dp4 r12.w, r11.xyzw, cb1[19].xyzw

#line 136
 442:   mov o0.xyzw, r12.xyzw
 443:   mov o1.xyz, r11.xyzx
 444:   mov o2.xyz, r4.xyzx
 445:   mov o3.xy, r8.xyxx
 446:   mov o4.x, r3.z
 447:   emit_stream m0

#line 173
 448:   nop   // m0 <- triStream

#line 174
 449:   nop 
 450:   mov r4.xyz, r9.xyzx
 451:   mov r1.xyz, r1.xyzx
 452:   mov r10.xyz, r10.xyzx
 453:   nop 
 454:   mov r3.z, vPrim

#line 120
 455:   mov r3.z, r3.z

#line 122
 456:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
 457:   dp3 r3.w, r4.xyzx, r4.xyzx
 458:   rsq r3.w, r3.w
 459:   mul r8.xyz, r3.wwww, r4.xyzx  // r8.x <- o.NormalW.x; r8.y <- o.NormalW.y; r8.z <- o.NormalW.z

#line 124
 460:   mov r12.xy, l(0,1.000000,0,0)  // r12.x <- o.TexC.x; r12.y <- o.TexC.y

#line 125
 461:   mov r4.w, l(1.000000)
 462:   dp4 r13.x, r4.xyzw, cb1[16].xyzw  // r13.x <- o.PosH.x
 463:   dp4 r13.y, r4.xyzw, cb1[17].xyzw  // r13.y <- o.PosH.y
 464:   dp4 r13.z, r4.xyzw, cb1[18].xyzw  // r13.z <- o.PosH.z
 465:   dp4 r13.w, r4.xyzw, cb1[19].xyzw  // r13.w <- o.PosH.w

#line 126
 466:   mov o0.xyzw, r13.xyzw
 467:   mov o1.xyz, r4.xyzx
 468:   mov o2.xyz, r8.xyzx
 469:   mov o3.xy, r12.xyxx
 470:   mov o4.x, r3.z
 471:   emit_stream m0

#line 127
 472:   mov r1.xyz, r1.xyzx  // r1.x <- o.PosW.x; r1.y <- o.PosW.y; r1.z <- o.PosW.z

#line 128
 473:   dp3 r3.w, r1.xyzx, r1.xyzx
 474:   rsq r3.w, r3.w
 475:   mul r4.xyz, r1.xyzx, r3.wwww  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
 476:   mov r8.xy, l(1.000000,1.000000,0,0)  // r8.x <- o.TexC.x; r8.y <- o.TexC.y

#line 130
 477:   mov r1.w, l(1.000000)
 478:   dp4 r12.x, r1.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
 479:   dp4 r12.y, r1.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
 480:   dp4 r12.z, r1.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
 481:   dp4 r12.w, r1.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 131
 482:   mov o0.xyzw, r12.xyzw
 483:   mov o1.xyz, r1.xyzx
 484:   mov o2.xyz, r4.xyzx
 485:   mov o3.xy, r8.xyxx
 486:   mov o4.x, r3.z
 487:   emit_stream m0

#line 132
 488:   mov r10.xyz, r10.xyzx  // r10.x <- o.PosW.x; r10.y <- o.PosW.y; r10.z <- o.PosW.z

#line 133
 489:   dp3 r3.w, r10.xyzx, r10.xyzx
 490:   rsq r3.w, r3.w
 491:   mul r4.xyz, r3.wwww, r10.xyzx

#line 134
 492:   mov r8.xy, l(0.500000,0,0,0)

#line 135
 493:   mov r10.w, l(1.000000)
 494:   dp4 r12.x, r10.xyzw, cb1[16].xyzw
 495:   dp4 r12.y, r10.xyzw, cb1[17].xyzw
 496:   dp4 r12.z, r10.xyzw, cb1[18].xyzw
 497:   dp4 r12.w, r10.xyzw, cb1[19].xyzw

#line 136
 498:   mov o0.xyzw, r12.xyzw
 499:   mov o1.xyz, r10.xyzx
 500:   mov o2.xyz, r4.xyzx
 501:   mov o3.xy, r8.xyxx
 502:   mov o4.x, r3.z
 503:   emit_stream m0

#line 174
 504:   nop   // m0 <- triStream

#line 175
 505:   nop 
 506:   mov r4.xyz, r11.xyzx
 507:   mov r8.xyz, r10.xyzx
 508:   mov r12.xyz, r6.xyzx
 509:   nop 
 510:   mov r3.z, vPrim

#line 120
 511:   mov r3.z, r3.z

#line 122
 512:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
 513:   dp3 r3.w, r4.xyzx, r4.xyzx
 514:   rsq r3.w, r3.w
 515:   mul r13.xyz, r3.wwww, r4.xyzx  // r13.x <- o.NormalW.x; r13.y <- o.NormalW.y; r13.z <- o.NormalW.z

#line 124
 516:   mov r14.xy, l(0,1.000000,0,0)  // r14.x <- o.TexC.x; r14.y <- o.TexC.y

#line 125
 517:   mov r4.w, l(1.000000)
 518:   dp4 r15.x, r4.xyzw, cb1[16].xyzw  // r15.x <- o.PosH.x
 519:   dp4 r15.y, r4.xyzw, cb1[17].xyzw  // r15.y <- o.PosH.y
 520:   dp4 r15.z, r4.xyzw, cb1[18].xyzw  // r15.z <- o.PosH.z
 521:   dp4 r15.w, r4.xyzw, cb1[19].xyzw  // r15.w <- o.PosH.w

#line 126
 522:   mov o0.xyzw, r15.xyzw
 523:   mov o1.xyz, r4.xyzx
 524:   mov o2.xyz, r13.xyzx
 525:   mov o3.xy, r14.xyxx
 526:   mov o4.x, r3.z
 527:   emit_stream m0

#line 127
 528:   mov r8.xyz, r8.xyzx  // r8.x <- o.PosW.x; r8.y <- o.PosW.y; r8.z <- o.PosW.z

#line 128
 529:   dp3 r3.w, r8.xyzx, r8.xyzx
 530:   rsq r3.w, r3.w
 531:   mul r4.xyz, r3.wwww, r8.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
 532:   mov r13.xy, l(1.000000,1.000000,0,0)  // r13.x <- o.TexC.x; r13.y <- o.TexC.y

#line 130
 533:   mov r8.w, l(1.000000)
 534:   dp4 r14.x, r8.xyzw, cb1[16].xyzw  // r14.x <- o.PosH.x
 535:   dp4 r14.y, r8.xyzw, cb1[17].xyzw  // r14.y <- o.PosH.y
 536:   dp4 r14.z, r8.xyzw, cb1[18].xyzw  // r14.z <- o.PosH.z
 537:   dp4 r14.w, r8.xyzw, cb1[19].xyzw  // r14.w <- o.PosH.w

#line 131
 538:   mov o0.xyzw, r14.xyzw
 539:   mov o1.xyz, r8.xyzx
 540:   mov o2.xyz, r4.xyzx
 541:   mov o3.xy, r13.xyxx
 542:   mov o4.x, r3.z
 543:   emit_stream m0

#line 132
 544:   mov r12.xyz, r12.xyzx  // r12.x <- o.PosW.x; r12.y <- o.PosW.y; r12.z <- o.PosW.z

#line 133
 545:   dp3 r3.w, r12.xyzx, r12.xyzx
 546:   rsq r3.w, r3.w
 547:   mul r4.xyz, r3.wwww, r12.xyzx

#line 134
 548:   mov r8.xy, l(0.500000,0,0,0)  // r8.x <- o.TexC.x; r8.y <- o.TexC.y

#line 135
 549:   mov r12.w, l(1.000000)
 550:   dp4 r13.x, r12.xyzw, cb1[16].xyzw  // r13.x <- o.PosH.x
 551:   dp4 r13.y, r12.xyzw, cb1[17].xyzw  // r13.y <- o.PosH.y
 552:   dp4 r13.z, r12.xyzw, cb1[18].xyzw  // r13.z <- o.PosH.z
 553:   dp4 r13.w, r12.xyzw, cb1[19].xyzw  // r13.w <- o.PosH.w

#line 136
 554:   mov o0.xyzw, r13.xyzw
 555:   mov o1.xyz, r12.xyzx
 556:   mov o2.xyz, r4.xyzx
 557:   mov o3.xy, r8.xyxx
 558:   mov o4.x, r3.z
 559:   emit_stream m0

#line 175
 560:   nop   // m0 <- triStream

#line 176
 561:   nop 
 562:   mov r9.xyz, r9.xyzx
 563:   mov r10.xyz, r10.xyzx
 564:   nop 
 565:   mov r3.z, vPrim

#line 120
 566:   mov r3.z, r3.z

#line 122
 567:   mov r9.xyz, r9.xyzx  // r9.x <- o.PosW.x; r9.y <- o.PosW.y; r9.z <- o.PosW.z

#line 123
 568:   dp3 r3.w, r9.xyzx, r9.xyzx
 569:   rsq r3.w, r3.w
 570:   mul r4.xyz, r3.wwww, r9.xyzx

#line 124
 571:   mov r8.xy, l(0,1.000000,0,0)

#line 125
 572:   mov r9.w, l(1.000000)
 573:   dp4 r12.x, r9.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
 574:   dp4 r12.y, r9.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
 575:   dp4 r12.z, r9.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
 576:   dp4 r12.w, r9.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 126
 577:   mov o0.xyzw, r12.xyzw
 578:   mov o1.xyz, r9.xyzx
 579:   mov o2.xyz, r4.xyzx
 580:   mov o3.xy, r8.xyxx
 581:   mov o4.x, r3.z
 582:   emit_stream m0

#line 127
 583:   mov r10.xyz, r10.xyzx  // r10.x <- o.PosW.x; r10.y <- o.PosW.y; r10.z <- o.PosW.z

#line 128
 584:   dp3 r3.w, r10.xyzx, r10.xyzx
 585:   rsq r3.w, r3.w
 586:   mul r4.xyz, r3.wwww, r10.xyzx

#line 129
 587:   mov r8.xy, l(1.000000,1.000000,0,0)

#line 130
 588:   mov r10.w, l(1.000000)
 589:   dp4 r9.x, r10.xyzw, cb1[16].xyzw  // r9.x <- o.PosH.x
 590:   dp4 r9.y, r10.xyzw, cb1[17].xyzw  // r9.y <- o.PosH.y
 591:   dp4 r9.z, r10.xyzw, cb1[18].xyzw  // r9.z <- o.PosH.z
 592:   dp4 r9.w, r10.xyzw, cb1[19].xyzw  // r9.w <- o.PosH.w

#line 131
 593:   mov o0.xyzw, r9.xyzw
 594:   mov o1.xyz, r10.xyzx
 595:   mov o2.xyz, r4.xyzx
 596:   mov o3.xy, r8.xyxx
 597:   mov o4.x, r3.z
 598:   emit_stream m0

#line 132
 599:   mov r11.xyz, r11.xyzx  // r11.x <- o.PosW.x; r11.y <- o.PosW.y; r11.z <- o.PosW.z

#line 133
 600:   dp3 r3.w, r11.xyzx, r11.xyzx
 601:   rsq r3.w, r3.w
 602:   mul r4.xyz, r3.wwww, r11.xyzx

#line 134
 603:   mov r8.xy, l(0.500000,0,0,0)

#line 135
 604:   mov r11.w, l(1.000000)
 605:   dp4 r9.x, r11.xyzw, cb1[16].xyzw
 606:   dp4 r9.y, r11.xyzw, cb1[17].xyzw
 607:   dp4 r9.z, r11.xyzw, cb1[18].xyzw
 608:   dp4 r9.w, r11.xyzw, cb1[19].xyzw

#line 136
 609:   mov o0.xyzw, r9.xyzw
 610:   mov o1.xyz, r11.xyzx
 611:   mov o2.xyz, r4.xyzx
 612:   mov o3.xy, r8.xyxx
 613:   mov o4.x, r3.z
 614:   emit_stream m0

#line 176
 615:   nop   // m0 <- triStream

#line 179
 616:   mov r4.xyz, r7.xyzx  // r4.x <- a0.x; r4.y <- a0.y; r4.z <- a0.z
 617:   mov r8.xyz, r6.xyzx  // r8.x <- b0.x; r8.y <- b0.y; r8.z <- b0.z
 618:   mov r2.xyz, r2.xyzx  // r2.x <- c0.x; r2.y <- c0.y; r2.z <- c0.z

#line 180
 619:   nop 
 620:   add r9.xyz, r4.xyzx, r8.xyzx
 621:   mul r9.xyz, r9.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 622:   mov r3.x, r3.x

#line 111
 623:   dp3 r3.z, r9.xyzx, r9.xyzx
 624:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 625:   lt r3.w, r3.z, l(0.000001)
 626:   if_nz r3.w

#line 113
 627:     itof r10.yz, l(0, 0, 0, 0)  // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z
 628:     mov r10.x, r3.x  // r11.y <- <ProjectKeepRadius return value>.y; r11.z <- <ProjectKeepRadius return value>.z
 629:   endif   // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z; r10.x <- <ProjectKeepRadius return value>.x

#line 114
 630:   if_z r3.w
 631:     div r9.xyz, r9.xyzx, r3.zzzz
 632:     mul r10.xyz, r3.xxxx, r9.xyzx
 633:   endif 

#line 180
 634:   mov r10.xyz, r10.xyzx  // r10.x <- a0b0.x; r10.y <- a0b0.y; r10.z <- a0b0.z

#line 181
 635:   nop 
 636:   add r9.xyz, r2.xyzx, r8.xyzx
 637:   mul r9.xyz, r9.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 638:   mov r3.x, r3.x

#line 111
 639:   dp3 r3.z, r9.xyzx, r9.xyzx
 640:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 641:   lt r3.w, r3.z, l(0.000001)
 642:   if_nz r3.w

#line 113
 643:     itof r11.yz, l(0, 0, 0, 0)  // r11.y <- <ProjectKeepRadius return value>.y; r11.z <- <ProjectKeepRadius return value>.z
 644:     mov r11.x, r3.x  // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z
 645:   endif   // r11.y <- <ProjectKeepRadius return value>.y; r11.z <- <ProjectKeepRadius return value>.z; r11.x <- <ProjectKeepRadius return value>.x

#line 114
 646:   if_z r3.w
 647:     div r9.xyz, r9.xyzx, r3.zzzz
 648:     mul r11.xyz, r3.xxxx, r9.xyzx
 649:   endif 

#line 181
 650:   mov r11.xyz, r11.xyzx  // r11.x <- b0c0.x; r11.y <- b0c0.y; r11.z <- b0c0.z

#line 182
 651:   nop 
 652:   add r9.xyz, r4.xyzx, r2.xyzx
 653:   mul r9.xyz, r9.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 654:   mov r3.x, r3.x

#line 111
 655:   dp3 r3.z, r9.xyzx, r9.xyzx
 656:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 657:   lt r3.w, r3.z, l(0.000001)
 658:   if_nz r3.w

#line 113
 659:     itof r12.yz, l(0, 0, 0, 0)  // r12.y <- <ProjectKeepRadius return value>.y; r12.z <- <ProjectKeepRadius return value>.z
 660:     mov r12.x, r3.x  // r11.y <- <ProjectKeepRadius return value>.y; r11.z <- <ProjectKeepRadius return value>.z
 661:   endif   // r12.y <- <ProjectKeepRadius return value>.y; r12.z <- <ProjectKeepRadius return value>.z; r12.x <- <ProjectKeepRadius return value>.x

#line 114
 662:   if_z r3.w
 663:     div r9.xyz, r9.xyzx, r3.zzzz
 664:     mul r12.xyz, r3.xxxx, r9.xyzx
 665:   endif 

#line 182
 666:   mov r12.xyz, r12.xyzx  // r12.x <- c0a0.x; r12.y <- c0a0.y; r12.z <- c0a0.z

#line 183
 667:   nop 
 668:   mov r4.xyz, r4.xyzx
 669:   mov r10.xyz, r10.xyzx
 670:   mov r12.xyz, r12.xyzx
 671:   nop 
 672:   mov r3.z, vPrim

#line 120
 673:   mov r3.z, r3.z  // r3.z <- o.PrimID

#line 122
 674:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
 675:   dp3 r3.w, r4.xyzx, r4.xyzx
 676:   rsq r3.w, r3.w
 677:   mul r9.xyz, r3.wwww, r4.xyzx  // r9.x <- o.NormalW.x; r9.y <- o.NormalW.y; r9.z <- o.NormalW.z

#line 124
 678:   mov r13.xy, l(0,1.000000,0,0)  // r13.x <- o.TexC.x; r13.y <- o.TexC.y

#line 125
 679:   mov r4.w, l(1.000000)
 680:   dp4 r14.x, r4.xyzw, cb1[16].xyzw  // r14.x <- o.PosH.x
 681:   dp4 r14.y, r4.xyzw, cb1[17].xyzw  // r14.y <- o.PosH.y
 682:   dp4 r14.z, r4.xyzw, cb1[18].xyzw  // r14.z <- o.PosH.z
 683:   dp4 r14.w, r4.xyzw, cb1[19].xyzw  // r14.w <- o.PosH.w

#line 126
 684:   mov o0.xyzw, r14.xyzw
 685:   mov o1.xyz, r4.xyzx
 686:   mov o2.xyz, r9.xyzx
 687:   mov o3.xy, r13.xyxx
 688:   mov o4.x, r3.z
 689:   emit_stream m0

#line 127
 690:   mov r10.xyz, r10.xyzx  // r10.x <- o.PosW.x; r10.y <- o.PosW.y; r10.z <- o.PosW.z

#line 128
 691:   dp3 r3.w, r10.xyzx, r10.xyzx
 692:   rsq r3.w, r3.w
 693:   mul r4.xyz, r3.wwww, r10.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
 694:   mov r9.xy, l(1.000000,1.000000,0,0)  // r9.x <- o.TexC.x; r9.y <- o.TexC.y

#line 130
 695:   mov r10.w, l(1.000000)
 696:   dp4 r13.x, r10.xyzw, cb1[16].xyzw  // r13.x <- o.PosH.x
 697:   dp4 r13.y, r10.xyzw, cb1[17].xyzw  // r13.y <- o.PosH.y
 698:   dp4 r13.z, r10.xyzw, cb1[18].xyzw  // r13.z <- o.PosH.z
 699:   dp4 r13.w, r10.xyzw, cb1[19].xyzw  // r13.w <- o.PosH.w

#line 131
 700:   mov o0.xyzw, r13.xyzw
 701:   mov o1.xyz, r10.xyzx
 702:   mov o2.xyz, r4.xyzx
 703:   mov o3.xy, r9.xyxx
 704:   mov o4.x, r3.z
 705:   emit_stream m0

#line 132
 706:   mov r12.xyz, r12.xyzx  // r12.x <- o.PosW.x; r12.y <- o.PosW.y; r12.z <- o.PosW.z

#line 133
 707:   dp3 r3.w, r12.xyzx, r12.xyzx
 708:   rsq r3.w, r3.w
 709:   mul r4.xyz, r3.wwww, r12.xyzx

#line 134
 710:   mov r9.xy, l(0.500000,0,0,0)

#line 135
 711:   mov r12.w, l(1.000000)
 712:   dp4 r13.x, r12.xyzw, cb1[16].xyzw
 713:   dp4 r13.y, r12.xyzw, cb1[17].xyzw
 714:   dp4 r13.z, r12.xyzw, cb1[18].xyzw
 715:   dp4 r13.w, r12.xyzw, cb1[19].xyzw

#line 136
 716:   mov o0.xyzw, r13.xyzw
 717:   mov o1.xyz, r12.xyzx
 718:   mov o2.xyz, r4.xyzx
 719:   mov o3.xy, r9.xyxx
 720:   mov o4.x, r3.z
 721:   emit_stream m0

#line 183
 722:   nop   // m0 <- triStream

#line 184
 723:   nop 
 724:   mov r4.xyz, r10.xyzx
 725:   mov r8.xyz, r8.xyzx
 726:   mov r11.xyz, r11.xyzx
 727:   nop 
 728:   mov r3.z, vPrim

#line 120
 729:   mov r3.z, r3.z

#line 122
 730:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
 731:   dp3 r3.w, r4.xyzx, r4.xyzx
 732:   rsq r3.w, r3.w
 733:   mul r9.xyz, r3.wwww, r4.xyzx  // r9.x <- o.NormalW.x; r9.y <- o.NormalW.y; r9.z <- o.NormalW.z

#line 124
 734:   mov r13.xy, l(0,1.000000,0,0)  // r13.x <- o.TexC.x; r13.y <- o.TexC.y

#line 125
 735:   mov r4.w, l(1.000000)
 736:   dp4 r14.x, r4.xyzw, cb1[16].xyzw  // r14.x <- o.PosH.x
 737:   dp4 r14.y, r4.xyzw, cb1[17].xyzw  // r14.y <- o.PosH.y
 738:   dp4 r14.z, r4.xyzw, cb1[18].xyzw  // r14.z <- o.PosH.z
 739:   dp4 r14.w, r4.xyzw, cb1[19].xyzw  // r14.w <- o.PosH.w

#line 126
 740:   mov o0.xyzw, r14.xyzw
 741:   mov o1.xyz, r4.xyzx
 742:   mov o2.xyz, r9.xyzx
 743:   mov o3.xy, r13.xyxx
 744:   mov o4.x, r3.z
 745:   emit_stream m0

#line 127
 746:   mov r8.xyz, r8.xyzx  // r8.x <- o.PosW.x; r8.y <- o.PosW.y; r8.z <- o.PosW.z

#line 128
 747:   dp3 r3.w, r8.xyzx, r8.xyzx
 748:   rsq r3.w, r3.w
 749:   mul r4.xyz, r3.wwww, r8.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
 750:   mov r9.xy, l(1.000000,1.000000,0,0)  // r9.x <- o.TexC.x; r9.y <- o.TexC.y

#line 130
 751:   mov r8.w, l(1.000000)
 752:   dp4 r13.x, r8.xyzw, cb1[16].xyzw  // r13.x <- o.PosH.x
 753:   dp4 r13.y, r8.xyzw, cb1[17].xyzw  // r13.y <- o.PosH.y
 754:   dp4 r13.z, r8.xyzw, cb1[18].xyzw  // r13.z <- o.PosH.z
 755:   dp4 r13.w, r8.xyzw, cb1[19].xyzw  // r13.w <- o.PosH.w

#line 131
 756:   mov o0.xyzw, r13.xyzw
 757:   mov o1.xyz, r8.xyzx
 758:   mov o2.xyz, r4.xyzx
 759:   mov o3.xy, r9.xyxx
 760:   mov o4.x, r3.z
 761:   emit_stream m0

#line 132
 762:   mov r11.xyz, r11.xyzx  // r11.x <- o.PosW.x; r11.y <- o.PosW.y; r11.z <- o.PosW.z

#line 133
 763:   dp3 r3.w, r11.xyzx, r11.xyzx
 764:   rsq r3.w, r3.w
 765:   mul r4.xyz, r3.wwww, r11.xyzx

#line 134
 766:   mov r8.xy, l(0.500000,0,0,0)  // r8.x <- o.TexC.x; r8.y <- o.TexC.y

#line 135
 767:   mov r11.w, l(1.000000)
 768:   dp4 r9.x, r11.xyzw, cb1[16].xyzw  // r9.x <- o.PosH.x
 769:   dp4 r9.y, r11.xyzw, cb1[17].xyzw  // r9.y <- o.PosH.y
 770:   dp4 r9.z, r11.xyzw, cb1[18].xyzw  // r9.z <- o.PosH.z
 771:   dp4 r9.w, r11.xyzw, cb1[19].xyzw  // r9.w <- o.PosH.w

#line 136
 772:   mov o0.xyzw, r9.xyzw
 773:   mov o1.xyz, r11.xyzx
 774:   mov o2.xyz, r4.xyzx
 775:   mov o3.xy, r8.xyxx
 776:   mov o4.x, r3.z
 777:   emit_stream m0

#line 184
 778:   nop   // m0 <- triStream

#line 185
 779:   nop 
 780:   mov r4.xyz, r12.xyzx
 781:   mov r8.xyz, r11.xyzx
 782:   mov r2.xyz, r2.xyzx
 783:   nop 
 784:   mov r3.z, vPrim

#line 120
 785:   mov r3.z, r3.z

#line 122
 786:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
 787:   dp3 r3.w, r4.xyzx, r4.xyzx
 788:   rsq r3.w, r3.w
 789:   mul r9.xyz, r3.wwww, r4.xyzx  // r9.x <- o.NormalW.x; r9.y <- o.NormalW.y; r9.z <- o.NormalW.z

#line 124
 790:   mov r13.xy, l(0,1.000000,0,0)  // r13.x <- o.TexC.x; r13.y <- o.TexC.y

#line 125
 791:   mov r4.w, l(1.000000)
 792:   dp4 r14.x, r4.xyzw, cb1[16].xyzw  // r14.x <- o.PosH.x
 793:   dp4 r14.y, r4.xyzw, cb1[17].xyzw  // r14.y <- o.PosH.y
 794:   dp4 r14.z, r4.xyzw, cb1[18].xyzw  // r14.z <- o.PosH.z
 795:   dp4 r14.w, r4.xyzw, cb1[19].xyzw  // r14.w <- o.PosH.w

#line 126
 796:   mov o0.xyzw, r14.xyzw
 797:   mov o1.xyz, r4.xyzx
 798:   mov o2.xyz, r9.xyzx
 799:   mov o3.xy, r13.xyxx
 800:   mov o4.x, r3.z
 801:   emit_stream m0

#line 127
 802:   mov r8.xyz, r8.xyzx  // r8.x <- o.PosW.x; r8.y <- o.PosW.y; r8.z <- o.PosW.z

#line 128
 803:   dp3 r3.w, r8.xyzx, r8.xyzx
 804:   rsq r3.w, r3.w
 805:   mul r4.xyz, r3.wwww, r8.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
 806:   mov r9.xy, l(1.000000,1.000000,0,0)  // r9.x <- o.TexC.x; r9.y <- o.TexC.y

#line 130
 807:   mov r8.w, l(1.000000)
 808:   dp4 r13.x, r8.xyzw, cb1[16].xyzw  // r13.x <- o.PosH.x
 809:   dp4 r13.y, r8.xyzw, cb1[17].xyzw  // r13.y <- o.PosH.y
 810:   dp4 r13.z, r8.xyzw, cb1[18].xyzw  // r13.z <- o.PosH.z
 811:   dp4 r13.w, r8.xyzw, cb1[19].xyzw  // r13.w <- o.PosH.w

#line 131
 812:   mov o0.xyzw, r13.xyzw
 813:   mov o1.xyz, r8.xyzx
 814:   mov o2.xyz, r4.xyzx
 815:   mov o3.xy, r9.xyxx
 816:   mov o4.x, r3.z
 817:   emit_stream m0

#line 132
 818:   mov r2.xyz, r2.xyzx  // r2.x <- o.PosW.x; r2.y <- o.PosW.y; r2.z <- o.PosW.z

#line 133
 819:   dp3 r3.w, r2.xyzx, r2.xyzx
 820:   rsq r3.w, r3.w
 821:   mul r4.xyz, r2.xyzx, r3.wwww

#line 134
 822:   mov r8.xy, l(0.500000,0,0,0)  // r8.x <- o.TexC.x; r8.y <- o.TexC.y

#line 135
 823:   mov r2.w, l(1.000000)
 824:   dp4 r9.x, r2.xyzw, cb1[16].xyzw  // r9.x <- o.PosH.x
 825:   dp4 r9.y, r2.xyzw, cb1[17].xyzw  // r9.y <- o.PosH.y
 826:   dp4 r9.z, r2.xyzw, cb1[18].xyzw  // r9.z <- o.PosH.z
 827:   dp4 r9.w, r2.xyzw, cb1[19].xyzw  // r9.w <- o.PosH.w

#line 136
 828:   mov o0.xyzw, r9.xyzw
 829:   mov o1.xyz, r2.xyzx
 830:   mov o2.xyz, r4.xyzx
 831:   mov o3.xy, r8.xyxx
 832:   mov o4.x, r3.z
 833:   emit_stream m0

#line 185
 834:   nop   // m0 <- triStream

#line 186
 835:   nop 
 836:   mov r10.xyz, r10.xyzx
 837:   mov r11.xyz, r11.xyzx
 838:   nop 
 839:   mov r3.z, vPrim

#line 120
 840:   mov r3.z, r3.z

#line 122
 841:   mov r10.xyz, r10.xyzx  // r10.x <- o.PosW.x; r10.y <- o.PosW.y; r10.z <- o.PosW.z

#line 123
 842:   dp3 r3.w, r10.xyzx, r10.xyzx
 843:   rsq r3.w, r3.w
 844:   mul r4.xyz, r3.wwww, r10.xyzx

#line 124
 845:   mov r8.xy, l(0,1.000000,0,0)

#line 125
 846:   mov r10.w, l(1.000000)
 847:   dp4 r9.x, r10.xyzw, cb1[16].xyzw
 848:   dp4 r9.y, r10.xyzw, cb1[17].xyzw
 849:   dp4 r9.z, r10.xyzw, cb1[18].xyzw
 850:   dp4 r9.w, r10.xyzw, cb1[19].xyzw

#line 126
 851:   mov o0.xyzw, r9.xyzw
 852:   mov o1.xyz, r10.xyzx
 853:   mov o2.xyz, r4.xyzx
 854:   mov o3.xy, r8.xyxx
 855:   mov o4.x, r3.z
 856:   emit_stream m0

#line 127
 857:   mov r11.xyz, r11.xyzx  // r11.x <- o.PosW.x; r11.y <- o.PosW.y; r11.z <- o.PosW.z

#line 128
 858:   dp3 r3.w, r11.xyzx, r11.xyzx
 859:   rsq r3.w, r3.w
 860:   mul r4.xyz, r3.wwww, r11.xyzx

#line 129
 861:   mov r8.xy, l(1.000000,1.000000,0,0)

#line 130
 862:   mov r11.w, l(1.000000)
 863:   dp4 r9.x, r11.xyzw, cb1[16].xyzw
 864:   dp4 r9.y, r11.xyzw, cb1[17].xyzw
 865:   dp4 r9.z, r11.xyzw, cb1[18].xyzw
 866:   dp4 r9.w, r11.xyzw, cb1[19].xyzw

#line 131
 867:   mov o0.xyzw, r9.xyzw
 868:   mov o1.xyz, r11.xyzx
 869:   mov o2.xyz, r4.xyzx
 870:   mov o3.xy, r8.xyxx
 871:   mov o4.x, r3.z
 872:   emit_stream m0

#line 132
 873:   mov r12.xyz, r12.xyzx  // r12.x <- o.PosW.x; r12.y <- o.PosW.y; r12.z <- o.PosW.z

#line 133
 874:   dp3 r3.w, r12.xyzx, r12.xyzx
 875:   rsq r3.w, r3.w
 876:   mul r4.xyz, r3.wwww, r12.xyzx

#line 134
 877:   mov r8.xy, l(0.500000,0,0,0)

#line 135
 878:   mov r12.w, l(1.000000)
 879:   dp4 r9.x, r12.xyzw, cb1[16].xyzw
 880:   dp4 r9.y, r12.xyzw, cb1[17].xyzw
 881:   dp4 r9.z, r12.xyzw, cb1[18].xyzw
 882:   dp4 r9.w, r12.xyzw, cb1[19].xyzw

#line 136
 883:   mov o0.xyzw, r9.xyzw
 884:   mov o1.xyz, r12.xyzx
 885:   mov o2.xyz, r4.xyzx
 886:   mov o3.xy, r8.xyxx
 887:   mov o4.x, r3.z
 888:   emit_stream m0

#line 186
 889:   nop   // m0 <- triStream

#line 189
 890:   mov r5.xyz, r5.xyzx  // r5.x <- a0.x; r5.y <- a0.y; r5.z <- a0.z
 891:   mov r6.xyz, r6.xyzx  // r6.x <- b0.x; r6.y <- b0.y; r6.z <- b0.z
 892:   mov r7.xyz, r7.xyzx  // r7.x <- c0.x; r7.y <- c0.y; r7.z <- c0.z

#line 190
 893:   nop 
 894:   add r4.xyz, r5.xyzx, r6.xyzx
 895:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 896:   mov r3.x, r3.x

#line 111
 897:   dp3 r3.z, r4.xyzx, r4.xyzx
 898:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 899:   lt r3.w, r3.z, l(0.000001)
 900:   if_nz r3.w

#line 113
 901:     itof r8.yz, l(0, 0, 0, 0)  // r8.y <- <ProjectKeepRadius return value>.y; r8.z <- <ProjectKeepRadius return value>.z
 902:     mov r8.x, r3.x  // r12.y <- <ProjectKeepRadius return value>.y; r12.z <- <ProjectKeepRadius return value>.z
 903:   endif   // r8.y <- <ProjectKeepRadius return value>.y; r8.z <- <ProjectKeepRadius return value>.z; r8.x <- <ProjectKeepRadius return value>.x

#line 114
 904:   if_z r3.w
 905:     div r4.xyz, r4.xyzx, r3.zzzz
 906:     mul r8.xyz, r3.xxxx, r4.xyzx
 907:   endif 

#line 190
 908:   mov r8.xyz, r8.xyzx  // r8.x <- a0b0.x; r8.y <- a0b0.y; r8.z <- a0b0.z

#line 191
 909:   nop 
 910:   add r4.xyz, r6.xyzx, r7.xyzx
 911:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 912:   mov r3.x, r3.x

#line 111
 913:   dp3 r3.z, r4.xyzx, r4.xyzx
 914:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 915:   lt r3.w, r3.z, l(0.000001)
 916:   if_nz r3.w

#line 113
 917:     itof r9.yz, l(0, 0, 0, 0)  // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z
 918:     mov r9.x, r3.x  // r8.y <- <ProjectKeepRadius return value>.y; r8.z <- <ProjectKeepRadius return value>.z
 919:   endif   // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z; r9.x <- <ProjectKeepRadius return value>.x

#line 114
 920:   if_z r3.w
 921:     div r4.xyz, r4.xyzx, r3.zzzz
 922:     mul r9.xyz, r3.xxxx, r4.xyzx
 923:   endif 

#line 191
 924:   mov r9.xyz, r9.xyzx  // r9.x <- b0c0.x; r9.y <- b0c0.y; r9.z <- b0c0.z

#line 192
 925:   nop 
 926:   add r4.xyz, r5.xyzx, r7.xyzx
 927:   mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 928:   mov r3.x, r3.x

#line 111
 929:   dp3 r3.z, r4.xyzx, r4.xyzx
 930:   sqrt r3.z, r3.z  // r3.z <- len

#line 112
 931:   lt r3.w, r3.z, l(0.000001)
 932:   if_nz r3.w

#line 113
 933:     itof r10.yz, l(0, 0, 0, 0)  // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z
 934:     mov r10.x, r3.x  // r9.y <- <ProjectKeepRadius return value>.y; r9.z <- <ProjectKeepRadius return value>.z
 935:   endif   // r10.y <- <ProjectKeepRadius return value>.y; r10.z <- <ProjectKeepRadius return value>.z; r10.x <- <ProjectKeepRadius return value>.x

#line 114
 936:   if_z r3.w
 937:     div r4.xyz, r4.xyzx, r3.zzzz
 938:     mul r10.xyz, r3.xxxx, r4.xyzx
 939:   endif 

#line 192
 940:   mov r10.xyz, r10.xyzx  // r10.x <- c0a0.x; r10.y <- c0a0.y; r10.z <- c0a0.z

#line 193
 941:   nop 
 942:   mov r5.xyz, r5.xyzx
 943:   mov r8.xyz, r8.xyzx
 944:   mov r10.xyz, r10.xyzx
 945:   nop 
 946:   mov r3.z, vPrim

#line 120
 947:   mov r3.z, r3.z  // r3.z <- o.PrimID

#line 122
 948:   mov r5.xyz, r5.xyzx  // r5.x <- o.PosW.x; r5.y <- o.PosW.y; r5.z <- o.PosW.z

#line 123
 949:   dp3 r3.w, r5.xyzx, r5.xyzx
 950:   rsq r3.w, r3.w
 951:   mul r4.xyz, r3.wwww, r5.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 124
 952:   mov r11.xy, l(0,1.000000,0,0)  // r11.x <- o.TexC.x; r11.y <- o.TexC.y

#line 125
 953:   mov r5.w, l(1.000000)
 954:   dp4 r12.x, r5.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
 955:   dp4 r12.y, r5.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
 956:   dp4 r12.z, r5.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
 957:   dp4 r12.w, r5.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 126
 958:   mov o0.xyzw, r12.xyzw
 959:   mov o1.xyz, r5.xyzx
 960:   mov o2.xyz, r4.xyzx
 961:   mov o3.xy, r11.xyxx
 962:   mov o4.x, r3.z
 963:   emit_stream m0

#line 127
 964:   mov r8.xyz, r8.xyzx  // r8.x <- o.PosW.x; r8.y <- o.PosW.y; r8.z <- o.PosW.z

#line 128
 965:   dp3 r3.w, r8.xyzx, r8.xyzx
 966:   rsq r3.w, r3.w
 967:   mul r4.xyz, r3.wwww, r8.xyzx

#line 129
 968:   mov r5.xy, l(1.000000,1.000000,0,0)  // r5.x <- o.TexC.x; r5.y <- o.TexC.y

#line 130
 969:   mov r8.w, l(1.000000)
 970:   dp4 r11.x, r8.xyzw, cb1[16].xyzw  // r11.x <- o.PosH.x
 971:   dp4 r11.y, r8.xyzw, cb1[17].xyzw  // r11.y <- o.PosH.y
 972:   dp4 r11.z, r8.xyzw, cb1[18].xyzw  // r11.z <- o.PosH.z
 973:   dp4 r11.w, r8.xyzw, cb1[19].xyzw  // r11.w <- o.PosH.w

#line 131
 974:   mov o0.xyzw, r11.xyzw
 975:   mov o1.xyz, r8.xyzx
 976:   mov o2.xyz, r4.xyzx
 977:   mov o3.xy, r5.xyxx
 978:   mov o4.x, r3.z
 979:   emit_stream m0

#line 132
 980:   mov r10.xyz, r10.xyzx  // r10.x <- o.PosW.x; r10.y <- o.PosW.y; r10.z <- o.PosW.z

#line 133
 981:   dp3 r3.w, r10.xyzx, r10.xyzx
 982:   rsq r3.w, r3.w
 983:   mul r4.xyz, r3.wwww, r10.xyzx

#line 134
 984:   mov r5.xy, l(0.500000,0,0,0)

#line 135
 985:   mov r10.w, l(1.000000)
 986:   dp4 r11.x, r10.xyzw, cb1[16].xyzw
 987:   dp4 r11.y, r10.xyzw, cb1[17].xyzw
 988:   dp4 r11.z, r10.xyzw, cb1[18].xyzw
 989:   dp4 r11.w, r10.xyzw, cb1[19].xyzw

#line 136
 990:   mov o0.xyzw, r11.xyzw
 991:   mov o1.xyz, r10.xyzx
 992:   mov o2.xyz, r4.xyzx
 993:   mov o3.xy, r5.xyxx
 994:   mov o4.x, r3.z
 995:   emit_stream m0

#line 193
 996:   nop   // m0 <- triStream

#line 194
 997:   nop 
 998:   mov r4.xyz, r8.xyzx
 999:   mov r6.xyz, r6.xyzx
1000:   mov r9.xyz, r9.xyzx
1001:   nop 
1002:   mov r3.z, vPrim

#line 120
1003:   mov r3.z, r3.z

#line 122
1004:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
1005:   dp3 r3.w, r4.xyzx, r4.xyzx
1006:   rsq r3.w, r3.w
1007:   mul r5.xyz, r3.wwww, r4.xyzx  // r5.x <- o.NormalW.x; r5.y <- o.NormalW.y; r5.z <- o.NormalW.z

#line 124
1008:   mov r11.xy, l(0,1.000000,0,0)  // r11.x <- o.TexC.x; r11.y <- o.TexC.y

#line 125
1009:   mov r4.w, l(1.000000)
1010:   dp4 r12.x, r4.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
1011:   dp4 r12.y, r4.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
1012:   dp4 r12.z, r4.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
1013:   dp4 r12.w, r4.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 126
1014:   mov o0.xyzw, r12.xyzw
1015:   mov o1.xyz, r4.xyzx
1016:   mov o2.xyz, r5.xyzx
1017:   mov o3.xy, r11.xyxx
1018:   mov o4.x, r3.z
1019:   emit_stream m0

#line 127
1020:   mov r6.xyz, r6.xyzx  // r6.x <- o.PosW.x; r6.y <- o.PosW.y; r6.z <- o.PosW.z

#line 128
1021:   dp3 r3.w, r6.xyzx, r6.xyzx
1022:   rsq r3.w, r3.w
1023:   mul r4.xyz, r3.wwww, r6.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
1024:   mov r5.xy, l(1.000000,1.000000,0,0)  // r5.x <- o.TexC.x; r5.y <- o.TexC.y

#line 130
1025:   mov r6.w, l(1.000000)
1026:   dp4 r11.x, r6.xyzw, cb1[16].xyzw  // r11.x <- o.PosH.x
1027:   dp4 r11.y, r6.xyzw, cb1[17].xyzw  // r11.y <- o.PosH.y
1028:   dp4 r11.z, r6.xyzw, cb1[18].xyzw  // r11.z <- o.PosH.z
1029:   dp4 r11.w, r6.xyzw, cb1[19].xyzw  // r11.w <- o.PosH.w

#line 131
1030:   mov o0.xyzw, r11.xyzw
1031:   mov o1.xyz, r6.xyzx
1032:   mov o2.xyz, r4.xyzx
1033:   mov o3.xy, r5.xyxx
1034:   mov o4.x, r3.z
1035:   emit_stream m0

#line 132
1036:   mov r9.xyz, r9.xyzx  // r9.x <- o.PosW.x; r9.y <- o.PosW.y; r9.z <- o.PosW.z

#line 133
1037:   dp3 r3.w, r9.xyzx, r9.xyzx
1038:   rsq r3.w, r3.w
1039:   mul r4.xyz, r3.wwww, r9.xyzx

#line 134
1040:   mov r5.xy, l(0.500000,0,0,0)

#line 135
1041:   mov r9.w, l(1.000000)
1042:   dp4 r6.x, r9.xyzw, cb1[16].xyzw  // r6.x <- o.PosH.x
1043:   dp4 r6.y, r9.xyzw, cb1[17].xyzw  // r6.y <- o.PosH.y
1044:   dp4 r6.z, r9.xyzw, cb1[18].xyzw  // r6.z <- o.PosH.z
1045:   dp4 r6.w, r9.xyzw, cb1[19].xyzw  // r6.w <- o.PosH.w

#line 136
1046:   mov o0.xyzw, r6.xyzw
1047:   mov o1.xyz, r9.xyzx
1048:   mov o2.xyz, r4.xyzx
1049:   mov o3.xy, r5.xyxx
1050:   mov o4.x, r3.z
1051:   emit_stream m0

#line 194
1052:   nop   // m0 <- triStream

#line 195
1053:   nop 
1054:   mov r4.xyz, r10.xyzx
1055:   mov r5.xyz, r9.xyzx
1056:   mov r7.xyz, r7.xyzx
1057:   nop 
1058:   mov r3.z, vPrim

#line 120
1059:   mov r3.z, r3.z

#line 122
1060:   mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 123
1061:   dp3 r3.w, r4.xyzx, r4.xyzx
1062:   rsq r3.w, r3.w
1063:   mul r6.xyz, r3.wwww, r4.xyzx  // r6.x <- o.NormalW.x; r6.y <- o.NormalW.y; r6.z <- o.NormalW.z

#line 124
1064:   mov r11.xy, l(0,1.000000,0,0)  // r11.x <- o.TexC.x; r11.y <- o.TexC.y

#line 125
1065:   mov r4.w, l(1.000000)
1066:   dp4 r12.x, r4.xyzw, cb1[16].xyzw  // r12.x <- o.PosH.x
1067:   dp4 r12.y, r4.xyzw, cb1[17].xyzw  // r12.y <- o.PosH.y
1068:   dp4 r12.z, r4.xyzw, cb1[18].xyzw  // r12.z <- o.PosH.z
1069:   dp4 r12.w, r4.xyzw, cb1[19].xyzw  // r12.w <- o.PosH.w

#line 126
1070:   mov o0.xyzw, r12.xyzw
1071:   mov o1.xyz, r4.xyzx
1072:   mov o2.xyz, r6.xyzx
1073:   mov o3.xy, r11.xyxx
1074:   mov o4.x, r3.z
1075:   emit_stream m0

#line 127
1076:   mov r5.xyz, r5.xyzx  // r5.x <- o.PosW.x; r5.y <- o.PosW.y; r5.z <- o.PosW.z

#line 128
1077:   dp3 r3.w, r5.xyzx, r5.xyzx
1078:   rsq r3.w, r3.w
1079:   mul r4.xyz, r3.wwww, r5.xyzx  // r4.x <- o.NormalW.x; r4.y <- o.NormalW.y; r4.z <- o.NormalW.z

#line 129
1080:   mov r6.xy, l(1.000000,1.000000,0,0)  // r6.x <- o.TexC.x; r6.y <- o.TexC.y

#line 130
1081:   mov r5.w, l(1.000000)
1082:   dp4 r11.x, r5.xyzw, cb1[16].xyzw  // r11.x <- o.PosH.x
1083:   dp4 r11.y, r5.xyzw, cb1[17].xyzw  // r11.y <- o.PosH.y
1084:   dp4 r11.z, r5.xyzw, cb1[18].xyzw  // r11.z <- o.PosH.z
1085:   dp4 r11.w, r5.xyzw, cb1[19].xyzw  // r11.w <- o.PosH.w

#line 131
1086:   mov o0.xyzw, r11.xyzw
1087:   mov o1.xyz, r5.xyzx
1088:   mov o2.xyz, r4.xyzx
1089:   mov o3.xy, r6.xyxx
1090:   mov o4.x, r3.z
1091:   emit_stream m0

#line 132
1092:   mov r7.xyz, r7.xyzx  // r7.x <- o.PosW.x; r7.y <- o.PosW.y; r7.z <- o.PosW.z

#line 133
1093:   dp3 r3.w, r7.xyzx, r7.xyzx
1094:   rsq r3.w, r3.w
1095:   mul r4.xyz, r3.wwww, r7.xyzx

#line 134
1096:   mov r5.xy, l(0.500000,0,0,0)  // r5.x <- o.TexC.x; r5.y <- o.TexC.y

#line 135
1097:   mov r7.w, l(1.000000)
1098:   dp4 r6.x, r7.xyzw, cb1[16].xyzw  // r6.x <- o.PosH.x
1099:   dp4 r6.y, r7.xyzw, cb1[17].xyzw  // r6.y <- o.PosH.y
1100:   dp4 r6.z, r7.xyzw, cb1[18].xyzw  // r6.z <- o.PosH.z
1101:   dp4 r6.w, r7.xyzw, cb1[19].xyzw  // r6.w <- o.PosH.w

#line 136
1102:   mov o0.xyzw, r6.xyzw
1103:   mov o1.xyz, r7.xyzx
1104:   mov o2.xyz, r4.xyzx
1105:   mov o3.xy, r5.xyxx
1106:   mov o4.x, r3.z
1107:   emit_stream m0

#line 195
1108:   nop   // m0 <- triStream

#line 196
1109:   nop 
1110:   mov r8.xyz, r8.xyzx
1111:   mov r9.xyz, r9.xyzx
1112:   nop 
1113:   mov r3.z, vPrim

#line 120
1114:   mov r3.z, r3.z

#line 122
1115:   mov r8.xyz, r8.xyzx  // r8.x <- o.PosW.x; r8.y <- o.PosW.y; r8.z <- o.PosW.z

#line 123
1116:   dp3 r3.w, r8.xyzx, r8.xyzx
1117:   rsq r3.w, r3.w
1118:   mul r4.xyz, r3.wwww, r8.xyzx

#line 124
1119:   mov r5.xy, l(0,1.000000,0,0)

#line 125
1120:   mov r8.w, l(1.000000)
1121:   dp4 r6.x, r8.xyzw, cb1[16].xyzw
1122:   dp4 r6.y, r8.xyzw, cb1[17].xyzw
1123:   dp4 r6.z, r8.xyzw, cb1[18].xyzw
1124:   dp4 r6.w, r8.xyzw, cb1[19].xyzw

#line 126
1125:   mov o0.xyzw, r6.xyzw
1126:   mov o1.xyz, r8.xyzx
1127:   mov o2.xyz, r4.xyzx
1128:   mov o3.xy, r5.xyxx
1129:   mov o4.x, r3.z
1130:   emit_stream m0

#line 127
1131:   mov r9.xyz, r9.xyzx  // r9.x <- o.PosW.x; r9.y <- o.PosW.y; r9.z <- o.PosW.z

#line 128
1132:   dp3 r3.w, r9.xyzx, r9.xyzx
1133:   rsq r3.w, r3.w
1134:   mul r4.xyz, r3.wwww, r9.xyzx

#line 129
1135:   mov r5.xy, l(1.000000,1.000000,0,0)

#line 130
1136:   mov r9.w, l(1.000000)
1137:   dp4 r6.x, r9.xyzw, cb1[16].xyzw
1138:   dp4 r6.y, r9.xyzw, cb1[17].xyzw
1139:   dp4 r6.z, r9.xyzw, cb1[18].xyzw
1140:   dp4 r6.w, r9.xyzw, cb1[19].xyzw

#line 131
1141:   mov o0.xyzw, r6.xyzw
1142:   mov o1.xyz, r9.xyzx
1143:   mov o2.xyz, r4.xyzx
1144:   mov o3.xy, r5.xyxx
1145:   mov o4.x, r3.z
1146:   emit_stream m0

#line 132
1147:   mov r10.xyz, r10.xyzx  // r10.x <- o.PosW.x; r10.y <- o.PosW.y; r10.z <- o.PosW.z

#line 133
1148:   dp3 r3.w, r10.xyzx, r10.xyzx
1149:   rsq r3.w, r3.w
1150:   mul r4.xyz, r3.wwww, r10.xyzx

#line 134
1151:   mov r5.xy, l(0.500000,0,0,0)

#line 135
1152:   mov r10.w, l(1.000000)
1153:   dp4 r6.x, r10.xyzw, cb1[16].xyzw
1154:   dp4 r6.y, r10.xyzw, cb1[17].xyzw
1155:   dp4 r6.z, r10.xyzw, cb1[18].xyzw
1156:   dp4 r6.w, r10.xyzw, cb1[19].xyzw

#line 136
1157:   mov o0.xyzw, r6.xyzw
1158:   mov o1.xyz, r10.xyzx
1159:   mov o2.xyz, r4.xyzx
1160:   mov o3.xy, r5.xyxx
1161:   mov o4.x, r3.z
1162:   emit_stream m0

#line 196
1163:   nop   // m0 <- triStream

#line 198
1164: else   // Prior locations: r0.x <- a.x; r0.y <- a.y; r0.z <- a.z; r1.x <- b.x; r1.y <- b.y; r1.z <- b.z; r2.x <- c.x; r2.y <- c.y; r2.z <- c.z

#line 199
1165:   lt r3.y, r3.y, l(30.000000)
1166:   if_nz r3.y

#line 201
1167:     nop 
1168:     add r3.yzw, r0.xxyz, r1.xxyz
1169:     mul r3.yzw, r3.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)
1170:     mov r3.x, r3.x

#line 111
1171:     dp3 r4.x, r3.yzwy, r3.yzwy
1172:     sqrt r4.x, r4.x  // r4.x <- len

#line 112
1173:     lt r4.y, r4.x, l(0.000001)
1174:     if_nz r4.y

#line 113
1175:       itof r5.yz, l(0, 0, 0, 0)  // r5.y <- <ProjectKeepRadius return value>.y; r5.z <- <ProjectKeepRadius return value>.z
1176:       mov r5.x, r3.x
1177:     endif   // r5.y <- <ProjectKeepRadius return value>.y; r5.z <- <ProjectKeepRadius return value>.z; r5.x <- <ProjectKeepRadius return value>.x

#line 114
1178:     if_z r4.y
1179:       div r3.yzw, r3.yyzw, r4.xxxx
1180:       mul r5.xyz, r3.xxxx, r3.yzwy
1181:     endif 

#line 201
1182:     mov r5.xyz, r5.xyzx  // r5.x <- ab.x; r5.y <- ab.y; r5.z <- ab.z

#line 202
1183:     nop 
1184:     add r3.yzw, r1.xxyz, r2.xxyz
1185:     mul r3.yzw, r3.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)
1186:     mov r3.x, r3.x

#line 111
1187:     dp3 r4.x, r3.yzwy, r3.yzwy
1188:     sqrt r4.x, r4.x  // r4.x <- len

#line 112
1189:     lt r4.y, r4.x, l(0.000001)
1190:     if_nz r4.y

#line 113
1191:       itof r6.yz, l(0, 0, 0, 0)  // r6.y <- <ProjectKeepRadius return value>.y; r6.z <- <ProjectKeepRadius return value>.z
1192:       mov r6.x, r3.x  // r5.y <- <ProjectKeepRadius return value>.y; r5.z <- <ProjectKeepRadius return value>.z
1193:     endif   // r6.y <- <ProjectKeepRadius return value>.y; r6.z <- <ProjectKeepRadius return value>.z; r6.x <- <ProjectKeepRadius return value>.x

#line 114
1194:     if_z r4.y
1195:       div r3.yzw, r3.yyzw, r4.xxxx
1196:       mul r6.xyz, r3.xxxx, r3.yzwy
1197:     endif 

#line 202
1198:     mov r6.xyz, r6.xyzx  // r6.x <- bc.x; r6.y <- bc.y; r6.z <- bc.z

#line 203
1199:     nop 
1200:     add r3.yzw, r0.xxyz, r2.xxyz
1201:     mul r3.yzw, r3.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)
1202:     mov r3.x, r3.x

#line 111
1203:     dp3 r4.x, r3.yzwy, r3.yzwy
1204:     sqrt r4.x, r4.x  // r4.x <- len

#line 112
1205:     lt r4.y, r4.x, l(0.000001)
1206:     if_nz r4.y

#line 113
1207:       itof r7.yz, l(0, 0, 0, 0)  // r7.y <- <ProjectKeepRadius return value>.y; r7.z <- <ProjectKeepRadius return value>.z
1208:       mov r7.x, r3.x  // r6.y <- <ProjectKeepRadius return value>.y; r6.z <- <ProjectKeepRadius return value>.z
1209:     endif   // r7.y <- <ProjectKeepRadius return value>.y; r7.z <- <ProjectKeepRadius return value>.z; r7.x <- <ProjectKeepRadius return value>.x

#line 114
1210:     if_z r4.y
1211:       div r3.yzw, r3.yyzw, r4.xxxx
1212:       mul r7.xyz, r3.xxxx, r3.yzwy
1213:     endif 

#line 203
1214:     mov r7.xyz, r7.xyzx  // r7.x <- ca.x; r7.y <- ca.y; r7.z <- ca.z

#line 205
1215:     nop 
1216:     mov r0.xyz, r0.xyzx
1217:     mov r5.xyz, r5.xyzx
1218:     mov r7.xyz, r7.xyzx
1219:     nop 
1220:     mov r3.x, vPrim

#line 120
1221:     mov r3.x, r3.x  // r3.x <- o.PrimID

#line 122
1222:     mov r0.xyz, r0.xyzx  // r0.x <- o.PosW.x; r0.y <- o.PosW.y; r0.z <- o.PosW.z

#line 123
1223:     dp3 r3.y, r0.xyzx, r0.xyzx
1224:     rsq r3.y, r3.y
1225:     mul r3.yzw, r0.xxyz, r3.yyyy  // r3.y <- o.NormalW.x; r3.z <- o.NormalW.y; r3.w <- o.NormalW.z

#line 124
1226:     mov r4.xy, l(0,1.000000,0,0)  // r4.x <- o.TexC.x; r4.y <- o.TexC.y

#line 125
1227:     mov r0.w, l(1.000000)
1228:     dp4 r8.x, r0.xyzw, cb1[16].xyzw  // r8.x <- o.PosH.x
1229:     dp4 r8.y, r0.xyzw, cb1[17].xyzw  // r8.y <- o.PosH.y
1230:     dp4 r8.z, r0.xyzw, cb1[18].xyzw  // r8.z <- o.PosH.z
1231:     dp4 r8.w, r0.xyzw, cb1[19].xyzw  // r8.w <- o.PosH.w

#line 126
1232:     mov o0.xyzw, r8.xyzw
1233:     mov o1.xyz, r0.xyzx
1234:     mov o2.xyz, r3.yzwy
1235:     mov o3.xy, r4.xyxx
1236:     mov o4.x, r3.x
1237:     emit_stream m0

#line 127
1238:     mov r5.xyz, r5.xyzx  // r5.x <- o.PosW.x; r5.y <- o.PosW.y; r5.z <- o.PosW.z

#line 128
1239:     dp3 r3.y, r5.xyzx, r5.xyzx
1240:     rsq r3.y, r3.y
1241:     mul r3.yzw, r3.yyyy, r5.xxyz  // r3.y <- o.NormalW.x

#line 129
1242:     mov r4.xy, l(1.000000,1.000000,0,0)

#line 130
1243:     mov r5.w, l(1.000000)
1244:     dp4 r8.x, r5.xyzw, cb1[16].xyzw
1245:     dp4 r8.y, r5.xyzw, cb1[17].xyzw
1246:     dp4 r8.z, r5.xyzw, cb1[18].xyzw
1247:     dp4 r8.w, r5.xyzw, cb1[19].xyzw

#line 131
1248:     mov o0.xyzw, r8.xyzw
1249:     mov o1.xyz, r5.xyzx
1250:     mov o2.xyz, r3.yzwy
1251:     mov o3.xy, r4.xyxx
1252:     mov o4.x, r3.x
1253:     emit_stream m0

#line 132
1254:     mov r7.xyz, r7.xyzx  // r7.x <- o.PosW.x; r7.y <- o.PosW.y; r7.z <- o.PosW.z

#line 133
1255:     dp3 r3.y, r7.xyzx, r7.xyzx
1256:     rsq r3.y, r3.y
1257:     mul r3.yzw, r3.yyyy, r7.xxyz  // r3.y <- o.NormalW.x

#line 134
1258:     mov r4.xy, l(0.500000,0,0,0)

#line 135
1259:     mov r7.w, l(1.000000)
1260:     dp4 r8.x, r7.xyzw, cb1[16].xyzw
1261:     dp4 r8.y, r7.xyzw, cb1[17].xyzw
1262:     dp4 r8.z, r7.xyzw, cb1[18].xyzw
1263:     dp4 r8.w, r7.xyzw, cb1[19].xyzw

#line 136
1264:     mov o0.xyzw, r8.xyzw
1265:     mov o1.xyz, r7.xyzx
1266:     mov o2.xyz, r3.yzwy
1267:     mov o3.xy, r4.xyxx
1268:     mov o4.x, r3.x
1269:     emit_stream m0

#line 205
1270:     nop   // m0 <- triStream

#line 206
1271:     nop 
1272:     mov r3.xyz, r5.xyzx
1273:     mov r1.xyz, r1.xyzx
1274:     mov r6.xyz, r6.xyzx
1275:     nop 
1276:     mov r4.x, vPrim

#line 120
1277:     mov r4.x, r4.x  // r4.x <- o.PrimID

#line 122
1278:     mov r3.xyz, r3.xyzx  // r3.x <- o.PosW.x; r3.y <- o.PosW.y; r3.z <- o.PosW.z

#line 123
1279:     dp3 r4.y, r3.xyzx, r3.xyzx
1280:     rsq r4.y, r4.y
1281:     mul r4.yzw, r3.xxyz, r4.yyyy  // r4.y <- o.NormalW.x; r4.z <- o.NormalW.y; r4.w <- o.NormalW.z

#line 124
1282:     mov r8.xy, l(0,1.000000,0,0)  // r8.x <- o.TexC.x; r8.y <- o.TexC.y

#line 125
1283:     mov r3.w, l(1.000000)
1284:     dp4 r9.x, r3.xyzw, cb1[16].xyzw  // r9.x <- o.PosH.x
1285:     dp4 r9.y, r3.xyzw, cb1[17].xyzw  // r9.y <- o.PosH.y
1286:     dp4 r9.z, r3.xyzw, cb1[18].xyzw  // r9.z <- o.PosH.z
1287:     dp4 r9.w, r3.xyzw, cb1[19].xyzw  // r9.w <- o.PosH.w

#line 126
1288:     mov o0.xyzw, r9.xyzw
1289:     mov o1.xyz, r3.xyzx
1290:     mov o2.xyz, r4.yzwy
1291:     mov o3.xy, r8.xyxx
1292:     mov o4.x, r4.x
1293:     emit_stream m0

#line 127
1294:     mov r1.xyz, r1.xyzx  // r1.x <- o.PosW.x; r1.y <- o.PosW.y; r1.z <- o.PosW.z

#line 128
1295:     dp3 r3.x, r1.xyzx, r1.xyzx
1296:     rsq r3.x, r3.x
1297:     mul r3.xyz, r1.xyzx, r3.xxxx  // r3.x <- o.NormalW.x; r3.y <- o.NormalW.y; r3.z <- o.NormalW.z

#line 129
1298:     mov r4.yz, l(0,1.000000,1.000000,0)  // r4.y <- o.TexC.x; r4.z <- o.TexC.y

#line 130
1299:     mov r1.w, l(1.000000)
1300:     dp4 r8.x, r1.xyzw, cb1[16].xyzw  // r8.x <- o.PosH.x
1301:     dp4 r8.y, r1.xyzw, cb1[17].xyzw  // r8.y <- o.PosH.y
1302:     dp4 r8.z, r1.xyzw, cb1[18].xyzw  // r8.z <- o.PosH.z
1303:     dp4 r8.w, r1.xyzw, cb1[19].xyzw  // r8.w <- o.PosH.w

#line 131
1304:     mov o0.xyzw, r8.xyzw
1305:     mov o1.xyz, r1.xyzx
1306:     mov o2.xyz, r3.xyzx
1307:     mov o3.xy, r4.yzyy
1308:     mov o4.x, r4.x
1309:     emit_stream m0

#line 132
1310:     mov r6.xyz, r6.xyzx  // r6.x <- o.PosW.x; r6.y <- o.PosW.y; r6.z <- o.PosW.z

#line 133
1311:     dp3 r3.x, r6.xyzx, r6.xyzx
1312:     rsq r3.x, r3.x
1313:     mul r3.xyz, r3.xxxx, r6.xyzx  // r3.x <- o.NormalW.x

#line 134
1314:     mov r4.yz, l(0,0.500000,0,0)

#line 135
1315:     mov r6.w, l(1.000000)
1316:     dp4 r8.x, r6.xyzw, cb1[16].xyzw
1317:     dp4 r8.y, r6.xyzw, cb1[17].xyzw
1318:     dp4 r8.z, r6.xyzw, cb1[18].xyzw
1319:     dp4 r8.w, r6.xyzw, cb1[19].xyzw

#line 136
1320:     mov o0.xyzw, r8.xyzw
1321:     mov o1.xyz, r6.xyzx
1322:     mov o2.xyz, r3.xyzx
1323:     mov o3.xy, r4.yzyy
1324:     mov o4.x, r4.x
1325:     emit_stream m0

#line 206
1326:     nop   // m0 <- triStream

#line 207
1327:     nop 
1328:     mov r3.xyz, r7.xyzx
1329:     mov r4.xyz, r6.xyzx
1330:     mov r2.xyz, r2.xyzx
1331:     nop 
1332:     mov r8.x, vPrim

#line 120
1333:     mov r8.x, r8.x  // r8.x <- o.PrimID

#line 122
1334:     mov r3.xyz, r3.xyzx  // r3.x <- o.PosW.x; r3.y <- o.PosW.y; r3.z <- o.PosW.z

#line 123
1335:     dp3 r8.y, r3.xyzx, r3.xyzx
1336:     rsq r8.y, r8.y
1337:     mul r8.yzw, r3.xxyz, r8.yyyy  // r8.y <- o.NormalW.x; r8.z <- o.NormalW.y; r8.w <- o.NormalW.z

#line 124
1338:     mov r9.xy, l(0,1.000000,0,0)  // r9.x <- o.TexC.x; r9.y <- o.TexC.y

#line 125
1339:     mov r3.w, l(1.000000)
1340:     dp4 r10.x, r3.xyzw, cb1[16].xyzw  // r10.x <- o.PosH.x
1341:     dp4 r10.y, r3.xyzw, cb1[17].xyzw  // r10.y <- o.PosH.y
1342:     dp4 r10.z, r3.xyzw, cb1[18].xyzw  // r10.z <- o.PosH.z
1343:     dp4 r10.w, r3.xyzw, cb1[19].xyzw  // r10.w <- o.PosH.w

#line 126
1344:     mov o0.xyzw, r10.xyzw
1345:     mov o1.xyz, r3.xyzx
1346:     mov o2.xyz, r8.yzwy
1347:     mov o3.xy, r9.xyxx
1348:     mov o4.x, r8.x
1349:     emit_stream m0

#line 127
1350:     mov r4.xyz, r4.xyzx  // r4.x <- o.PosW.x; r4.y <- o.PosW.y; r4.z <- o.PosW.z

#line 128
1351:     dp3 r3.x, r4.xyzx, r4.xyzx
1352:     rsq r3.x, r3.x
1353:     mul r3.xyz, r3.xxxx, r4.xyzx  // r3.x <- o.NormalW.x; r3.y <- o.NormalW.y; r3.z <- o.NormalW.z

#line 129
1354:     mov r8.yz, l(0,1.000000,1.000000,0)  // r8.y <- o.TexC.x; r8.z <- o.TexC.y

#line 130
1355:     mov r4.w, l(1.000000)
1356:     dp4 r9.x, r4.xyzw, cb1[16].xyzw  // r9.x <- o.PosH.x
1357:     dp4 r9.y, r4.xyzw, cb1[17].xyzw  // r9.y <- o.PosH.y
1358:     dp4 r9.z, r4.xyzw, cb1[18].xyzw  // r9.z <- o.PosH.z
1359:     dp4 r9.w, r4.xyzw, cb1[19].xyzw  // r9.w <- o.PosH.w

#line 131
1360:     mov o0.xyzw, r9.xyzw
1361:     mov o1.xyz, r4.xyzx
1362:     mov o2.xyz, r3.xyzx
1363:     mov o3.xy, r8.yzyy
1364:     mov o4.x, r8.x
1365:     emit_stream m0

#line 132
1366:     mov r2.xyz, r2.xyzx  // r2.x <- o.PosW.x; r2.y <- o.PosW.y; r2.z <- o.PosW.z

#line 133
1367:     dp3 r3.x, r2.xyzx, r2.xyzx
1368:     rsq r3.x, r3.x
1369:     mul r3.xyz, r2.xyzx, r3.xxxx  // r3.x <- o.NormalW.x

#line 134
1370:     mov r4.xy, l(0.500000,0,0,0)  // r4.x <- o.TexC.x; r4.y <- o.TexC.y

#line 135
1371:     mov r2.w, l(1.000000)
1372:     dp4 r9.x, r2.xyzw, cb1[16].xyzw
1373:     dp4 r9.y, r2.xyzw, cb1[17].xyzw
1374:     dp4 r9.z, r2.xyzw, cb1[18].xyzw
1375:     dp4 r9.w, r2.xyzw, cb1[19].xyzw

#line 136
1376:     mov o0.xyzw, r9.xyzw
1377:     mov o1.xyz, r2.xyzx
1378:     mov o2.xyz, r3.xyzx
1379:     mov o3.xy, r4.xyxx
1380:     mov o4.x, r8.x
1381:     emit_stream m0

#line 207
1382:     nop   // m0 <- triStream

#line 208
1383:     nop 
1384:     mov r5.xyz, r5.xyzx
1385:     mov r6.xyz, r6.xyzx
1386:     nop 
1387:     mov r3.x, vPrim

#line 120
1388:     mov r3.x, r3.x  // r3.x <- o.PrimID

#line 122
1389:     mov r5.xyz, r5.xyzx  // r5.x <- o.PosW.x; r5.y <- o.PosW.y; r5.z <- o.PosW.z

#line 123
1390:     dp3 r3.y, r5.xyzx, r5.xyzx
1391:     rsq r3.y, r3.y
1392:     mul r3.yzw, r3.yyyy, r5.xxyz  // r3.y <- o.NormalW.x; r3.z <- o.NormalW.y; r3.w <- o.NormalW.z

#line 124
1393:     mov r4.xy, l(0,1.000000,0,0)

#line 125
1394:     mov r5.w, l(1.000000)
1395:     dp4 r8.x, r5.xyzw, cb1[16].xyzw  // r8.x <- o.PosH.x
1396:     dp4 r8.y, r5.xyzw, cb1[17].xyzw  // r8.y <- o.PosH.y
1397:     dp4 r8.z, r5.xyzw, cb1[18].xyzw  // r8.z <- o.PosH.z
1398:     dp4 r8.w, r5.xyzw, cb1[19].xyzw  // r8.w <- o.PosH.w

#line 126
1399:     mov o0.xyzw, r8.xyzw
1400:     mov o1.xyz, r5.xyzx
1401:     mov o2.xyz, r3.yzwy
1402:     mov o3.xy, r4.xyxx
1403:     mov o4.x, r3.x
1404:     emit_stream m0

#line 127
1405:     mov r6.xyz, r6.xyzx  // r6.x <- o.PosW.x; r6.y <- o.PosW.y; r6.z <- o.PosW.z

#line 128
1406:     dp3 r3.y, r6.xyzx, r6.xyzx
1407:     rsq r3.y, r3.y
1408:     mul r3.yzw, r3.yyyy, r6.xxyz  // r3.y <- o.NormalW.x

#line 129
1409:     mov r4.xy, l(1.000000,1.000000,0,0)

#line 130
1410:     mov r6.w, l(1.000000)
1411:     dp4 r5.x, r6.xyzw, cb1[16].xyzw  // r5.x <- o.PosH.x
1412:     dp4 r5.y, r6.xyzw, cb1[17].xyzw  // r5.y <- o.PosH.y
1413:     dp4 r5.z, r6.xyzw, cb1[18].xyzw  // r5.z <- o.PosH.z
1414:     dp4 r5.w, r6.xyzw, cb1[19].xyzw  // r5.w <- o.PosH.w

#line 131
1415:     mov o0.xyzw, r5.xyzw
1416:     mov o1.xyz, r6.xyzx
1417:     mov o2.xyz, r3.yzwy
1418:     mov o3.xy, r4.xyxx
1419:     mov o4.x, r3.x
1420:     emit_stream m0

#line 132
1421:     mov r7.xyz, r7.xyzx  // r7.x <- o.PosW.x; r7.y <- o.PosW.y; r7.z <- o.PosW.z

#line 133
1422:     dp3 r3.y, r7.xyzx, r7.xyzx
1423:     rsq r3.y, r3.y
1424:     mul r3.yzw, r3.yyyy, r7.xxyz  // r3.y <- o.NormalW.x

#line 134
1425:     mov r4.xy, l(0.500000,0,0,0)

#line 135
1426:     mov r7.w, l(1.000000)
1427:     dp4 r5.x, r7.xyzw, cb1[16].xyzw
1428:     dp4 r5.y, r7.xyzw, cb1[17].xyzw
1429:     dp4 r5.z, r7.xyzw, cb1[18].xyzw
1430:     dp4 r5.w, r7.xyzw, cb1[19].xyzw

#line 136
1431:     mov o0.xyzw, r5.xyzw
1432:     mov o1.xyz, r7.xyzx
1433:     mov o2.xyz, r3.yzwy
1434:     mov o3.xy, r4.xyxx
1435:     mov o4.x, r3.x
1436:     emit_stream m0

#line 208
1437:     nop   // m0 <- triStream

#line 209
1438:   else   // Prior locations: r3.x <- R

#line 212
1439:     nop 
1440:     mov r0.xyz, r0.xyzx
1441:     mov r1.xyz, r1.xyzx
1442:     mov r2.xyz, r2.xyzx
1443:     nop 
1444:     mov r3.x, vPrim

#line 120
1445:     mov r3.x, r3.x  // r3.x <- o.PrimID

#line 122
1446:     mov r0.xyz, r0.xyzx  // r0.x <- o.PosW.x; r0.y <- o.PosW.y; r0.z <- o.PosW.z

#line 123
1447:     dp3 r3.y, r0.xyzx, r0.xyzx
1448:     rsq r3.y, r3.y
1449:     mul r3.yzw, r0.xxyz, r3.yyyy  // r3.y <- o.NormalW.x; r3.z <- o.NormalW.y; r3.w <- o.NormalW.z

#line 124
1450:     mov r4.xy, l(0,1.000000,0,0)  // r4.x <- o.TexC.x; r4.y <- o.TexC.y

#line 125
1451:     mov r0.w, l(1.000000)
1452:     dp4 r5.x, r0.xyzw, cb1[16].xyzw  // r5.x <- o.PosH.x
1453:     dp4 r5.y, r0.xyzw, cb1[17].xyzw  // r5.y <- o.PosH.y
1454:     dp4 r5.z, r0.xyzw, cb1[18].xyzw  // r5.z <- o.PosH.z
1455:     dp4 r5.w, r0.xyzw, cb1[19].xyzw  // r5.w <- o.PosH.w

#line 126
1456:     mov o0.xyzw, r5.xyzw
1457:     mov o1.xyz, r0.xyzx
1458:     mov o2.xyz, r3.yzwy
1459:     mov o3.xy, r4.xyxx
1460:     mov o4.x, r3.x
1461:     emit_stream m0

#line 127
1462:     mov r1.xyz, r1.xyzx  // r1.x <- o.PosW.x; r1.y <- o.PosW.y; r1.z <- o.PosW.z

#line 128
1463:     dp3 r0.x, r1.xyzx, r1.xyzx
1464:     rsq r0.x, r0.x
1465:     mul r0.xyz, r0.xxxx, r1.xyzx  // r0.x <- o.NormalW.x; r0.y <- o.NormalW.y; r0.z <- o.NormalW.z

#line 129
1466:     mov r3.yz, l(0,1.000000,1.000000,0)  // r3.y <- o.TexC.x; r3.z <- o.TexC.y

#line 130
1467:     mov r1.w, l(1.000000)
1468:     dp4 r4.x, r1.xyzw, cb1[16].xyzw  // r4.x <- o.PosH.x
1469:     dp4 r4.y, r1.xyzw, cb1[17].xyzw  // r4.y <- o.PosH.y
1470:     dp4 r4.z, r1.xyzw, cb1[18].xyzw  // r4.z <- o.PosH.z
1471:     dp4 r4.w, r1.xyzw, cb1[19].xyzw  // r4.w <- o.PosH.w

#line 131
1472:     mov o0.xyzw, r4.xyzw
1473:     mov o1.xyz, r1.xyzx
1474:     mov o2.xyz, r0.xyzx
1475:     mov o3.xy, r3.yzyy
1476:     mov o4.x, r3.x
1477:     emit_stream m0

#line 132
1478:     mov r2.xyz, r2.xyzx  // r2.x <- o.PosW.x; r2.y <- o.PosW.y; r2.z <- o.PosW.z

#line 133
1479:     dp3 r0.x, r2.xyzx, r2.xyzx
1480:     rsq r0.x, r0.x
1481:     mul r0.xyz, r0.xxxx, r2.xyzx  // r0.x <- o.NormalW.x

#line 134
1482:     mov r1.xy, l(0.500000,0,0,0)  // r1.x <- o.TexC.x; r1.y <- o.TexC.y

#line 135
1483:     mov r2.w, l(1.000000)
1484:     dp4 r4.x, r2.xyzw, cb1[16].xyzw
1485:     dp4 r4.y, r2.xyzw, cb1[17].xyzw
1486:     dp4 r4.z, r2.xyzw, cb1[18].xyzw
1487:     dp4 r4.w, r2.xyzw, cb1[19].xyzw

#line 136
1488:     mov o0.xyzw, r4.xyzw
1489:     mov o1.xyz, r2.xyzx
1490:     mov o2.xyz, r0.xyzx
1491:     mov o3.xy, r1.xyxx
1492:     mov o4.x, r3.x
1493:     emit_stream m0

#line 212
1494:     nop   // m0 <- triStream

#line 213
1495:   endif 
1496: endif 

#line 214
1497: ret 
// Approximately 1498 instruction slots used
 