//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbSettings
// {
//
//   int gBlurRadius;                   // Offset:    0 Size:     4
//   float3 pad;                        // Offset:    4 Size:    12 [unused]
//   float weight[49];                  // Offset:   16 Size:   772
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gInput                            texture  float4          2d             t0      1 
// gOutput                               UAV  float4          2d             u0      1 
// cbSettings                        cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      cs_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[50], immediateIndexed
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_uav_typed_texture2d (float,float,float,float) u0
      dcl_input vThreadIDInGroup.xy
      dcl_input vThreadID.xy
      dcl_temps 7
      dcl_indexableTemp x0[49], 4
      dcl_tgsm_structured g0, 16, 484
      dcl_thread_group 16, 16, 1
//
// Initial variable locations:
//   vThreadIDInGroup.x <- groupThreadID.x; vThreadIDInGroup.y <- groupThreadID.y; vThreadIDInGroup.z <- groupThreadID.z; 
//   vThreadID.x <- dispatchThreadID.x; vThreadID.y <- dispatchThreadID.y; vThreadID.z <- dispatchThreadID.z; 
//   x0 <- weights
//
#line 8 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap13\Chap13_Solution\Chap13_4\Shaders\Blur.hlsl"
   0: mov r0.x, l(3)  // r0.x <- gMaxBlurRadius

#line 38
   1: resinfo_indexable(texture2d)(float,float,float,float)_uint r0.yz, l(0), t0.zxyw
   2: mov r0.y, r0.y  // r0.y <- texW
   3: mov r0.z, r0.z  // r0.z <- texH

#line 40
   4: mov r0.w, l(0)
   5: ult r0.w, r0.w, r0.y
   6: ineg r1.x, l(1)
   7: iadd r1.x, r0.y, r1.x
   8: movc r1.x, r0.w, r1.x, l(0)  // r1.x <- maxX

#line 41
   9: mov r0.w, l(0)
  10: ult r0.w, r0.w, r0.z
  11: ineg r1.z, l(1)
  12: iadd r1.z, r0.z, r1.z
  13: movc r1.y, r0.w, r1.z, l(0)  // r1.y <- maxY

#line 43
  14: mov r1.zw, l(0,0,0,0)  // r1.z <- lo.x; r1.w <- lo.y

#line 44
  15: mov r1.x, r1.x  // r1.x <- hi.x
  16: mov r1.y, r1.y  // r1.y <- hi.y

#line 46
  17: mov r0.w, vThreadIDInGroup.x  // r0.w <- gx

#line 47
  18: mov r2.x, vThreadIDInGroup.y  // r2.x <- gy

#line 48
  19: mov r3.y, vThreadID.x  // r3.y <- dx

#line 49
  20: mov r3.xzw, vThreadID.yyyy  // r3.w <- dy

#line 51
  21: ilt r0.y, r3.y, r0.y
  22: ilt r0.z, r3.x, r0.z
  23: and r0.y, r0.z, r0.y  // r0.y <- inBounds

#line 53
  24: imin r0.z, r0.x, cb0[0].x  // r0.z <- radius

#line 55
  25: mov x0[0].x, cb0[1].x
  26: mov x0[1].x, cb0[2].x
  27: mov x0[2].x, cb0[3].x
  28: mov x0[3].x, cb0[4].x
  29: mov x0[4].x, cb0[5].x
  30: mov x0[5].x, cb0[6].x
  31: mov x0[6].x, cb0[7].x
  32: mov x0[7].x, cb0[8].x
  33: mov x0[8].x, cb0[9].x
  34: mov x0[9].x, cb0[10].x
  35: mov x0[10].x, cb0[11].x
  36: mov x0[11].x, cb0[12].x
  37: mov x0[12].x, cb0[13].x
  38: mov x0[13].x, cb0[14].x
  39: mov x0[14].x, cb0[15].x
  40: mov x0[15].x, cb0[16].x
  41: mov x0[16].x, cb0[17].x
  42: mov x0[17].x, cb0[18].x
  43: mov x0[18].x, cb0[19].x
  44: mov x0[19].x, cb0[20].x
  45: mov x0[20].x, cb0[21].x
  46: mov x0[21].x, cb0[22].x
  47: mov x0[22].x, cb0[23].x
  48: mov x0[23].x, cb0[24].x
  49: mov x0[24].x, cb0[25].x
  50: mov x0[25].x, cb0[26].x
  51: mov x0[26].x, cb0[27].x
  52: mov x0[27].x, cb0[28].x
  53: mov x0[28].x, cb0[29].x
  54: mov x0[29].x, cb0[30].x
  55: mov x0[30].x, cb0[31].x
  56: mov x0[31].x, cb0[32].x
  57: mov x0[32].x, cb0[33].x
  58: mov x0[33].x, cb0[34].x
  59: mov x0[34].x, cb0[35].x
  60: mov x0[35].x, cb0[36].x
  61: mov x0[36].x, cb0[37].x
  62: mov x0[37].x, cb0[38].x
  63: mov x0[38].x, cb0[39].x
  64: mov x0[39].x, cb0[40].x
  65: mov x0[40].x, cb0[41].x
  66: mov x0[41].x, cb0[42].x
  67: mov x0[42].x, cb0[43].x
  68: mov x0[43].x, cb0[44].x
  69: mov x0[44].x, cb0[45].x
  70: mov x0[45].x, cb0[46].x
  71: mov x0[46].x, cb0[47].x
  72: mov x0[47].x, cb0[48].x
  73: mov x0[48].x, cb0[49].x

#line 58
  74: iadd r2.y, r0.w, l(3)  // r2.y <- cx

#line 59
  75: iadd r2.z, r2.x, l(3)  // r2.z <- cy

#line 60
  76: nop 
  77: mov r2.y, r2.y
  78: mov r2.z, r2.z

#line 22
  79: imul null, r2.w, r2.z, l(22)
  80: iadd r2.w, r2.y, r2.w  // r2.w <- <CacheIndex return value>

#line 60
  81: mov r2.w, r2.w  // r2.w <- cIndex

#line 63
  82: nop 
  83: mov r3.y, r3.y
  84: mov r3.x, r3.x
  85: mov r1.xy, r1.xyxx

#line 27
  86: ilt r4.x, r1.x, r3.y
  87: movc r4.x, r4.x, r1.x, r3.y  // r4.x <- <ClampCoord return value>.x
  88: ilt r5.x, r1.y, r3.x
  89: movc r4.y, r5.x, r1.y, r3.x  // r4.y <- <ClampCoord return value>.y

#line 63
  90: mov r4.xy, r4.xyxx  // r4.x <- pCenter.x; r4.y <- pCenter.y

#line 64
  91: mov r4.zw, l(0,0,0,0)
  92: ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyzw, t0.xyzw
  93: store_structured g0.x, r2.w, l(0), r4.x
  94: store_structured g0.x, r2.w, l(4), r4.y
  95: store_structured g0.x, r2.w, l(8), r4.z
  96: store_structured g0.x, r2.w, l(12), r4.w

#line 67
  97: ilt r4.x, r0.w, r0.z
  98: if_nz r4.x

#line 69
  99:   nop 
 100:   ineg r4.x, r0.z
 101:   iadd r4.x, r3.y, r4.x
 102:   mov r3.x, r3.x
 103:   mov r1.z, r1.z

#line 27
 104:   ilt r4.y, r4.x, r1.z
 105:   ilt r4.z, r1.x, r4.x
 106:   movc r4.x, r4.z, r1.x, r4.x
 107:   movc r4.x, r4.y, r1.z, r4.x  // r4.x <- <ClampCoord return value>.x
 108:   ilt r5.x, r1.y, r3.x
 109:   movc r4.y, r5.x, r1.y, r3.x  // r4.y <- <ClampCoord return value>.y

#line 69
 110:   mov r4.xy, r4.xyxx  // r4.x <- p.x; r4.y <- p.y

#line 70
 111:   nop 
 112:   ineg r5.x, r0.z
 113:   iadd r5.x, r2.y, r5.x

#line 22
 114:   imul null, r5.y, r2.z, l(22)
 115:   iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 70
 116:   mov r4.zw, l(0,0,0,0)
 117:   ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyzw, t0.xyzw
 118:   store_structured g0.x, r5.x, l(0), r4.x
 119:   store_structured g0.x, r5.x, l(4), r4.y
 120:   store_structured g0.x, r5.x, l(8), r4.z
 121:   store_structured g0.x, r5.x, l(12), r4.w

#line 71
 122: endif 

#line 72
 123: ineg r4.x, r0.z
 124: iadd r4.x, r4.x, l(16)
 125: ige r4.x, r0.w, r4.x
 126: if_nz r4.x

#line 74
 127:   nop 
 128:   iadd r4.x, r0.z, r3.y
 129:   mov r3.x, r3.x
 130:   mov r1.z, r1.z

#line 27
 131:   ilt r4.y, r4.x, r1.z
 132:   ilt r4.z, r1.x, r4.x
 133:   movc r4.x, r4.z, r1.x, r4.x
 134:   movc r4.x, r4.y, r1.z, r4.x  // r4.x <- <ClampCoord return value>.x
 135:   ilt r5.x, r1.y, r3.x
 136:   movc r4.y, r5.x, r1.y, r3.x  // r4.y <- <ClampCoord return value>.y

#line 74
 137:   mov r4.xy, r4.xyxx  // r4.x <- p.x; r4.y <- p.y

#line 75
 138:   nop 
 139:   iadd r5.x, r0.z, r2.y

#line 22
 140:   imul null, r5.y, r2.z, l(22)
 141:   iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 75
 142:   mov r4.zw, l(0,0,0,0)
 143:   ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyzw, t0.xyzw
 144:   store_structured g0.x, r5.x, l(0), r4.x
 145:   store_structured g0.x, r5.x, l(4), r4.y
 146:   store_structured g0.x, r5.x, l(8), r4.z
 147:   store_structured g0.x, r5.x, l(12), r4.w

#line 76
 148: endif 

#line 78
 149: ilt r4.x, r2.x, r0.z
 150: if_nz r4.x

#line 80
 151:   nop 
 152:   ineg r4.x, r0.z
 153:   iadd r4.x, r3.x, r4.x
 154:   mov r1.w, r1.w

#line 27
 155:   ilt r4.y, r1.x, r3.y
 156:   movc r5.x, r4.y, r1.x, r3.y  // r5.x <- <ClampCoord return value>.x
 157:   ilt r4.y, r4.x, r1.w
 158:   ilt r4.z, r1.y, r4.x
 159:   movc r4.x, r4.z, r1.y, r4.x
 160:   movc r5.y, r4.y, r1.w, r4.x  // r5.y <- <ClampCoord return value>.y

#line 80
 161:   mov r5.xy, r5.xyxx  // r5.x <- p.x; r5.y <- p.y

#line 81
 162:   nop 
 163:   ineg r4.x, r0.z
 164:   iadd r4.x, r2.z, r4.x

#line 22
 165:   imul null, r4.x, r4.x, l(22)
 166:   iadd r4.x, r2.y, r4.x  // r4.x <- <CacheIndex return value>

#line 81
 167:   mov r5.zw, l(0,0,0,0)
 168:   ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyzw, t0.xyzw
 169:   store_structured g0.x, r4.x, l(0), r5.x
 170:   store_structured g0.x, r4.x, l(4), r5.y
 171:   store_structured g0.x, r4.x, l(8), r5.z
 172:   store_structured g0.x, r4.x, l(12), r5.w

#line 82
 173: endif 

#line 83
 174: ineg r4.x, r0.z
 175: iadd r4.x, r4.x, l(16)
 176: ige r4.x, r2.x, r4.x
 177: if_nz r4.x

#line 85
 178:   nop 
 179:   iadd r4.x, r0.z, r3.x
 180:   mov r1.w, r1.w

#line 27
 181:   ilt r4.y, r1.x, r3.y
 182:   movc r5.x, r4.y, r1.x, r3.y  // r5.x <- <ClampCoord return value>.x
 183:   ilt r4.y, r4.x, r1.w
 184:   ilt r4.z, r1.y, r4.x
 185:   movc r4.x, r4.z, r1.y, r4.x
 186:   movc r5.y, r4.y, r1.w, r4.x  // r5.y <- <ClampCoord return value>.y

#line 85
 187:   mov r5.xy, r5.xyxx  // r5.x <- p.x; r5.y <- p.y

#line 86
 188:   nop 
 189:   iadd r4.x, r0.z, r2.z

#line 22
 190:   imul null, r4.x, r4.x, l(22)
 191:   iadd r4.x, r2.y, r4.x  // r4.x <- <CacheIndex return value>

#line 86
 192:   mov r5.zw, l(0,0,0,0)
 193:   ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyzw, t0.xyzw
 194:   store_structured g0.x, r4.x, l(0), r5.x
 195:   store_structured g0.x, r4.x, l(4), r5.y
 196:   store_structured g0.x, r4.x, l(8), r5.z
 197:   store_structured g0.x, r4.x, l(12), r5.w

#line 87
 198: endif 

#line 89
 199: ilt r4.x, r0.w, r0.z
 200: ilt r4.y, r2.x, r0.z
 201: and r4.x, r4.y, r4.x
 202: if_nz r4.x

#line 91
 203:   nop 
 204:   ineg r4.x, r0.z
 205:   iadd r4.x, r3.y, r4.x
 206:   ineg r4.y, r0.z
 207:   iadd r4.y, r3.x, r4.y
 208:   mov r1.zw, r1.zzzw

#line 27
 209:   ilt r4.z, r4.x, r1.z
 210:   ilt r4.w, r1.x, r4.x
 211:   movc r4.x, r4.w, r1.x, r4.x
 212:   movc r5.x, r4.z, r1.z, r4.x  // r5.x <- <ClampCoord return value>.x
 213:   ilt r4.x, r4.y, r1.w
 214:   ilt r4.z, r1.y, r4.y
 215:   movc r4.y, r4.z, r1.y, r4.y
 216:   movc r5.y, r4.x, r1.w, r4.y  // r5.y <- <ClampCoord return value>.y

#line 91
 217:   mov r5.xy, r5.xyxx  // r5.x <- p.x; r5.y <- p.y

#line 92
 218:   nop 
 219:   ineg r4.x, r0.z
 220:   iadd r4.x, r2.y, r4.x
 221:   ineg r4.y, r0.z
 222:   iadd r4.y, r2.z, r4.y

#line 22
 223:   imul null, r4.y, r4.y, l(22)
 224:   iadd r4.x, r4.x, r4.y  // r4.x <- <CacheIndex return value>

#line 92
 225:   mov r5.zw, l(0,0,0,0)
 226:   ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyzw, t0.xyzw
 227:   store_structured g0.x, r4.x, l(0), r5.x
 228:   store_structured g0.x, r4.x, l(4), r5.y
 229:   store_structured g0.x, r4.x, l(8), r5.z
 230:   store_structured g0.x, r4.x, l(12), r5.w

#line 93
 231: endif 

#line 94
 232: ilt r4.x, r0.w, r0.z
 233: ineg r4.y, r0.z
 234: iadd r4.y, r4.y, l(16)
 235: ige r4.y, r2.x, r4.y
 236: and r4.x, r4.y, r4.x
 237: if_nz r4.x

#line 96
 238:   nop 
 239:   ineg r4.x, r0.z
 240:   iadd r4.x, r3.y, r4.x
 241:   iadd r4.y, r0.z, r3.x
 242:   mov r1.zw, r1.zzzw

#line 27
 243:   ilt r4.z, r4.x, r1.z
 244:   ilt r4.w, r1.x, r4.x
 245:   movc r4.x, r4.w, r1.x, r4.x
 246:   movc r5.x, r4.z, r1.z, r4.x  // r5.x <- <ClampCoord return value>.x
 247:   ilt r4.x, r4.y, r1.w
 248:   ilt r4.z, r1.y, r4.y
 249:   movc r4.y, r4.z, r1.y, r4.y
 250:   movc r5.y, r4.x, r1.w, r4.y  // r5.y <- <ClampCoord return value>.y

#line 96
 251:   mov r5.xy, r5.xyxx  // r5.x <- p.x; r5.y <- p.y

#line 97
 252:   nop 
 253:   ineg r4.x, r0.z
 254:   iadd r4.x, r2.y, r4.x
 255:   iadd r4.y, r0.z, r2.z

#line 22
 256:   imul null, r4.y, r4.y, l(22)
 257:   iadd r4.x, r4.x, r4.y  // r4.x <- <CacheIndex return value>

#line 97
 258:   mov r5.zw, l(0,0,0,0)
 259:   ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyzw, t0.xyzw
 260:   store_structured g0.x, r4.x, l(0), r5.x
 261:   store_structured g0.x, r4.x, l(4), r5.y
 262:   store_structured g0.x, r4.x, l(8), r5.z
 263:   store_structured g0.x, r4.x, l(12), r5.w

#line 98
 264: endif 

#line 99
 265: ineg r4.x, r0.z
 266: iadd r4.x, r4.x, l(16)
 267: ige r4.x, r0.w, r4.x
 268: ilt r4.y, r2.x, r0.z
 269: and r4.x, r4.y, r4.x
 270: if_nz r4.x

#line 101
 271:   nop 
 272:   iadd r4.x, r0.z, r3.y
 273:   ineg r4.y, r0.z
 274:   iadd r4.y, r3.x, r4.y
 275:   mov r1.zw, r1.zzzw

#line 27
 276:   ilt r4.z, r4.x, r1.z
 277:   ilt r4.w, r1.x, r4.x
 278:   movc r4.x, r4.w, r1.x, r4.x
 279:   movc r5.x, r4.z, r1.z, r4.x  // r5.x <- <ClampCoord return value>.x
 280:   ilt r4.x, r4.y, r1.w
 281:   ilt r4.z, r1.y, r4.y
 282:   movc r4.y, r4.z, r1.y, r4.y
 283:   movc r5.y, r4.x, r1.w, r4.y  // r5.y <- <ClampCoord return value>.y

#line 101
 284:   mov r5.xy, r5.xyxx  // r5.x <- p.x; r5.y <- p.y

#line 102
 285:   nop 
 286:   iadd r4.x, r0.z, r2.y
 287:   ineg r4.y, r0.z
 288:   iadd r4.y, r2.z, r4.y

#line 22
 289:   imul null, r4.y, r4.y, l(22)
 290:   iadd r4.x, r4.x, r4.y  // r4.x <- <CacheIndex return value>

#line 102
 291:   mov r5.zw, l(0,0,0,0)
 292:   ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyzw, t0.xyzw
 293:   store_structured g0.x, r4.x, l(0), r5.x
 294:   store_structured g0.x, r4.x, l(4), r5.y
 295:   store_structured g0.x, r4.x, l(8), r5.z
 296:   store_structured g0.x, r4.x, l(12), r5.w

#line 103
 297: endif 

#line 104
 298: ineg r4.x, r0.z
 299: iadd r4.x, r4.x, l(16)
 300: ige r0.w, r0.w, r4.x
 301: ineg r4.x, r0.z
 302: iadd r4.x, r4.x, l(16)
 303: ige r2.x, r2.x, r4.x
 304: and r0.w, r0.w, r2.x
 305: if_nz r0.w

#line 106
 306:   nop 
 307:   iadd r0.w, r0.z, r3.y
 308:   iadd r2.x, r0.z, r3.x
 309:   mov r1.zw, r1.zzzw

#line 27
 310:   ilt r4.x, r0.w, r1.z
 311:   ilt r4.y, r1.x, r0.w
 312:   movc r0.w, r4.y, r1.x, r0.w
 313:   movc r4.x, r4.x, r1.z, r0.w  // r4.x <- <ClampCoord return value>.x
 314:   ilt r0.w, r2.x, r1.w
 315:   ilt r1.x, r1.y, r2.x
 316:   movc r1.x, r1.x, r1.y, r2.x
 317:   movc r4.y, r0.w, r1.w, r1.x  // r4.y <- <ClampCoord return value>.y

#line 106
 318:   mov r4.xy, r4.xyxx  // r4.x <- p.x; r4.y <- p.y

#line 107
 319:   nop 
 320:   iadd r0.w, r0.z, r2.y
 321:   iadd r1.x, r0.z, r2.z

#line 22
 322:   imul null, r1.x, r1.x, l(22)
 323:   iadd r0.w, r0.w, r1.x  // r0.w <- <CacheIndex return value>

#line 107
 324:   mov r4.zw, l(0,0,0,0)
 325:   ld_indexable(texture2d)(float,float,float,float) r1.xyzw, r4.xyzw, t0.xyzw
 326:   store_structured g0.x, r0.w, l(0), r1.x
 327:   store_structured g0.x, r0.w, l(4), r1.y
 328:   store_structured g0.x, r0.w, l(8), r1.z
 329:   store_structured g0.x, r0.w, l(12), r1.w

#line 108
 330: endif 

#line 110
 331: sync_g_t

#line 113
 332: ld_structured r1.x, r2.w, l(0), g0.xxxx
 333: ld_structured r1.y, r2.w, l(4), g0.xxxx
 334: ld_structured r1.z, r2.w, l(8), g0.xxxx
 335: mov r1.x, r1.x  // r1.x <- center.x
 336: mov r1.y, r1.y  // r1.y <- center.y
 337: mov r1.z, r1.z  // r1.z <- center.z

#line 115
 338: itof r4.xyzw, l(0, 0, 0, 0)  // r4.x <- sumColor.x; r4.y <- sumColor.y; r4.z <- sumColor.z; r4.w <- sumColor.w

#line 116
 339: mov r0.w, l(0)  // r0.w <- sumW

#line 119
 340: mov r1.w, l(8.000000)  // r1.w <- inv2SigmaR2

#line 122
 341: mov r2.x, l(-3)  // r2.x <- j

#line 124
 342: ineg r2.w, r0.z
 343: ilt r2.w, r2.x, r2.w
 344: ilt r5.x, r0.z, r2.x
 345: or r2.w, r2.w, r5.x
 346: if_nz r2.w

#line 125
 347:   iadd r2.x, r2.x, l(1)
 348: endif 

#line 128
 349: if_z r2.w
 350:   mov r2.w, l(-3)  // r2.w <- i

#line 130
 351:   ineg r5.x, r0.z
 352:   ilt r5.x, r2.w, r5.x
 353:   ilt r5.y, r0.z, r2.w
 354:   or r5.x, r5.y, r5.x
 355:   if_nz r5.x

#line 131
 356:     iadd r2.w, r2.w, l(1)
 357:   endif 

#line 133
 358:   if_z r5.x
 359:     iadd r5.x, r0.x, r2.x
 360:     imul null, r5.x, r5.x, l(7)
 361:     iadd r5.y, r0.x, r2.w
 362:     iadd r5.x, r5.y, r5.x  // r5.x <- wi

#line 134
 363:     mov r5.x, x0[r5.x + 0].x  // r5.x <- wS

#line 136
 364:     nop 
 365:     iadd r2.w, r2.w, r2.y
 366:     iadd r5.y, r2.x, r2.z

#line 22
 367:     imul null, r5.y, r5.y, l(22)
 368:     iadd r2.w, r2.w, r5.y  // r2.w <- <CacheIndex return value>

#line 136
 369:     ld_structured r6.x, r2.w, l(0), g0.xxxx  // r6.x <- s.x
 370:     ld_structured r6.y, r2.w, l(4), g0.xxxx  // r6.y <- s.y
 371:     ld_structured r6.z, r2.w, l(8), g0.xxxx  // r6.z <- s.z
 372:     ld_structured r6.w, r2.w, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 373:     mov r5.yzw, -r6.xxyz
 374:     add r5.yzw, r1.xxyz, r5.yyzw  // r5.y <- diff.x; r5.z <- diff.y; r5.w <- diff.z

#line 139
 375:     dp3 r2.w, r5.yzwy, r5.yzwy  // r2.w <- d2

#line 140
 376:     mov r2.w, -r2.w
 377:     mul r2.w, r1.w, r2.w
 378:     mul r2.w, r2.w, l(1.442695)
 379:     exp r2.w, r2.w  // r2.w <- wR

#line 142
 380:     mul r2.w, r2.w, r5.x  // r2.w <- w

#line 144
 381:     mul r5.xyzw, r2.wwww, r6.xyzw
 382:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 383:     add r0.w, r0.w, r2.w
 384:   endif 

#line 130
 385:   ineg r2.w, r0.z
 386:   ilt r2.w, l(-2), r2.w
 387:   ilt r5.x, r0.z, l(-2)
 388:   or r2.w, r2.w, r5.x
 389:   if_nz r2.w

#line 131
 390:     iadd r5.x, l(1), l(-2)  // r5.x <- i
 391:   else 
 392:     mov r5.x, l(-2)  // r5.x <- i
 393:   endif 

#line 133
 394:   if_z r2.w
 395:     iadd r2.w, r0.x, r2.x
 396:     imul null, r2.w, r2.w, l(7)
 397:     iadd r5.y, r0.x, r5.x
 398:     iadd r2.w, r2.w, r5.y  // r2.w <- wi

#line 134
 399:     mov r2.w, x0[r2.w + 0].x  // r2.w <- wS

#line 136
 400:     nop 
 401:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 402:     iadd r5.y, r2.x, r2.z  // r5.y <- y

#line 22
 403:     imul null, r5.y, r5.y, l(22)
 404:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 405:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 406:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 407:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 408:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 409:     mov r5.xyz, -r6.xyzx
 410:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 411:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 412:     mov r5.x, -r5.x
 413:     mul r5.x, r1.w, r5.x
 414:     mul r5.x, r5.x, l(1.442695)
 415:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 416:     mul r2.w, r2.w, r5.x  // r2.w <- w

#line 144
 417:     mul r5.xyzw, r2.wwww, r6.xyzw
 418:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 419:     add r0.w, r0.w, r2.w
 420:   endif 

#line 130
 421:   ineg r2.w, r0.z
 422:   ilt r2.w, l(-1), r2.w
 423:   ilt r5.x, r0.z, l(-1)
 424:   or r2.w, r2.w, r5.x
 425:   not r5.x, r2.w  // r5.x <- i

#line 133
 426:   if_z r2.w
 427:     iadd r2.w, r0.x, r2.x
 428:     imul null, r2.w, r2.w, l(7)
 429:     iadd r5.y, r0.x, r5.x
 430:     iadd r2.w, r2.w, r5.y  // r2.w <- wi

#line 134
 431:     mov r2.w, x0[r2.w + 0].x  // r2.w <- wS

#line 136
 432:     nop 
 433:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 434:     iadd r5.y, r2.x, r2.z  // r5.y <- y

#line 22
 435:     imul null, r5.y, r5.y, l(22)
 436:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 437:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 438:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 439:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 440:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 441:     mov r5.xyz, -r6.xyzx
 442:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 443:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 444:     mov r5.x, -r5.x
 445:     mul r5.x, r1.w, r5.x
 446:     mul r5.x, r5.x, l(1.442695)
 447:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 448:     mul r2.w, r2.w, r5.x  // r2.w <- w

#line 144
 449:     mul r5.xyzw, r2.wwww, r6.xyzw
 450:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 451:     add r0.w, r0.w, r2.w
 452:   endif 

#line 130
 453:   ineg r2.w, r0.z
 454:   ilt r2.w, l(0), r2.w
 455:   ilt r5.x, r0.z, l(0)
 456:   or r2.w, r2.w, r5.x
 457:   if_nz r2.w

#line 131
 458:     iadd r5.x, l(1), l(0)  // r5.x <- i
 459:   else 
 460:     mov r5.x, l(0)  // r5.x <- i
 461:   endif 

#line 133
 462:   if_z r2.w
 463:     iadd r2.w, r0.x, r2.x
 464:     imul null, r2.w, r2.w, l(7)
 465:     iadd r5.y, r0.x, r5.x
 466:     iadd r2.w, r2.w, r5.y  // r2.w <- wi

#line 134
 467:     mov r2.w, x0[r2.w + 0].x  // r2.w <- wS

#line 136
 468:     nop 
 469:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 470:     iadd r5.y, r2.x, r2.z  // r5.y <- y

#line 22
 471:     imul null, r5.y, r5.y, l(22)
 472:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 473:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 474:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 475:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 476:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 477:     mov r5.xyz, -r6.xyzx
 478:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 479:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 480:     mov r5.x, -r5.x
 481:     mul r5.x, r1.w, r5.x
 482:     mul r5.x, r5.x, l(1.442695)
 483:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 484:     mul r2.w, r2.w, r5.x  // r2.w <- w

#line 144
 485:     mul r5.xyzw, r2.wwww, r6.xyzw
 486:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 487:     add r0.w, r0.w, r2.w
 488:   endif 

#line 130
 489:   ineg r2.w, r0.z
 490:   ilt r2.w, l(1), r2.w
 491:   ilt r5.x, r0.z, l(1)
 492:   or r2.w, r2.w, r5.x
 493:   if_nz r2.w

#line 131
 494:     iadd r5.x, l(1), l(1)  // r5.x <- i
 495:   else 
 496:     mov r5.x, l(1)  // r5.x <- i
 497:   endif 

#line 133
 498:   if_z r2.w
 499:     iadd r2.w, r0.x, r2.x
 500:     imul null, r2.w, r2.w, l(7)
 501:     iadd r5.y, r0.x, r5.x
 502:     iadd r2.w, r2.w, r5.y  // r2.w <- wi

#line 134
 503:     mov r2.w, x0[r2.w + 0].x  // r2.w <- wS

#line 136
 504:     nop 
 505:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 506:     iadd r5.y, r2.x, r2.z  // r5.y <- y

#line 22
 507:     imul null, r5.y, r5.y, l(22)
 508:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 509:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 510:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 511:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 512:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 513:     mov r5.xyz, -r6.xyzx
 514:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 515:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 516:     mov r5.x, -r5.x
 517:     mul r5.x, r1.w, r5.x
 518:     mul r5.x, r5.x, l(1.442695)
 519:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 520:     mul r2.w, r2.w, r5.x  // r2.w <- w

#line 144
 521:     mul r5.xyzw, r2.wwww, r6.xyzw
 522:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 523:     add r0.w, r0.w, r2.w
 524:   endif 

#line 130
 525:   ineg r2.w, r0.z
 526:   ilt r2.w, l(2), r2.w
 527:   ilt r5.x, r0.z, l(2)
 528:   or r2.w, r2.w, r5.x
 529:   if_nz r2.w

#line 131
 530:     iadd r5.x, l(1), l(2)  // r5.x <- i
 531:   else 
 532:     mov r5.x, l(2)  // r5.x <- i
 533:   endif 

#line 133
 534:   if_z r2.w
 535:     iadd r2.w, r0.x, r2.x
 536:     imul null, r2.w, r2.w, l(7)
 537:     iadd r5.y, r0.x, r5.x
 538:     iadd r2.w, r2.w, r5.y  // r2.w <- wi

#line 134
 539:     mov r2.w, x0[r2.w + 0].x  // r2.w <- wS

#line 136
 540:     nop 
 541:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 542:     iadd r5.y, r2.x, r2.z  // r5.y <- y

#line 22
 543:     imul null, r5.y, r5.y, l(22)
 544:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 545:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 546:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 547:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 548:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 549:     mov r5.xyz, -r6.xyzx
 550:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 551:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 552:     mov r5.x, -r5.x
 553:     mul r5.x, r1.w, r5.x
 554:     mul r5.x, r5.x, l(1.442695)
 555:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 556:     mul r2.w, r2.w, r5.x  // r2.w <- w

#line 144
 557:     mul r5.xyzw, r2.wwww, r6.xyzw
 558:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 559:     add r0.w, r0.w, r2.w
 560:   endif 

#line 130
 561:   ineg r2.w, r0.z
 562:   ilt r2.w, l(3), r2.w
 563:   ilt r5.x, r0.z, l(3)
 564:   or r2.w, r2.w, r5.x
 565:   if_nz r2.w

#line 131
 566:     iadd r5.x, l(1), l(3)  // r5.x <- i
 567:   else 
 568:     mov r5.x, l(3)  // r5.x <- i
 569:   endif 

#line 133
 570:   if_z r2.w
 571:     iadd r2.w, r0.x, r2.x
 572:     imul null, r2.w, r2.w, l(7)
 573:     iadd r5.y, r0.x, r5.x
 574:     iadd r2.w, r2.w, r5.y  // r2.w <- wi

#line 134
 575:     mov r2.w, x0[r2.w + 0].x  // r2.w <- wS

#line 136
 576:     nop 
 577:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 578:     iadd r2.x, r2.x, r2.z  // r2.x <- y

#line 22
 579:     imul null, r2.x, r2.x, l(22)
 580:     iadd r2.x, r5.x, r2.x  // r2.x <- <CacheIndex return value>

#line 136
 581:     ld_structured r5.x, r2.x, l(0), g0.xxxx  // r5.x <- s.x
 582:     ld_structured r5.y, r2.x, l(4), g0.xxxx  // r5.y <- s.y
 583:     ld_structured r5.z, r2.x, l(8), g0.xxxx  // r5.z <- s.z
 584:     ld_structured r5.w, r2.x, l(12), g0.xxxx  // r5.w <- s.w

#line 138
 585:     mov r6.xyz, -r5.xyzx
 586:     add r6.xyz, r1.xyzx, r6.xyzx  // r6.x <- diff.x; r6.y <- diff.y; r6.z <- diff.z

#line 139
 587:     dp3 r2.x, r6.xyzx, r6.xyzx  // r2.x <- d2

#line 140
 588:     mov r2.x, -r2.x
 589:     mul r2.x, r1.w, r2.x
 590:     mul r2.x, r2.x, l(1.442695)
 591:     exp r2.x, r2.x  // r2.x <- wR

#line 142
 592:     mul r2.x, r2.x, r2.w  // r2.x <- w

#line 144
 593:     mul r5.xyzw, r2.xxxx, r5.xyzw
 594:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 595:     add r0.w, r0.w, r2.x
 596:   endif 

#line 146
 597: endif 

#line 124
 598: ineg r2.x, r0.z
 599: ilt r2.x, l(-2), r2.x
 600: ilt r2.w, r0.z, l(-2)
 601: or r2.x, r2.w, r2.x
 602: if_nz r2.x

#line 125
 603:   iadd r2.w, l(1), l(-2)  // r2.w <- j
 604: else 
 605:   mov r2.w, l(-2)  // r2.w <- j
 606: endif 

#line 128
 607: if_z r2.x
 608:   mov r2.x, l(-3)  // r2.x <- i

#line 130
 609:   ineg r5.x, r0.z
 610:   ilt r5.x, r2.x, r5.x
 611:   ilt r5.y, r0.z, r2.x
 612:   or r5.x, r5.y, r5.x
 613:   if_nz r5.x

#line 131
 614:     iadd r2.x, r2.x, l(1)
 615:   endif 

#line 133
 616:   if_z r5.x
 617:     iadd r5.x, r0.x, r2.w
 618:     imul null, r5.x, r5.x, l(7)
 619:     iadd r5.y, r0.x, r2.x
 620:     iadd r5.x, r5.y, r5.x  // r5.x <- wi

#line 134
 621:     mov r5.x, x0[r5.x + 0].x  // r5.x <- wS

#line 136
 622:     nop 
 623:     iadd r2.x, r2.x, r2.y  // r2.x <- x
 624:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 625:     imul null, r5.y, r5.y, l(22)
 626:     iadd r2.x, r2.x, r5.y  // r2.x <- <CacheIndex return value>

#line 136
 627:     ld_structured r6.x, r2.x, l(0), g0.xxxx  // r6.x <- s.x
 628:     ld_structured r6.y, r2.x, l(4), g0.xxxx  // r6.y <- s.y
 629:     ld_structured r6.z, r2.x, l(8), g0.xxxx  // r6.z <- s.z
 630:     ld_structured r6.w, r2.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 631:     mov r5.yzw, -r6.xxyz
 632:     add r5.yzw, r1.xxyz, r5.yyzw  // r5.y <- diff.x; r5.z <- diff.y; r5.w <- diff.z

#line 139
 633:     dp3 r2.x, r5.yzwy, r5.yzwy  // r2.x <- d2

#line 140
 634:     mov r2.x, -r2.x
 635:     mul r2.x, r1.w, r2.x
 636:     mul r2.x, r2.x, l(1.442695)
 637:     exp r2.x, r2.x  // r2.x <- wR

#line 142
 638:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 639:     mul r5.xyzw, r2.xxxx, r6.xyzw
 640:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 641:     add r0.w, r0.w, r2.x
 642:   endif 

#line 130
 643:   ineg r2.x, r0.z
 644:   ilt r2.x, l(-2), r2.x
 645:   ilt r5.x, r0.z, l(-2)
 646:   or r2.x, r2.x, r5.x
 647:   if_nz r2.x

#line 131
 648:     iadd r5.x, l(1), l(-2)  // r5.x <- i
 649:   else 
 650:     mov r5.x, l(-2)  // r5.x <- i
 651:   endif 

#line 133
 652:   if_z r2.x
 653:     iadd r2.x, r0.x, r2.w
 654:     imul null, r2.x, r2.x, l(7)
 655:     iadd r5.y, r0.x, r5.x
 656:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 657:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 658:     nop 
 659:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 660:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 661:     imul null, r5.y, r5.y, l(22)
 662:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 663:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 664:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 665:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 666:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 667:     mov r5.xyz, -r6.xyzx
 668:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 669:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 670:     mov r5.x, -r5.x
 671:     mul r5.x, r1.w, r5.x
 672:     mul r5.x, r5.x, l(1.442695)
 673:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 674:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 675:     mul r5.xyzw, r2.xxxx, r6.xyzw
 676:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 677:     add r0.w, r0.w, r2.x
 678:   endif 

#line 130
 679:   ineg r2.x, r0.z
 680:   ilt r2.x, l(-1), r2.x
 681:   ilt r5.x, r0.z, l(-1)
 682:   or r2.x, r2.x, r5.x
 683:   not r5.x, r2.x  // r5.x <- i

#line 133
 684:   if_z r2.x
 685:     iadd r2.x, r0.x, r2.w
 686:     imul null, r2.x, r2.x, l(7)
 687:     iadd r5.y, r0.x, r5.x
 688:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 689:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 690:     nop 
 691:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 692:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 693:     imul null, r5.y, r5.y, l(22)
 694:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 695:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 696:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 697:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 698:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 699:     mov r5.xyz, -r6.xyzx
 700:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 701:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 702:     mov r5.x, -r5.x
 703:     mul r5.x, r1.w, r5.x
 704:     mul r5.x, r5.x, l(1.442695)
 705:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 706:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 707:     mul r5.xyzw, r2.xxxx, r6.xyzw
 708:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 709:     add r0.w, r0.w, r2.x
 710:   endif 

#line 130
 711:   ineg r2.x, r0.z
 712:   ilt r2.x, l(0), r2.x
 713:   ilt r5.x, r0.z, l(0)
 714:   or r2.x, r2.x, r5.x
 715:   if_nz r2.x

#line 131
 716:     iadd r5.x, l(1), l(0)  // r5.x <- i
 717:   else 
 718:     mov r5.x, l(0)  // r5.x <- i
 719:   endif 

#line 133
 720:   if_z r2.x
 721:     iadd r2.x, r0.x, r2.w
 722:     imul null, r2.x, r2.x, l(7)
 723:     iadd r5.y, r0.x, r5.x
 724:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 725:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 726:     nop 
 727:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 728:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 729:     imul null, r5.y, r5.y, l(22)
 730:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 731:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 732:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 733:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 734:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 735:     mov r5.xyz, -r6.xyzx
 736:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 737:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 738:     mov r5.x, -r5.x
 739:     mul r5.x, r1.w, r5.x
 740:     mul r5.x, r5.x, l(1.442695)
 741:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 742:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 743:     mul r5.xyzw, r2.xxxx, r6.xyzw
 744:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 745:     add r0.w, r0.w, r2.x
 746:   endif 

#line 130
 747:   ineg r2.x, r0.z
 748:   ilt r2.x, l(1), r2.x
 749:   ilt r5.x, r0.z, l(1)
 750:   or r2.x, r2.x, r5.x
 751:   if_nz r2.x

#line 131
 752:     iadd r5.x, l(1), l(1)  // r5.x <- i
 753:   else 
 754:     mov r5.x, l(1)  // r5.x <- i
 755:   endif 

#line 133
 756:   if_z r2.x
 757:     iadd r2.x, r0.x, r2.w
 758:     imul null, r2.x, r2.x, l(7)
 759:     iadd r5.y, r0.x, r5.x
 760:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 761:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 762:     nop 
 763:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 764:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 765:     imul null, r5.y, r5.y, l(22)
 766:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 767:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 768:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 769:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 770:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 771:     mov r5.xyz, -r6.xyzx
 772:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 773:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 774:     mov r5.x, -r5.x
 775:     mul r5.x, r1.w, r5.x
 776:     mul r5.x, r5.x, l(1.442695)
 777:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 778:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 779:     mul r5.xyzw, r2.xxxx, r6.xyzw
 780:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 781:     add r0.w, r0.w, r2.x
 782:   endif 

#line 130
 783:   ineg r2.x, r0.z
 784:   ilt r2.x, l(2), r2.x
 785:   ilt r5.x, r0.z, l(2)
 786:   or r2.x, r2.x, r5.x
 787:   if_nz r2.x

#line 131
 788:     iadd r5.x, l(1), l(2)  // r5.x <- i
 789:   else 
 790:     mov r5.x, l(2)  // r5.x <- i
 791:   endif 

#line 133
 792:   if_z r2.x
 793:     iadd r2.x, r0.x, r2.w
 794:     imul null, r2.x, r2.x, l(7)
 795:     iadd r5.y, r0.x, r5.x
 796:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 797:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 798:     nop 
 799:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 800:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 801:     imul null, r5.y, r5.y, l(22)
 802:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 803:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 804:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 805:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 806:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 807:     mov r5.xyz, -r6.xyzx
 808:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 809:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 810:     mov r5.x, -r5.x
 811:     mul r5.x, r1.w, r5.x
 812:     mul r5.x, r5.x, l(1.442695)
 813:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 814:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 815:     mul r5.xyzw, r2.xxxx, r6.xyzw
 816:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 817:     add r0.w, r0.w, r2.x
 818:   endif 

#line 130
 819:   ineg r2.x, r0.z
 820:   ilt r2.x, l(3), r2.x
 821:   ilt r5.x, r0.z, l(3)
 822:   or r2.x, r2.x, r5.x
 823:   if_nz r2.x

#line 131
 824:     iadd r5.x, l(1), l(3)  // r5.x <- i
 825:   else 
 826:     mov r5.x, l(3)  // r5.x <- i
 827:   endif 

#line 133
 828:   if_z r2.x
 829:     iadd r2.x, r0.x, r2.w
 830:     imul null, r2.x, r2.x, l(7)
 831:     iadd r5.y, r0.x, r5.x
 832:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 833:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 834:     nop 
 835:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 836:     iadd r2.w, r2.w, r2.z  // r2.w <- y

#line 22
 837:     imul null, r2.w, r2.w, l(22)
 838:     iadd r2.w, r5.x, r2.w  // r2.w <- <CacheIndex return value>

#line 136
 839:     ld_structured r5.x, r2.w, l(0), g0.xxxx  // r5.x <- s.x
 840:     ld_structured r5.y, r2.w, l(4), g0.xxxx  // r5.y <- s.y
 841:     ld_structured r5.z, r2.w, l(8), g0.xxxx  // r5.z <- s.z
 842:     ld_structured r5.w, r2.w, l(12), g0.xxxx  // r5.w <- s.w

#line 138
 843:     mov r6.xyz, -r5.xyzx
 844:     add r6.xyz, r1.xyzx, r6.xyzx  // r6.x <- diff.x; r6.y <- diff.y; r6.z <- diff.z

#line 139
 845:     dp3 r2.w, r6.xyzx, r6.xyzx  // r2.w <- d2

#line 140
 846:     mov r2.w, -r2.w
 847:     mul r2.w, r1.w, r2.w
 848:     mul r2.w, r2.w, l(1.442695)
 849:     exp r2.w, r2.w  // r2.w <- wR

#line 142
 850:     mul r2.x, r2.w, r2.x  // r2.x <- w

#line 144
 851:     mul r5.xyzw, r2.xxxx, r5.xyzw
 852:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 853:     add r0.w, r0.w, r2.x
 854:   endif 

#line 146
 855: endif 

#line 124
 856: ineg r2.x, r0.z
 857: ilt r2.x, l(-1), r2.x
 858: ilt r2.w, r0.z, l(-1)
 859: or r2.x, r2.w, r2.x
 860: not r2.w, r2.x  // r2.w <- j

#line 128
 861: if_z r2.x
 862:   mov r2.x, l(-3)  // r2.x <- i

#line 130
 863:   ineg r5.x, r0.z
 864:   ilt r5.x, r2.x, r5.x
 865:   ilt r5.y, r0.z, r2.x
 866:   or r5.x, r5.y, r5.x
 867:   if_nz r5.x

#line 131
 868:     iadd r2.x, r2.x, l(1)
 869:   endif 

#line 133
 870:   if_z r5.x
 871:     iadd r5.x, r0.x, r2.w
 872:     imul null, r5.x, r5.x, l(7)
 873:     iadd r5.y, r0.x, r2.x
 874:     iadd r5.x, r5.y, r5.x  // r5.x <- wi

#line 134
 875:     mov r5.x, x0[r5.x + 0].x  // r5.x <- wS

#line 136
 876:     nop 
 877:     iadd r2.x, r2.x, r2.y  // r2.x <- x
 878:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 879:     imul null, r5.y, r5.y, l(22)
 880:     iadd r2.x, r2.x, r5.y  // r2.x <- <CacheIndex return value>

#line 136
 881:     ld_structured r6.x, r2.x, l(0), g0.xxxx  // r6.x <- s.x
 882:     ld_structured r6.y, r2.x, l(4), g0.xxxx  // r6.y <- s.y
 883:     ld_structured r6.z, r2.x, l(8), g0.xxxx  // r6.z <- s.z
 884:     ld_structured r6.w, r2.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 885:     mov r5.yzw, -r6.xxyz
 886:     add r5.yzw, r1.xxyz, r5.yyzw  // r5.y <- diff.x; r5.z <- diff.y; r5.w <- diff.z

#line 139
 887:     dp3 r2.x, r5.yzwy, r5.yzwy  // r2.x <- d2

#line 140
 888:     mov r2.x, -r2.x
 889:     mul r2.x, r1.w, r2.x
 890:     mul r2.x, r2.x, l(1.442695)
 891:     exp r2.x, r2.x  // r2.x <- wR

#line 142
 892:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 893:     mul r5.xyzw, r2.xxxx, r6.xyzw
 894:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 895:     add r0.w, r0.w, r2.x
 896:   endif 

#line 130
 897:   ineg r2.x, r0.z
 898:   ilt r2.x, l(-2), r2.x
 899:   ilt r5.x, r0.z, l(-2)
 900:   or r2.x, r2.x, r5.x
 901:   if_nz r2.x

#line 131
 902:     iadd r5.x, l(1), l(-2)  // r5.x <- i
 903:   else 
 904:     mov r5.x, l(-2)  // r5.x <- i
 905:   endif 

#line 133
 906:   if_z r2.x
 907:     iadd r2.x, r0.x, r2.w
 908:     imul null, r2.x, r2.x, l(7)
 909:     iadd r5.y, r0.x, r5.x
 910:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 911:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 912:     nop 
 913:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 914:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 915:     imul null, r5.y, r5.y, l(22)
 916:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 917:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 918:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 919:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 920:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 921:     mov r5.xyz, -r6.xyzx
 922:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 923:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 924:     mov r5.x, -r5.x
 925:     mul r5.x, r1.w, r5.x
 926:     mul r5.x, r5.x, l(1.442695)
 927:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 928:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 929:     mul r5.xyzw, r2.xxxx, r6.xyzw
 930:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 931:     add r0.w, r0.w, r2.x
 932:   endif 

#line 130
 933:   ineg r2.x, r0.z
 934:   ilt r2.x, l(-1), r2.x
 935:   ilt r5.x, r0.z, l(-1)
 936:   or r2.x, r2.x, r5.x
 937:   not r5.x, r2.x  // r5.x <- i

#line 133
 938:   if_z r2.x
 939:     iadd r2.x, r0.x, r2.w
 940:     imul null, r2.x, r2.x, l(7)
 941:     iadd r5.y, r0.x, r5.x
 942:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 943:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 944:     nop 
 945:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 946:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 947:     imul null, r5.y, r5.y, l(22)
 948:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 949:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 950:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 951:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 952:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 953:     mov r5.xyz, -r6.xyzx
 954:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 955:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 956:     mov r5.x, -r5.x
 957:     mul r5.x, r1.w, r5.x
 958:     mul r5.x, r5.x, l(1.442695)
 959:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 960:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 961:     mul r5.xyzw, r2.xxxx, r6.xyzw
 962:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 963:     add r0.w, r0.w, r2.x
 964:   endif 

#line 130
 965:   ineg r2.x, r0.z
 966:   ilt r2.x, l(0), r2.x
 967:   ilt r5.x, r0.z, l(0)
 968:   or r2.x, r2.x, r5.x
 969:   if_nz r2.x

#line 131
 970:     iadd r5.x, l(1), l(0)  // r5.x <- i
 971:   else 
 972:     mov r5.x, l(0)  // r5.x <- i
 973:   endif 

#line 133
 974:   if_z r2.x
 975:     iadd r2.x, r0.x, r2.w
 976:     imul null, r2.x, r2.x, l(7)
 977:     iadd r5.y, r0.x, r5.x
 978:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
 979:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
 980:     nop 
 981:     iadd r5.x, r2.y, r5.x  // r5.x <- x
 982:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
 983:     imul null, r5.y, r5.y, l(22)
 984:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
 985:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
 986:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
 987:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
 988:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
 989:     mov r5.xyz, -r6.xyzx
 990:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
 991:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
 992:     mov r5.x, -r5.x
 993:     mul r5.x, r1.w, r5.x
 994:     mul r5.x, r5.x, l(1.442695)
 995:     exp r5.x, r5.x  // r5.x <- wR

#line 142
 996:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
 997:     mul r5.xyzw, r2.xxxx, r6.xyzw
 998:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
 999:     add r0.w, r0.w, r2.x
1000:   endif 

#line 130
1001:   ineg r2.x, r0.z
1002:   ilt r2.x, l(1), r2.x
1003:   ilt r5.x, r0.z, l(1)
1004:   or r2.x, r2.x, r5.x
1005:   if_nz r2.x

#line 131
1006:     iadd r5.x, l(1), l(1)  // r5.x <- i
1007:   else 
1008:     mov r5.x, l(1)  // r5.x <- i
1009:   endif 

#line 133
1010:   if_z r2.x
1011:     iadd r2.x, r0.x, r2.w
1012:     imul null, r2.x, r2.x, l(7)
1013:     iadd r5.y, r0.x, r5.x
1014:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1015:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1016:     nop 
1017:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1018:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1019:     imul null, r5.y, r5.y, l(22)
1020:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1021:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1022:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1023:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1024:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1025:     mov r5.xyz, -r6.xyzx
1026:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1027:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1028:     mov r5.x, -r5.x
1029:     mul r5.x, r1.w, r5.x
1030:     mul r5.x, r5.x, l(1.442695)
1031:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1032:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1033:     mul r5.xyzw, r2.xxxx, r6.xyzw
1034:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1035:     add r0.w, r0.w, r2.x
1036:   endif 

#line 130
1037:   ineg r2.x, r0.z
1038:   ilt r2.x, l(2), r2.x
1039:   ilt r5.x, r0.z, l(2)
1040:   or r2.x, r2.x, r5.x
1041:   if_nz r2.x

#line 131
1042:     iadd r5.x, l(1), l(2)  // r5.x <- i
1043:   else 
1044:     mov r5.x, l(2)  // r5.x <- i
1045:   endif 

#line 133
1046:   if_z r2.x
1047:     iadd r2.x, r0.x, r2.w
1048:     imul null, r2.x, r2.x, l(7)
1049:     iadd r5.y, r0.x, r5.x
1050:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1051:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1052:     nop 
1053:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1054:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1055:     imul null, r5.y, r5.y, l(22)
1056:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1057:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1058:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1059:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1060:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1061:     mov r5.xyz, -r6.xyzx
1062:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1063:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1064:     mov r5.x, -r5.x
1065:     mul r5.x, r1.w, r5.x
1066:     mul r5.x, r5.x, l(1.442695)
1067:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1068:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1069:     mul r5.xyzw, r2.xxxx, r6.xyzw
1070:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1071:     add r0.w, r0.w, r2.x
1072:   endif 

#line 130
1073:   ineg r2.x, r0.z
1074:   ilt r2.x, l(3), r2.x
1075:   ilt r5.x, r0.z, l(3)
1076:   or r2.x, r2.x, r5.x
1077:   if_nz r2.x

#line 131
1078:     iadd r5.x, l(1), l(3)  // r5.x <- i
1079:   else 
1080:     mov r5.x, l(3)  // r5.x <- i
1081:   endif 

#line 133
1082:   if_z r2.x
1083:     iadd r2.x, r0.x, r2.w
1084:     imul null, r2.x, r2.x, l(7)
1085:     iadd r5.y, r0.x, r5.x
1086:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1087:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1088:     nop 
1089:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1090:     iadd r2.w, r2.w, r2.z  // r2.w <- y

#line 22
1091:     imul null, r2.w, r2.w, l(22)
1092:     iadd r2.w, r5.x, r2.w  // r2.w <- <CacheIndex return value>

#line 136
1093:     ld_structured r5.x, r2.w, l(0), g0.xxxx  // r5.x <- s.x
1094:     ld_structured r5.y, r2.w, l(4), g0.xxxx  // r5.y <- s.y
1095:     ld_structured r5.z, r2.w, l(8), g0.xxxx  // r5.z <- s.z
1096:     ld_structured r5.w, r2.w, l(12), g0.xxxx  // r5.w <- s.w

#line 138
1097:     mov r6.xyz, -r5.xyzx
1098:     add r6.xyz, r1.xyzx, r6.xyzx  // r6.x <- diff.x; r6.y <- diff.y; r6.z <- diff.z

#line 139
1099:     dp3 r2.w, r6.xyzx, r6.xyzx  // r2.w <- d2

#line 140
1100:     mov r2.w, -r2.w
1101:     mul r2.w, r1.w, r2.w
1102:     mul r2.w, r2.w, l(1.442695)
1103:     exp r2.w, r2.w  // r2.w <- wR

#line 142
1104:     mul r2.x, r2.w, r2.x  // r2.x <- w

#line 144
1105:     mul r5.xyzw, r2.xxxx, r5.xyzw
1106:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1107:     add r0.w, r0.w, r2.x
1108:   endif 

#line 146
1109: endif 

#line 124
1110: ineg r2.x, r0.z
1111: ilt r2.x, l(0), r2.x
1112: ilt r2.w, r0.z, l(0)
1113: or r2.x, r2.w, r2.x
1114: if_nz r2.x

#line 125
1115:   iadd r2.w, l(1), l(0)  // r2.w <- j
1116: else 
1117:   mov r2.w, l(0)  // r2.w <- j
1118: endif 

#line 128
1119: if_z r2.x
1120:   mov r2.x, l(-3)  // r2.x <- i

#line 130
1121:   ineg r5.x, r0.z
1122:   ilt r5.x, r2.x, r5.x
1123:   ilt r5.y, r0.z, r2.x
1124:   or r5.x, r5.y, r5.x
1125:   if_nz r5.x

#line 131
1126:     iadd r2.x, r2.x, l(1)
1127:   endif 

#line 133
1128:   if_z r5.x
1129:     iadd r5.x, r0.x, r2.w
1130:     imul null, r5.x, r5.x, l(7)
1131:     iadd r5.y, r0.x, r2.x
1132:     iadd r5.x, r5.y, r5.x  // r5.x <- wi

#line 134
1133:     mov r5.x, x0[r5.x + 0].x  // r5.x <- wS

#line 136
1134:     nop 
1135:     iadd r2.x, r2.x, r2.y  // r2.x <- x
1136:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1137:     imul null, r5.y, r5.y, l(22)
1138:     iadd r2.x, r2.x, r5.y  // r2.x <- <CacheIndex return value>

#line 136
1139:     ld_structured r6.x, r2.x, l(0), g0.xxxx  // r6.x <- s.x
1140:     ld_structured r6.y, r2.x, l(4), g0.xxxx  // r6.y <- s.y
1141:     ld_structured r6.z, r2.x, l(8), g0.xxxx  // r6.z <- s.z
1142:     ld_structured r6.w, r2.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1143:     mov r5.yzw, -r6.xxyz
1144:     add r5.yzw, r1.xxyz, r5.yyzw  // r5.y <- diff.x; r5.z <- diff.y; r5.w <- diff.z

#line 139
1145:     dp3 r2.x, r5.yzwy, r5.yzwy  // r2.x <- d2

#line 140
1146:     mov r2.x, -r2.x
1147:     mul r2.x, r1.w, r2.x
1148:     mul r2.x, r2.x, l(1.442695)
1149:     exp r2.x, r2.x  // r2.x <- wR

#line 142
1150:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1151:     mul r5.xyzw, r2.xxxx, r6.xyzw
1152:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1153:     add r0.w, r0.w, r2.x
1154:   endif 

#line 130
1155:   ineg r2.x, r0.z
1156:   ilt r2.x, l(-2), r2.x
1157:   ilt r5.x, r0.z, l(-2)
1158:   or r2.x, r2.x, r5.x
1159:   if_nz r2.x

#line 131
1160:     iadd r5.x, l(1), l(-2)  // r5.x <- i
1161:   else 
1162:     mov r5.x, l(-2)  // r5.x <- i
1163:   endif 

#line 133
1164:   if_z r2.x
1165:     iadd r2.x, r0.x, r2.w
1166:     imul null, r2.x, r2.x, l(7)
1167:     iadd r5.y, r0.x, r5.x
1168:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1169:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1170:     nop 
1171:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1172:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1173:     imul null, r5.y, r5.y, l(22)
1174:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1175:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1176:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1177:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1178:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1179:     mov r5.xyz, -r6.xyzx
1180:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1181:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1182:     mov r5.x, -r5.x
1183:     mul r5.x, r1.w, r5.x
1184:     mul r5.x, r5.x, l(1.442695)
1185:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1186:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1187:     mul r5.xyzw, r2.xxxx, r6.xyzw
1188:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1189:     add r0.w, r0.w, r2.x
1190:   endif 

#line 130
1191:   ineg r2.x, r0.z
1192:   ilt r2.x, l(-1), r2.x
1193:   ilt r5.x, r0.z, l(-1)
1194:   or r2.x, r2.x, r5.x
1195:   not r5.x, r2.x  // r5.x <- i

#line 133
1196:   if_z r2.x
1197:     iadd r2.x, r0.x, r2.w
1198:     imul null, r2.x, r2.x, l(7)
1199:     iadd r5.y, r0.x, r5.x
1200:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1201:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1202:     nop 
1203:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1204:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1205:     imul null, r5.y, r5.y, l(22)
1206:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1207:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1208:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1209:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1210:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1211:     mov r5.xyz, -r6.xyzx
1212:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1213:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1214:     mov r5.x, -r5.x
1215:     mul r5.x, r1.w, r5.x
1216:     mul r5.x, r5.x, l(1.442695)
1217:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1218:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1219:     mul r5.xyzw, r2.xxxx, r6.xyzw
1220:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1221:     add r0.w, r0.w, r2.x
1222:   endif 

#line 130
1223:   ineg r2.x, r0.z
1224:   ilt r2.x, l(0), r2.x
1225:   ilt r5.x, r0.z, l(0)
1226:   or r2.x, r2.x, r5.x
1227:   if_nz r2.x

#line 131
1228:     iadd r5.x, l(1), l(0)  // r5.x <- i
1229:   else 
1230:     mov r5.x, l(0)  // r5.x <- i
1231:   endif 

#line 133
1232:   if_z r2.x
1233:     iadd r2.x, r0.x, r2.w
1234:     imul null, r2.x, r2.x, l(7)
1235:     iadd r5.y, r0.x, r5.x
1236:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1237:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1238:     nop 
1239:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1240:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1241:     imul null, r5.y, r5.y, l(22)
1242:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1243:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1244:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1245:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1246:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1247:     mov r5.xyz, -r6.xyzx
1248:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1249:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1250:     mov r5.x, -r5.x
1251:     mul r5.x, r1.w, r5.x
1252:     mul r5.x, r5.x, l(1.442695)
1253:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1254:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1255:     mul r5.xyzw, r2.xxxx, r6.xyzw
1256:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1257:     add r0.w, r0.w, r2.x
1258:   endif 

#line 130
1259:   ineg r2.x, r0.z
1260:   ilt r2.x, l(1), r2.x
1261:   ilt r5.x, r0.z, l(1)
1262:   or r2.x, r2.x, r5.x
1263:   if_nz r2.x

#line 131
1264:     iadd r5.x, l(1), l(1)  // r5.x <- i
1265:   else 
1266:     mov r5.x, l(1)  // r5.x <- i
1267:   endif 

#line 133
1268:   if_z r2.x
1269:     iadd r2.x, r0.x, r2.w
1270:     imul null, r2.x, r2.x, l(7)
1271:     iadd r5.y, r0.x, r5.x
1272:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1273:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1274:     nop 
1275:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1276:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1277:     imul null, r5.y, r5.y, l(22)
1278:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1279:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1280:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1281:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1282:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1283:     mov r5.xyz, -r6.xyzx
1284:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1285:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1286:     mov r5.x, -r5.x
1287:     mul r5.x, r1.w, r5.x
1288:     mul r5.x, r5.x, l(1.442695)
1289:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1290:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1291:     mul r5.xyzw, r2.xxxx, r6.xyzw
1292:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1293:     add r0.w, r0.w, r2.x
1294:   endif 

#line 130
1295:   ineg r2.x, r0.z
1296:   ilt r2.x, l(2), r2.x
1297:   ilt r5.x, r0.z, l(2)
1298:   or r2.x, r2.x, r5.x
1299:   if_nz r2.x

#line 131
1300:     iadd r5.x, l(1), l(2)  // r5.x <- i
1301:   else 
1302:     mov r5.x, l(2)  // r5.x <- i
1303:   endif 

#line 133
1304:   if_z r2.x
1305:     iadd r2.x, r0.x, r2.w
1306:     imul null, r2.x, r2.x, l(7)
1307:     iadd r5.y, r0.x, r5.x
1308:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1309:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1310:     nop 
1311:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1312:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1313:     imul null, r5.y, r5.y, l(22)
1314:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1315:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1316:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1317:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1318:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1319:     mov r5.xyz, -r6.xyzx
1320:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1321:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1322:     mov r5.x, -r5.x
1323:     mul r5.x, r1.w, r5.x
1324:     mul r5.x, r5.x, l(1.442695)
1325:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1326:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1327:     mul r5.xyzw, r2.xxxx, r6.xyzw
1328:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1329:     add r0.w, r0.w, r2.x
1330:   endif 

#line 130
1331:   ineg r2.x, r0.z
1332:   ilt r2.x, l(3), r2.x
1333:   ilt r5.x, r0.z, l(3)
1334:   or r2.x, r2.x, r5.x
1335:   if_nz r2.x

#line 131
1336:     iadd r5.x, l(1), l(3)  // r5.x <- i
1337:   else 
1338:     mov r5.x, l(3)  // r5.x <- i
1339:   endif 

#line 133
1340:   if_z r2.x
1341:     iadd r2.x, r0.x, r2.w
1342:     imul null, r2.x, r2.x, l(7)
1343:     iadd r5.y, r0.x, r5.x
1344:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1345:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1346:     nop 
1347:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1348:     iadd r2.w, r2.w, r2.z  // r2.w <- y

#line 22
1349:     imul null, r2.w, r2.w, l(22)
1350:     iadd r2.w, r5.x, r2.w  // r2.w <- <CacheIndex return value>

#line 136
1351:     ld_structured r5.x, r2.w, l(0), g0.xxxx  // r5.x <- s.x
1352:     ld_structured r5.y, r2.w, l(4), g0.xxxx  // r5.y <- s.y
1353:     ld_structured r5.z, r2.w, l(8), g0.xxxx  // r5.z <- s.z
1354:     ld_structured r5.w, r2.w, l(12), g0.xxxx  // r5.w <- s.w

#line 138
1355:     mov r6.xyz, -r5.xyzx
1356:     add r6.xyz, r1.xyzx, r6.xyzx  // r6.x <- diff.x; r6.y <- diff.y; r6.z <- diff.z

#line 139
1357:     dp3 r2.w, r6.xyzx, r6.xyzx  // r2.w <- d2

#line 140
1358:     mov r2.w, -r2.w
1359:     mul r2.w, r1.w, r2.w
1360:     mul r2.w, r2.w, l(1.442695)
1361:     exp r2.w, r2.w  // r2.w <- wR

#line 142
1362:     mul r2.x, r2.w, r2.x  // r2.x <- w

#line 144
1363:     mul r5.xyzw, r2.xxxx, r5.xyzw
1364:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1365:     add r0.w, r0.w, r2.x
1366:   endif 

#line 146
1367: endif 

#line 124
1368: ineg r2.x, r0.z
1369: ilt r2.x, l(1), r2.x
1370: ilt r2.w, r0.z, l(1)
1371: or r2.x, r2.w, r2.x
1372: if_nz r2.x

#line 125
1373:   iadd r2.w, l(1), l(1)  // r2.w <- j
1374: else 
1375:   mov r2.w, l(1)  // r2.w <- j
1376: endif 

#line 128
1377: if_z r2.x
1378:   mov r2.x, l(-3)  // r2.x <- i

#line 130
1379:   ineg r5.x, r0.z
1380:   ilt r5.x, r2.x, r5.x
1381:   ilt r5.y, r0.z, r2.x
1382:   or r5.x, r5.y, r5.x
1383:   if_nz r5.x

#line 131
1384:     iadd r2.x, r2.x, l(1)
1385:   endif 

#line 133
1386:   if_z r5.x
1387:     iadd r5.x, r0.x, r2.w
1388:     imul null, r5.x, r5.x, l(7)
1389:     iadd r5.y, r0.x, r2.x
1390:     iadd r5.x, r5.y, r5.x  // r5.x <- wi

#line 134
1391:     mov r5.x, x0[r5.x + 0].x  // r5.x <- wS

#line 136
1392:     nop 
1393:     iadd r2.x, r2.x, r2.y  // r2.x <- x
1394:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1395:     imul null, r5.y, r5.y, l(22)
1396:     iadd r2.x, r2.x, r5.y  // r2.x <- <CacheIndex return value>

#line 136
1397:     ld_structured r6.x, r2.x, l(0), g0.xxxx  // r6.x <- s.x
1398:     ld_structured r6.y, r2.x, l(4), g0.xxxx  // r6.y <- s.y
1399:     ld_structured r6.z, r2.x, l(8), g0.xxxx  // r6.z <- s.z
1400:     ld_structured r6.w, r2.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1401:     mov r5.yzw, -r6.xxyz
1402:     add r5.yzw, r1.xxyz, r5.yyzw  // r5.y <- diff.x; r5.z <- diff.y; r5.w <- diff.z

#line 139
1403:     dp3 r2.x, r5.yzwy, r5.yzwy  // r2.x <- d2

#line 140
1404:     mov r2.x, -r2.x
1405:     mul r2.x, r1.w, r2.x
1406:     mul r2.x, r2.x, l(1.442695)
1407:     exp r2.x, r2.x  // r2.x <- wR

#line 142
1408:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1409:     mul r5.xyzw, r2.xxxx, r6.xyzw
1410:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1411:     add r0.w, r0.w, r2.x
1412:   endif 

#line 130
1413:   ineg r2.x, r0.z
1414:   ilt r2.x, l(-2), r2.x
1415:   ilt r5.x, r0.z, l(-2)
1416:   or r2.x, r2.x, r5.x
1417:   if_nz r2.x

#line 131
1418:     iadd r5.x, l(1), l(-2)  // r5.x <- i
1419:   else 
1420:     mov r5.x, l(-2)  // r5.x <- i
1421:   endif 

#line 133
1422:   if_z r2.x
1423:     iadd r2.x, r0.x, r2.w
1424:     imul null, r2.x, r2.x, l(7)
1425:     iadd r5.y, r0.x, r5.x
1426:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1427:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1428:     nop 
1429:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1430:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1431:     imul null, r5.y, r5.y, l(22)
1432:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1433:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1434:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1435:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1436:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1437:     mov r5.xyz, -r6.xyzx
1438:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1439:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1440:     mov r5.x, -r5.x
1441:     mul r5.x, r1.w, r5.x
1442:     mul r5.x, r5.x, l(1.442695)
1443:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1444:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1445:     mul r5.xyzw, r2.xxxx, r6.xyzw
1446:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1447:     add r0.w, r0.w, r2.x
1448:   endif 

#line 130
1449:   ineg r2.x, r0.z
1450:   ilt r2.x, l(-1), r2.x
1451:   ilt r5.x, r0.z, l(-1)
1452:   or r2.x, r2.x, r5.x
1453:   not r5.x, r2.x  // r5.x <- i

#line 133
1454:   if_z r2.x
1455:     iadd r2.x, r0.x, r2.w
1456:     imul null, r2.x, r2.x, l(7)
1457:     iadd r5.y, r0.x, r5.x
1458:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1459:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1460:     nop 
1461:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1462:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1463:     imul null, r5.y, r5.y, l(22)
1464:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1465:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1466:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1467:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1468:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1469:     mov r5.xyz, -r6.xyzx
1470:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1471:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1472:     mov r5.x, -r5.x
1473:     mul r5.x, r1.w, r5.x
1474:     mul r5.x, r5.x, l(1.442695)
1475:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1476:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1477:     mul r5.xyzw, r2.xxxx, r6.xyzw
1478:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1479:     add r0.w, r0.w, r2.x
1480:   endif 

#line 130
1481:   ineg r2.x, r0.z
1482:   ilt r2.x, l(0), r2.x
1483:   ilt r5.x, r0.z, l(0)
1484:   or r2.x, r2.x, r5.x
1485:   if_nz r2.x

#line 131
1486:     iadd r5.x, l(1), l(0)  // r5.x <- i
1487:   else 
1488:     mov r5.x, l(0)  // r5.x <- i
1489:   endif 

#line 133
1490:   if_z r2.x
1491:     iadd r2.x, r0.x, r2.w
1492:     imul null, r2.x, r2.x, l(7)
1493:     iadd r5.y, r0.x, r5.x
1494:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1495:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1496:     nop 
1497:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1498:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1499:     imul null, r5.y, r5.y, l(22)
1500:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1501:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1502:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1503:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1504:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1505:     mov r5.xyz, -r6.xyzx
1506:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1507:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1508:     mov r5.x, -r5.x
1509:     mul r5.x, r1.w, r5.x
1510:     mul r5.x, r5.x, l(1.442695)
1511:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1512:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1513:     mul r5.xyzw, r2.xxxx, r6.xyzw
1514:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1515:     add r0.w, r0.w, r2.x
1516:   endif 

#line 130
1517:   ineg r2.x, r0.z
1518:   ilt r2.x, l(1), r2.x
1519:   ilt r5.x, r0.z, l(1)
1520:   or r2.x, r2.x, r5.x
1521:   if_nz r2.x

#line 131
1522:     iadd r5.x, l(1), l(1)  // r5.x <- i
1523:   else 
1524:     mov r5.x, l(1)  // r5.x <- i
1525:   endif 

#line 133
1526:   if_z r2.x
1527:     iadd r2.x, r0.x, r2.w
1528:     imul null, r2.x, r2.x, l(7)
1529:     iadd r5.y, r0.x, r5.x
1530:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1531:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1532:     nop 
1533:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1534:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1535:     imul null, r5.y, r5.y, l(22)
1536:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1537:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1538:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1539:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1540:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1541:     mov r5.xyz, -r6.xyzx
1542:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1543:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1544:     mov r5.x, -r5.x
1545:     mul r5.x, r1.w, r5.x
1546:     mul r5.x, r5.x, l(1.442695)
1547:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1548:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1549:     mul r5.xyzw, r2.xxxx, r6.xyzw
1550:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1551:     add r0.w, r0.w, r2.x
1552:   endif 

#line 130
1553:   ineg r2.x, r0.z
1554:   ilt r2.x, l(2), r2.x
1555:   ilt r5.x, r0.z, l(2)
1556:   or r2.x, r2.x, r5.x
1557:   if_nz r2.x

#line 131
1558:     iadd r5.x, l(1), l(2)  // r5.x <- i
1559:   else 
1560:     mov r5.x, l(2)  // r5.x <- i
1561:   endif 

#line 133
1562:   if_z r2.x
1563:     iadd r2.x, r0.x, r2.w
1564:     imul null, r2.x, r2.x, l(7)
1565:     iadd r5.y, r0.x, r5.x
1566:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1567:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1568:     nop 
1569:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1570:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1571:     imul null, r5.y, r5.y, l(22)
1572:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1573:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1574:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1575:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1576:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1577:     mov r5.xyz, -r6.xyzx
1578:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1579:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1580:     mov r5.x, -r5.x
1581:     mul r5.x, r1.w, r5.x
1582:     mul r5.x, r5.x, l(1.442695)
1583:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1584:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1585:     mul r5.xyzw, r2.xxxx, r6.xyzw
1586:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1587:     add r0.w, r0.w, r2.x
1588:   endif 

#line 130
1589:   ineg r2.x, r0.z
1590:   ilt r2.x, l(3), r2.x
1591:   ilt r5.x, r0.z, l(3)
1592:   or r2.x, r2.x, r5.x
1593:   if_nz r2.x

#line 131
1594:     iadd r5.x, l(1), l(3)  // r5.x <- i
1595:   else 
1596:     mov r5.x, l(3)  // r5.x <- i
1597:   endif 

#line 133
1598:   if_z r2.x
1599:     iadd r2.x, r0.x, r2.w
1600:     imul null, r2.x, r2.x, l(7)
1601:     iadd r5.y, r0.x, r5.x
1602:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1603:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1604:     nop 
1605:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1606:     iadd r2.w, r2.w, r2.z  // r2.w <- y

#line 22
1607:     imul null, r2.w, r2.w, l(22)
1608:     iadd r2.w, r5.x, r2.w  // r2.w <- <CacheIndex return value>

#line 136
1609:     ld_structured r5.x, r2.w, l(0), g0.xxxx  // r5.x <- s.x
1610:     ld_structured r5.y, r2.w, l(4), g0.xxxx  // r5.y <- s.y
1611:     ld_structured r5.z, r2.w, l(8), g0.xxxx  // r5.z <- s.z
1612:     ld_structured r5.w, r2.w, l(12), g0.xxxx  // r5.w <- s.w

#line 138
1613:     mov r6.xyz, -r5.xyzx
1614:     add r6.xyz, r1.xyzx, r6.xyzx  // r6.x <- diff.x; r6.y <- diff.y; r6.z <- diff.z

#line 139
1615:     dp3 r2.w, r6.xyzx, r6.xyzx  // r2.w <- d2

#line 140
1616:     mov r2.w, -r2.w
1617:     mul r2.w, r1.w, r2.w
1618:     mul r2.w, r2.w, l(1.442695)
1619:     exp r2.w, r2.w  // r2.w <- wR

#line 142
1620:     mul r2.x, r2.w, r2.x  // r2.x <- w

#line 144
1621:     mul r5.xyzw, r2.xxxx, r5.xyzw
1622:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1623:     add r0.w, r0.w, r2.x
1624:   endif 

#line 146
1625: endif 

#line 124
1626: ineg r2.x, r0.z
1627: ilt r2.x, l(2), r2.x
1628: ilt r2.w, r0.z, l(2)
1629: or r2.x, r2.w, r2.x
1630: if_nz r2.x

#line 125
1631:   iadd r2.w, l(1), l(2)  // r2.w <- j
1632: else 
1633:   mov r2.w, l(2)  // r2.w <- j
1634: endif 

#line 128
1635: if_z r2.x
1636:   mov r2.x, l(-3)  // r2.x <- i

#line 130
1637:   ineg r5.x, r0.z
1638:   ilt r5.x, r2.x, r5.x
1639:   ilt r5.y, r0.z, r2.x
1640:   or r5.x, r5.y, r5.x
1641:   if_nz r5.x

#line 131
1642:     iadd r2.x, r2.x, l(1)
1643:   endif 

#line 133
1644:   if_z r5.x
1645:     iadd r5.x, r0.x, r2.w
1646:     imul null, r5.x, r5.x, l(7)
1647:     iadd r5.y, r0.x, r2.x
1648:     iadd r5.x, r5.y, r5.x  // r5.x <- wi

#line 134
1649:     mov r5.x, x0[r5.x + 0].x  // r5.x <- wS

#line 136
1650:     nop 
1651:     iadd r2.x, r2.x, r2.y  // r2.x <- x
1652:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1653:     imul null, r5.y, r5.y, l(22)
1654:     iadd r2.x, r2.x, r5.y  // r2.x <- <CacheIndex return value>

#line 136
1655:     ld_structured r6.x, r2.x, l(0), g0.xxxx  // r6.x <- s.x
1656:     ld_structured r6.y, r2.x, l(4), g0.xxxx  // r6.y <- s.y
1657:     ld_structured r6.z, r2.x, l(8), g0.xxxx  // r6.z <- s.z
1658:     ld_structured r6.w, r2.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1659:     mov r5.yzw, -r6.xxyz
1660:     add r5.yzw, r1.xxyz, r5.yyzw  // r5.y <- diff.x; r5.z <- diff.y; r5.w <- diff.z

#line 139
1661:     dp3 r2.x, r5.yzwy, r5.yzwy  // r2.x <- d2

#line 140
1662:     mov r2.x, -r2.x
1663:     mul r2.x, r1.w, r2.x
1664:     mul r2.x, r2.x, l(1.442695)
1665:     exp r2.x, r2.x  // r2.x <- wR

#line 142
1666:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1667:     mul r5.xyzw, r2.xxxx, r6.xyzw
1668:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1669:     add r0.w, r0.w, r2.x
1670:   endif 

#line 130
1671:   ineg r2.x, r0.z
1672:   ilt r2.x, l(-2), r2.x
1673:   ilt r5.x, r0.z, l(-2)
1674:   or r2.x, r2.x, r5.x
1675:   if_nz r2.x

#line 131
1676:     iadd r5.x, l(1), l(-2)  // r5.x <- i
1677:   else 
1678:     mov r5.x, l(-2)  // r5.x <- i
1679:   endif 

#line 133
1680:   if_z r2.x
1681:     iadd r2.x, r0.x, r2.w
1682:     imul null, r2.x, r2.x, l(7)
1683:     iadd r5.y, r0.x, r5.x
1684:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1685:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1686:     nop 
1687:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1688:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1689:     imul null, r5.y, r5.y, l(22)
1690:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1691:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1692:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1693:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1694:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1695:     mov r5.xyz, -r6.xyzx
1696:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1697:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1698:     mov r5.x, -r5.x
1699:     mul r5.x, r1.w, r5.x
1700:     mul r5.x, r5.x, l(1.442695)
1701:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1702:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1703:     mul r5.xyzw, r2.xxxx, r6.xyzw
1704:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1705:     add r0.w, r0.w, r2.x
1706:   endif 

#line 130
1707:   ineg r2.x, r0.z
1708:   ilt r2.x, l(-1), r2.x
1709:   ilt r5.x, r0.z, l(-1)
1710:   or r2.x, r2.x, r5.x
1711:   not r5.x, r2.x  // r5.x <- i

#line 133
1712:   if_z r2.x
1713:     iadd r2.x, r0.x, r2.w
1714:     imul null, r2.x, r2.x, l(7)
1715:     iadd r5.y, r0.x, r5.x
1716:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1717:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1718:     nop 
1719:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1720:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1721:     imul null, r5.y, r5.y, l(22)
1722:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1723:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1724:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1725:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1726:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1727:     mov r5.xyz, -r6.xyzx
1728:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1729:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1730:     mov r5.x, -r5.x
1731:     mul r5.x, r1.w, r5.x
1732:     mul r5.x, r5.x, l(1.442695)
1733:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1734:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1735:     mul r5.xyzw, r2.xxxx, r6.xyzw
1736:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1737:     add r0.w, r0.w, r2.x
1738:   endif 

#line 130
1739:   ineg r2.x, r0.z
1740:   ilt r2.x, l(0), r2.x
1741:   ilt r5.x, r0.z, l(0)
1742:   or r2.x, r2.x, r5.x
1743:   if_nz r2.x

#line 131
1744:     iadd r5.x, l(1), l(0)  // r5.x <- i
1745:   else 
1746:     mov r5.x, l(0)  // r5.x <- i
1747:   endif 

#line 133
1748:   if_z r2.x
1749:     iadd r2.x, r0.x, r2.w
1750:     imul null, r2.x, r2.x, l(7)
1751:     iadd r5.y, r0.x, r5.x
1752:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1753:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1754:     nop 
1755:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1756:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1757:     imul null, r5.y, r5.y, l(22)
1758:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1759:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1760:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1761:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1762:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1763:     mov r5.xyz, -r6.xyzx
1764:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1765:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1766:     mov r5.x, -r5.x
1767:     mul r5.x, r1.w, r5.x
1768:     mul r5.x, r5.x, l(1.442695)
1769:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1770:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1771:     mul r5.xyzw, r2.xxxx, r6.xyzw
1772:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1773:     add r0.w, r0.w, r2.x
1774:   endif 

#line 130
1775:   ineg r2.x, r0.z
1776:   ilt r2.x, l(1), r2.x
1777:   ilt r5.x, r0.z, l(1)
1778:   or r2.x, r2.x, r5.x
1779:   if_nz r2.x

#line 131
1780:     iadd r5.x, l(1), l(1)  // r5.x <- i
1781:   else 
1782:     mov r5.x, l(1)  // r5.x <- i
1783:   endif 

#line 133
1784:   if_z r2.x
1785:     iadd r2.x, r0.x, r2.w
1786:     imul null, r2.x, r2.x, l(7)
1787:     iadd r5.y, r0.x, r5.x
1788:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1789:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1790:     nop 
1791:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1792:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1793:     imul null, r5.y, r5.y, l(22)
1794:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1795:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1796:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1797:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1798:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1799:     mov r5.xyz, -r6.xyzx
1800:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1801:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1802:     mov r5.x, -r5.x
1803:     mul r5.x, r1.w, r5.x
1804:     mul r5.x, r5.x, l(1.442695)
1805:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1806:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1807:     mul r5.xyzw, r2.xxxx, r6.xyzw
1808:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1809:     add r0.w, r0.w, r2.x
1810:   endif 

#line 130
1811:   ineg r2.x, r0.z
1812:   ilt r2.x, l(2), r2.x
1813:   ilt r5.x, r0.z, l(2)
1814:   or r2.x, r2.x, r5.x
1815:   if_nz r2.x

#line 131
1816:     iadd r5.x, l(1), l(2)  // r5.x <- i
1817:   else 
1818:     mov r5.x, l(2)  // r5.x <- i
1819:   endif 

#line 133
1820:   if_z r2.x
1821:     iadd r2.x, r0.x, r2.w
1822:     imul null, r2.x, r2.x, l(7)
1823:     iadd r5.y, r0.x, r5.x
1824:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1825:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1826:     nop 
1827:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1828:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1829:     imul null, r5.y, r5.y, l(22)
1830:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1831:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1832:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1833:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1834:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1835:     mov r5.xyz, -r6.xyzx
1836:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1837:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1838:     mov r5.x, -r5.x
1839:     mul r5.x, r1.w, r5.x
1840:     mul r5.x, r5.x, l(1.442695)
1841:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1842:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1843:     mul r5.xyzw, r2.xxxx, r6.xyzw
1844:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1845:     add r0.w, r0.w, r2.x
1846:   endif 

#line 130
1847:   ineg r2.x, r0.z
1848:   ilt r2.x, l(3), r2.x
1849:   ilt r5.x, r0.z, l(3)
1850:   or r2.x, r2.x, r5.x
1851:   if_nz r2.x

#line 131
1852:     iadd r5.x, l(1), l(3)  // r5.x <- i
1853:   else 
1854:     mov r5.x, l(3)  // r5.x <- i
1855:   endif 

#line 133
1856:   if_z r2.x
1857:     iadd r2.x, r0.x, r2.w
1858:     imul null, r2.x, r2.x, l(7)
1859:     iadd r5.y, r0.x, r5.x
1860:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1861:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1862:     nop 
1863:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1864:     iadd r2.w, r2.w, r2.z  // r2.w <- y

#line 22
1865:     imul null, r2.w, r2.w, l(22)
1866:     iadd r2.w, r5.x, r2.w  // r2.w <- <CacheIndex return value>

#line 136
1867:     ld_structured r5.x, r2.w, l(0), g0.xxxx  // r5.x <- s.x
1868:     ld_structured r5.y, r2.w, l(4), g0.xxxx  // r5.y <- s.y
1869:     ld_structured r5.z, r2.w, l(8), g0.xxxx  // r5.z <- s.z
1870:     ld_structured r5.w, r2.w, l(12), g0.xxxx  // r5.w <- s.w

#line 138
1871:     mov r6.xyz, -r5.xyzx
1872:     add r6.xyz, r1.xyzx, r6.xyzx  // r6.x <- diff.x; r6.y <- diff.y; r6.z <- diff.z

#line 139
1873:     dp3 r2.w, r6.xyzx, r6.xyzx  // r2.w <- d2

#line 140
1874:     mov r2.w, -r2.w
1875:     mul r2.w, r1.w, r2.w
1876:     mul r2.w, r2.w, l(1.442695)
1877:     exp r2.w, r2.w  // r2.w <- wR

#line 142
1878:     mul r2.x, r2.w, r2.x  // r2.x <- w

#line 144
1879:     mul r5.xyzw, r2.xxxx, r5.xyzw
1880:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1881:     add r0.w, r0.w, r2.x
1882:   endif 

#line 146
1883: endif 

#line 124
1884: ineg r2.x, r0.z
1885: ilt r2.x, l(3), r2.x
1886: ilt r2.w, r0.z, l(3)
1887: or r2.x, r2.w, r2.x
1888: if_nz r2.x

#line 125
1889:   iadd r2.w, l(1), l(3)  // r2.w <- j
1890: else 
1891:   mov r2.w, l(3)  // r2.w <- j
1892: endif 

#line 128
1893: if_z r2.x
1894:   mov r2.x, l(-3)  // r2.x <- i

#line 130
1895:   ineg r5.x, r0.z
1896:   ilt r5.x, r2.x, r5.x
1897:   ilt r5.y, r0.z, r2.x
1898:   or r5.x, r5.y, r5.x
1899:   if_nz r5.x

#line 131
1900:     iadd r2.x, r2.x, l(1)
1901:   endif 

#line 133
1902:   if_z r5.x
1903:     iadd r5.x, r0.x, r2.w
1904:     imul null, r5.x, r5.x, l(7)
1905:     iadd r5.y, r0.x, r2.x
1906:     iadd r5.x, r5.y, r5.x  // r5.x <- wi

#line 134
1907:     mov r5.x, x0[r5.x + 0].x  // r5.x <- wS

#line 136
1908:     nop 
1909:     iadd r2.x, r2.x, r2.y  // r2.x <- x
1910:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1911:     imul null, r5.y, r5.y, l(22)
1912:     iadd r2.x, r2.x, r5.y  // r2.x <- <CacheIndex return value>

#line 136
1913:     ld_structured r6.x, r2.x, l(0), g0.xxxx  // r6.x <- s.x
1914:     ld_structured r6.y, r2.x, l(4), g0.xxxx  // r6.y <- s.y
1915:     ld_structured r6.z, r2.x, l(8), g0.xxxx  // r6.z <- s.z
1916:     ld_structured r6.w, r2.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1917:     mov r5.yzw, -r6.xxyz
1918:     add r5.yzw, r1.xxyz, r5.yyzw  // r5.y <- diff.x; r5.z <- diff.y; r5.w <- diff.z

#line 139
1919:     dp3 r2.x, r5.yzwy, r5.yzwy  // r2.x <- d2

#line 140
1920:     mov r2.x, -r2.x
1921:     mul r2.x, r1.w, r2.x
1922:     mul r2.x, r2.x, l(1.442695)
1923:     exp r2.x, r2.x  // r2.x <- wR

#line 142
1924:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1925:     mul r5.xyzw, r2.xxxx, r6.xyzw
1926:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1927:     add r0.w, r0.w, r2.x
1928:   endif 

#line 130
1929:   ineg r2.x, r0.z
1930:   ilt r2.x, l(-2), r2.x
1931:   ilt r5.x, r0.z, l(-2)
1932:   or r2.x, r2.x, r5.x
1933:   if_nz r2.x

#line 131
1934:     iadd r5.x, l(1), l(-2)  // r5.x <- i
1935:   else 
1936:     mov r5.x, l(-2)  // r5.x <- i
1937:   endif 

#line 133
1938:   if_z r2.x
1939:     iadd r2.x, r0.x, r2.w
1940:     imul null, r2.x, r2.x, l(7)
1941:     iadd r5.y, r0.x, r5.x
1942:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1943:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1944:     nop 
1945:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1946:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1947:     imul null, r5.y, r5.y, l(22)
1948:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1949:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1950:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1951:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1952:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1953:     mov r5.xyz, -r6.xyzx
1954:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1955:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1956:     mov r5.x, -r5.x
1957:     mul r5.x, r1.w, r5.x
1958:     mul r5.x, r5.x, l(1.442695)
1959:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1960:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1961:     mul r5.xyzw, r2.xxxx, r6.xyzw
1962:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1963:     add r0.w, r0.w, r2.x
1964:   endif 

#line 130
1965:   ineg r2.x, r0.z
1966:   ilt r2.x, l(-1), r2.x
1967:   ilt r5.x, r0.z, l(-1)
1968:   or r2.x, r2.x, r5.x
1969:   not r5.x, r2.x  // r5.x <- i

#line 133
1970:   if_z r2.x
1971:     iadd r2.x, r0.x, r2.w
1972:     imul null, r2.x, r2.x, l(7)
1973:     iadd r5.y, r0.x, r5.x
1974:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
1975:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
1976:     nop 
1977:     iadd r5.x, r2.y, r5.x  // r5.x <- x
1978:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
1979:     imul null, r5.y, r5.y, l(22)
1980:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
1981:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
1982:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
1983:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
1984:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
1985:     mov r5.xyz, -r6.xyzx
1986:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
1987:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
1988:     mov r5.x, -r5.x
1989:     mul r5.x, r1.w, r5.x
1990:     mul r5.x, r5.x, l(1.442695)
1991:     exp r5.x, r5.x  // r5.x <- wR

#line 142
1992:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
1993:     mul r5.xyzw, r2.xxxx, r6.xyzw
1994:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
1995:     add r0.w, r0.w, r2.x
1996:   endif 

#line 130
1997:   ineg r2.x, r0.z
1998:   ilt r2.x, l(0), r2.x
1999:   ilt r5.x, r0.z, l(0)
2000:   or r2.x, r2.x, r5.x
2001:   if_nz r2.x

#line 131
2002:     iadd r5.x, l(1), l(0)  // r5.x <- i
2003:   else 
2004:     mov r5.x, l(0)  // r5.x <- i
2005:   endif 

#line 133
2006:   if_z r2.x
2007:     iadd r2.x, r0.x, r2.w
2008:     imul null, r2.x, r2.x, l(7)
2009:     iadd r5.y, r0.x, r5.x
2010:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
2011:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
2012:     nop 
2013:     iadd r5.x, r2.y, r5.x  // r5.x <- x
2014:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
2015:     imul null, r5.y, r5.y, l(22)
2016:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
2017:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
2018:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
2019:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
2020:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
2021:     mov r5.xyz, -r6.xyzx
2022:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
2023:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
2024:     mov r5.x, -r5.x
2025:     mul r5.x, r1.w, r5.x
2026:     mul r5.x, r5.x, l(1.442695)
2027:     exp r5.x, r5.x  // r5.x <- wR

#line 142
2028:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
2029:     mul r5.xyzw, r2.xxxx, r6.xyzw
2030:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
2031:     add r0.w, r0.w, r2.x
2032:   endif 

#line 130
2033:   ineg r2.x, r0.z
2034:   ilt r2.x, l(1), r2.x
2035:   ilt r5.x, r0.z, l(1)
2036:   or r2.x, r2.x, r5.x
2037:   if_nz r2.x

#line 131
2038:     iadd r5.x, l(1), l(1)  // r5.x <- i
2039:   else 
2040:     mov r5.x, l(1)  // r5.x <- i
2041:   endif 

#line 133
2042:   if_z r2.x
2043:     iadd r2.x, r0.x, r2.w
2044:     imul null, r2.x, r2.x, l(7)
2045:     iadd r5.y, r0.x, r5.x
2046:     iadd r2.x, r2.x, r5.y  // r2.x <- wi

#line 134
2047:     mov r2.x, x0[r2.x + 0].x  // r2.x <- wS

#line 136
2048:     nop 
2049:     iadd r5.x, r2.y, r5.x  // r5.x <- x
2050:     iadd r5.y, r2.w, r2.z  // r5.y <- y

#line 22
2051:     imul null, r5.y, r5.y, l(22)
2052:     iadd r5.x, r5.x, r5.y  // r5.x <- <CacheIndex return value>

#line 136
2053:     ld_structured r6.x, r5.x, l(0), g0.xxxx  // r6.x <- s.x
2054:     ld_structured r6.y, r5.x, l(4), g0.xxxx  // r6.y <- s.y
2055:     ld_structured r6.z, r5.x, l(8), g0.xxxx  // r6.z <- s.z
2056:     ld_structured r6.w, r5.x, l(12), g0.xxxx  // r6.w <- s.w

#line 138
2057:     mov r5.xyz, -r6.xyzx
2058:     add r5.xyz, r1.xyzx, r5.xyzx  // r5.x <- diff.x; r5.y <- diff.y; r5.z <- diff.z

#line 139
2059:     dp3 r5.x, r5.xyzx, r5.xyzx  // r5.x <- d2

#line 140
2060:     mov r5.x, -r5.x
2061:     mul r5.x, r1.w, r5.x
2062:     mul r5.x, r5.x, l(1.442695)
2063:     exp r5.x, r5.x  // r5.x <- wR

#line 142
2064:     mul r2.x, r2.x, r5.x  // r2.x <- w

#line 144
2065:     mul r5.xyzw, r2.xxxx, r6.xyzw
2066:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
2067:     add r0.w, r0.w, r2.x
2068:   endif 

#line 130
2069:   ineg r2.x, r0.z
2070:   ilt r2.x, l(2), r2.x
2071:   ilt r5.x, r0.z, l(2)
2072:   or r2.x, r2.x, r5.x
2073:   if_nz r2.x

#line 131
2074:     iadd r5.x, l(1), l(2)  // r5.x <- i
2075:   else 
2076:     mov r5.x, l(2)  // r5.x <- i
2077:   endif 

#line 133
2078:   if_z r2.x
2079:     iadd r2.x, r0.x, r2.w
2080:     imul null, r2.x, r2.x, l(7)
2081:     iadd r0.x, r0.x, r5.x
2082:     iadd r0.x, r0.x, r2.x  // r0.x <- wi

#line 134
2083:     mov r0.x, x0[r0.x + 0].x  // r0.x <- wS

#line 136
2084:     nop 
2085:     iadd r2.x, r2.y, r5.x  // r2.x <- x
2086:     iadd r5.x, r2.w, r2.z  // r5.x <- y

#line 22
2087:     imul null, r5.x, r5.x, l(22)
2088:     iadd r2.x, r2.x, r5.x  // r2.x <- <CacheIndex return value>

#line 136
2089:     ld_structured r5.x, r2.x, l(0), g0.xxxx  // r5.x <- s.x
2090:     ld_structured r5.y, r2.x, l(4), g0.xxxx  // r5.y <- s.y
2091:     ld_structured r5.z, r2.x, l(8), g0.xxxx  // r5.z <- s.z
2092:     ld_structured r5.w, r2.x, l(12), g0.xxxx  // r5.w <- s.w

#line 138
2093:     mov r6.xyz, -r5.xyzx
2094:     add r6.xyz, r1.xyzx, r6.xyzx  // r6.x <- diff.x; r6.y <- diff.y; r6.z <- diff.z

#line 139
2095:     dp3 r2.x, r6.xyzx, r6.xyzx  // r2.x <- d2

#line 140
2096:     mov r2.x, -r2.x
2097:     mul r2.x, r1.w, r2.x
2098:     mul r2.x, r2.x, l(1.442695)
2099:     exp r2.x, r2.x  // r2.x <- wR

#line 142
2100:     mul r0.x, r0.x, r2.x  // r0.x <- w

#line 144
2101:     mul r5.xyzw, r0.xxxx, r5.xyzw
2102:     add r4.xyzw, r4.xyzw, r5.xyzw

#line 145
2103:     add r0.w, r0.x, r0.w
2104:   endif 

#line 130
2105:   ineg r0.x, r0.z
2106:   ilt r0.x, l(3), r0.x
2107:   ilt r0.z, r0.z, l(3)
2108:   or r0.x, r0.z, r0.x
2109:   if_nz r0.x

#line 131
2110:     iadd r0.z, l(1), l(3)  // r0.z <- i
2111:   else 
2112:     mov r0.z, l(3)  // r0.z <- i
2113:   endif 

#line 133
2114:   if_z r0.x

#line 134
2115:     mov r0.x, x0[48].x  // r0.x <- wS

#line 136
2116:     nop 
2117:     iadd r0.z, r0.z, r2.y  // r0.z <- x
2118:     iadd r2.x, r2.w, r2.z  // r2.x <- y

#line 22
2119:     imul null, r2.x, r2.x, l(22)
2120:     iadd r0.z, r0.z, r2.x  // r0.z <- <CacheIndex return value>

#line 136
2121:     ld_structured r2.x, r0.z, l(0), g0.xxxx  // r2.x <- s.x
2122:     ld_structured r2.y, r0.z, l(4), g0.xxxx  // r2.y <- s.y
2123:     ld_structured r2.z, r0.z, l(8), g0.xxxx  // r2.z <- s.z
2124:     ld_structured r2.w, r0.z, l(12), g0.xxxx  // r2.w <- s.w

#line 138
2125:     mov r5.xyz, -r2.xyzx
2126:     add r1.xyz, r1.xyzx, r5.xyzx  // r1.x <- diff.x; r1.y <- diff.y; r1.z <- diff.z

#line 139
2127:     dp3 r0.z, r1.xyzx, r1.xyzx  // r0.z <- d2

#line 140
2128:     mov r0.z, -r0.z
2129:     mul r0.z, r1.w, r0.z
2130:     mul r0.z, r0.z, l(1.442695)
2131:     exp r0.z, r0.z  // r0.z <- wR

#line 142
2132:     mul r0.x, r0.z, r0.x  // r0.x <- w

#line 144
2133:     mul r1.xyzw, r0.xxxx, r2.xyzw
2134:     add r4.xyzw, r1.xyzw, r4.xyzw

#line 145
2135:     add r0.w, r0.x, r0.w
2136:   endif 

#line 146
2137: endif 

#line 149
2138: max r0.x, r0.w, l(0.000001)
2139: div r1.xyzw, r4.xyzw, r0.xxxx  // r1.x <- outColor.x; r1.y <- outColor.y; r1.z <- outColor.z; r1.w <- outColor.w

#line 151
2140: if_nz r0.y

#line 153
2141:   store_uav_typed u0.xyzw, r3.yzwx, r1.xyzw

#line 154
2142: endif 

#line 155
2143: ret 
// Approximately 2144 instruction slots used
 