//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbSettings
// {
//
//   int gBlurRadius;                   // Offset:    0 Size:     4
//   float w0;                          // Offset:    4 Size:     4
//   float w1;                          // Offset:    8 Size:     4
//   float w2;                          // Offset:   12 Size:     4
//   float w3;                          // Offset:   16 Size:     4
//   float w4;                          // Offset:   20 Size:     4
//   float w5;                          // Offset:   24 Size:     4
//   float w6;                          // Offset:   28 Size:     4
//   float w7;                          // Offset:   32 Size:     4
//   float w8;                          // Offset:   36 Size:     4
//   float w9;                          // Offset:   40 Size:     4
//   float w10;                         // Offset:   44 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gInput                            texture  float4          2d             t0      1 
// gOutput                               UAV  float4          2d             u0      1 
// cbSettings                        cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      cs_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[3], immediateIndexed
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_uav_typed_texture2d (float,float,float,float) u0
      dcl_input vThreadIDInGroup.y
      dcl_input vThreadID.xy
      dcl_temps 5
      dcl_indexableTemp x0[11], 4
      dcl_tgsm_structured g0, 16, 266
      dcl_thread_group 1, 256, 1
//
// Initial variable locations:
//   vThreadIDInGroup.x <- groupThreadID.x; vThreadIDInGroup.y <- groupThreadID.y; vThreadIDInGroup.z <- groupThreadID.z; 
//   vThreadID.x <- dispatchThreadID.x; vThreadID.y <- dispatchThreadID.y; vThreadID.z <- dispatchThreadID.z; 
//   x0 <- weights
//
#line 24 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap13\Chap13_Solution\Chap13_4\Shaders\Blur.hlsl"
   0: mov r0.x, l(5)  // r0.x <- gMaxBlurRadius

#line 115
   1: imin r0.y, r0.x, cb0[0].x  // r0.y <- radius

#line 117
   2: mov x0[0].x, cb0[0].y
   3: mov x0[1].x, cb0[0].z
   4: mov x0[2].x, cb0[0].w
   5: mov x0[3].x, cb0[1].x
   6: mov x0[4].x, cb0[1].y
   7: mov x0[5].x, cb0[1].z
   8: mov x0[6].x, cb0[1].w
   9: mov x0[7].x, cb0[2].x
  10: mov x0[8].x, cb0[2].y
  11: mov x0[9].x, cb0[2].z
  12: mov x0[10].x, cb0[2].w

#line 120
  13: resinfo_indexable(texture2d)(float,float,float,float)_uint r0.zw, l(0), t0.zwxy
  14: mov r0.z, r0.z  // r0.z <- texW
  15: mov r0.w, r0.w  // r0.w <- texH

#line 122
  16: mov r1.x, vThreadIDInGroup.y  // r1.x <- gy

#line 123
  17: mov r1.y, vThreadID.x  // r1.y <- dx

#line 124
  18: mov r1.z, vThreadID.y  // r1.z <- dy

#line 126
  19: ineg r1.w, l(1)
  20: iadd r0.z, r0.z, r1.w  // r0.z <- maxX

#line 127
  21: ineg r1.w, l(1)
  22: iadd r0.w, r0.w, r1.w  // r0.w <- maxY

#line 129
  23: ilt r1.w, r0.z, l(0)
  24: ilt r2.x, r0.w, l(0)
  25: or r1.w, r1.w, r2.x
  26: if_nz r1.w

#line 130
  27:   ret 
  28: endif 

#line 132
  29: ilt r1.w, r1.x, r0.y
  30: if_nz r1.w

#line 134
  31:   ineg r1.w, r0.y
  32:   iadd r1.w, r1.w, r1.z
  33:   imax r2.y, r1.w, l(0)  // r2.y <- y

#line 135
  34:   imax r1.w, r1.y, l(0)
  35:   imin r2.x, r0.z, r1.w  // r2.x <- x

#line 136
  36:   mov r2.zw, l(0,0,0,0)
  37:   ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyzw, t0.xyzw
  38:   store_structured g0.x, r1.x, l(0), r2.x
  39:   store_structured g0.x, r1.x, l(4), r2.y
  40:   store_structured g0.x, r1.x, l(8), r2.z
  41:   store_structured g0.x, r1.x, l(12), r2.w

#line 137
  42: endif 

#line 139
  43: ineg r1.w, r0.y
  44: iadd r1.w, r1.w, l(256)
  45: ige r1.w, r1.x, r1.w
  46: if_nz r1.w

#line 141
  47:   iadd r1.w, r0.y, r1.z
  48:   imin r2.y, r0.w, r1.w  // r2.y <- y

#line 142
  49:   imax r1.w, r1.y, l(0)
  50:   imin r2.x, r0.z, r1.w  // r2.x <- x

#line 143
  51:   imul null, r1.w, r0.y, l(2)
  52:   iadd r1.w, r1.w, r1.x
  53:   mov r2.zw, l(0,0,0,0)
  54:   ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyzw, t0.xyzw
  55:   store_structured g0.x, r1.w, l(0), r2.x
  56:   store_structured g0.x, r1.w, l(4), r2.y
  57:   store_structured g0.x, r1.w, l(8), r2.z
  58:   store_structured g0.x, r1.w, l(12), r2.w

#line 144
  59: endif 

#line 148
  60: imax r1.w, r1.y, l(0)
  61: imin r2.x, r0.z, r1.w  // r2.x <- x

#line 149
  62: imax r1.w, r1.z, l(0)
  63: imin r2.y, r0.w, r1.w  // r2.y <- y

#line 150
  64: iadd r1.w, r0.y, r1.x
  65: mov r2.zw, l(0,0,0,0)
  66: ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyzw, t0.xyzw
  67: store_structured g0.x, r1.w, l(0), r2.x
  68: store_structured g0.x, r1.w, l(4), r2.y
  69: store_structured g0.x, r1.w, l(8), r2.z
  70: store_structured g0.x, r1.w, l(12), r2.w

#line 153
  71: sync_g_t

#line 155
  72: itof r2.xyzw, l(0, 0, 0, 0)  // r2.x <- blurColor.x; r2.y <- blurColor.y; r2.z <- blurColor.z; r2.w <- blurColor.w

#line 156
  73: iadd r1.x, r0.y, r1.x  // r1.x <- centerK

#line 159
  74: mov r1.w, l(-5)  // r1.w <- i

#line 161
  75: ineg r3.x, r0.y
  76: ilt r3.x, r1.w, r3.x
  77: ilt r3.y, r0.y, r1.w
  78: or r3.x, r3.y, r3.x
  79: if_nz r3.x

#line 162
  80:   iadd r1.w, r1.w, l(1)
  81: endif 

#line 164
  82: if_z r3.x
  83:   iadd r3.x, r1.w, r1.x  // r3.x <- k

#line 165
  84:   iadd r1.w, r0.x, r1.w
  85:   mov r1.w, x0[r1.w + 0].x
  86:   ld_structured r4.x, r3.x, l(0), g0.xxxx
  87:   ld_structured r4.y, r3.x, l(4), g0.xxxx
  88:   ld_structured r4.z, r3.x, l(8), g0.xxxx
  89:   ld_structured r4.w, r3.x, l(12), g0.xxxx
  90:   mul r3.xyzw, r1.wwww, r4.xyzw
  91:   add r2.xyzw, r2.xyzw, r3.xyzw
  92: endif 

#line 161
  93: ineg r1.w, r0.y
  94: ilt r1.w, l(-4), r1.w
  95: ilt r3.x, r0.y, l(-4)
  96: or r1.w, r1.w, r3.x
  97: if_nz r1.w

#line 162
  98:   iadd r3.x, l(1), l(-4)  // r3.x <- i
  99: else 
 100:   mov r3.x, l(-4)  // r3.x <- i
 101: endif 

#line 164
 102: if_z r1.w
 103:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 104:   iadd r3.x, r0.x, r3.x
 105:   mov r3.x, x0[r3.x + 0].x
 106:   ld_structured r4.x, r1.w, l(0), g0.xxxx
 107:   ld_structured r4.y, r1.w, l(4), g0.xxxx
 108:   ld_structured r4.z, r1.w, l(8), g0.xxxx
 109:   ld_structured r4.w, r1.w, l(12), g0.xxxx
 110:   mul r3.xyzw, r3.xxxx, r4.xyzw
 111:   add r2.xyzw, r2.xyzw, r3.xyzw
 112: endif 

#line 161
 113: ineg r1.w, r0.y
 114: ilt r1.w, l(-3), r1.w
 115: ilt r3.x, r0.y, l(-3)
 116: or r1.w, r1.w, r3.x
 117: if_nz r1.w

#line 162
 118:   iadd r3.x, l(1), l(-3)  // r3.x <- i
 119: else 
 120:   mov r3.x, l(-3)  // r3.x <- i
 121: endif 

#line 164
 122: if_z r1.w
 123:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 124:   iadd r3.x, r0.x, r3.x
 125:   mov r3.x, x0[r3.x + 0].x
 126:   ld_structured r4.x, r1.w, l(0), g0.xxxx
 127:   ld_structured r4.y, r1.w, l(4), g0.xxxx
 128:   ld_structured r4.z, r1.w, l(8), g0.xxxx
 129:   ld_structured r4.w, r1.w, l(12), g0.xxxx
 130:   mul r3.xyzw, r3.xxxx, r4.xyzw
 131:   add r2.xyzw, r2.xyzw, r3.xyzw
 132: endif 

#line 161
 133: ineg r1.w, r0.y
 134: ilt r1.w, l(-2), r1.w
 135: ilt r3.x, r0.y, l(-2)
 136: or r1.w, r1.w, r3.x
 137: if_nz r1.w

#line 162
 138:   iadd r3.x, l(1), l(-2)  // r3.x <- i
 139: else 
 140:   mov r3.x, l(-2)  // r3.x <- i
 141: endif 

#line 164
 142: if_z r1.w
 143:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 144:   iadd r3.x, r0.x, r3.x
 145:   mov r3.x, x0[r3.x + 0].x
 146:   ld_structured r4.x, r1.w, l(0), g0.xxxx
 147:   ld_structured r4.y, r1.w, l(4), g0.xxxx
 148:   ld_structured r4.z, r1.w, l(8), g0.xxxx
 149:   ld_structured r4.w, r1.w, l(12), g0.xxxx
 150:   mul r3.xyzw, r3.xxxx, r4.xyzw
 151:   add r2.xyzw, r2.xyzw, r3.xyzw
 152: endif 

#line 161
 153: ineg r1.w, r0.y
 154: ilt r1.w, l(-1), r1.w
 155: ilt r3.x, r0.y, l(-1)
 156: or r1.w, r1.w, r3.x
 157: not r3.x, r1.w  // r3.x <- i

#line 164
 158: if_z r1.w
 159:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 160:   iadd r3.x, r0.x, r3.x
 161:   mov r3.x, x0[r3.x + 0].x
 162:   ld_structured r4.x, r1.w, l(0), g0.xxxx
 163:   ld_structured r4.y, r1.w, l(4), g0.xxxx
 164:   ld_structured r4.z, r1.w, l(8), g0.xxxx
 165:   ld_structured r4.w, r1.w, l(12), g0.xxxx
 166:   mul r3.xyzw, r3.xxxx, r4.xyzw
 167:   add r2.xyzw, r2.xyzw, r3.xyzw
 168: endif 

#line 161
 169: ineg r1.w, r0.y
 170: ilt r1.w, l(0), r1.w
 171: ilt r3.x, r0.y, l(0)
 172: or r1.w, r1.w, r3.x
 173: if_nz r1.w

#line 162
 174:   iadd r3.x, l(1), l(0)  // r3.x <- i
 175: else 
 176:   mov r3.x, l(0)  // r3.x <- i
 177: endif 

#line 164
 178: if_z r1.w
 179:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 180:   iadd r3.x, r0.x, r3.x
 181:   mov r3.x, x0[r3.x + 0].x
 182:   ld_structured r4.x, r1.w, l(0), g0.xxxx
 183:   ld_structured r4.y, r1.w, l(4), g0.xxxx
 184:   ld_structured r4.z, r1.w, l(8), g0.xxxx
 185:   ld_structured r4.w, r1.w, l(12), g0.xxxx
 186:   mul r3.xyzw, r3.xxxx, r4.xyzw
 187:   add r2.xyzw, r2.xyzw, r3.xyzw
 188: endif 

#line 161
 189: ineg r1.w, r0.y
 190: ilt r1.w, l(1), r1.w
 191: ilt r3.x, r0.y, l(1)
 192: or r1.w, r1.w, r3.x
 193: if_nz r1.w

#line 162
 194:   iadd r3.x, l(1), l(1)  // r3.x <- i
 195: else 
 196:   mov r3.x, l(1)  // r3.x <- i
 197: endif 

#line 164
 198: if_z r1.w
 199:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 200:   iadd r3.x, r0.x, r3.x
 201:   mov r3.x, x0[r3.x + 0].x
 202:   ld_structured r4.x, r1.w, l(0), g0.xxxx
 203:   ld_structured r4.y, r1.w, l(4), g0.xxxx
 204:   ld_structured r4.z, r1.w, l(8), g0.xxxx
 205:   ld_structured r4.w, r1.w, l(12), g0.xxxx
 206:   mul r3.xyzw, r3.xxxx, r4.xyzw
 207:   add r2.xyzw, r2.xyzw, r3.xyzw
 208: endif 

#line 161
 209: ineg r1.w, r0.y
 210: ilt r1.w, l(2), r1.w
 211: ilt r3.x, r0.y, l(2)
 212: or r1.w, r1.w, r3.x
 213: if_nz r1.w

#line 162
 214:   iadd r3.x, l(1), l(2)  // r3.x <- i
 215: else 
 216:   mov r3.x, l(2)  // r3.x <- i
 217: endif 

#line 164
 218: if_z r1.w
 219:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 220:   iadd r3.x, r0.x, r3.x
 221:   mov r3.x, x0[r3.x + 0].x
 222:   ld_structured r4.x, r1.w, l(0), g0.xxxx
 223:   ld_structured r4.y, r1.w, l(4), g0.xxxx
 224:   ld_structured r4.z, r1.w, l(8), g0.xxxx
 225:   ld_structured r4.w, r1.w, l(12), g0.xxxx
 226:   mul r3.xyzw, r3.xxxx, r4.xyzw
 227:   add r2.xyzw, r2.xyzw, r3.xyzw
 228: endif 

#line 161
 229: ineg r1.w, r0.y
 230: ilt r1.w, l(3), r1.w
 231: ilt r3.x, r0.y, l(3)
 232: or r1.w, r1.w, r3.x
 233: if_nz r1.w

#line 162
 234:   iadd r3.x, l(1), l(3)  // r3.x <- i
 235: else 
 236:   mov r3.x, l(3)  // r3.x <- i
 237: endif 

#line 164
 238: if_z r1.w
 239:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 240:   iadd r3.x, r0.x, r3.x
 241:   mov r3.x, x0[r3.x + 0].x
 242:   ld_structured r4.x, r1.w, l(0), g0.xxxx
 243:   ld_structured r4.y, r1.w, l(4), g0.xxxx
 244:   ld_structured r4.z, r1.w, l(8), g0.xxxx
 245:   ld_structured r4.w, r1.w, l(12), g0.xxxx
 246:   mul r3.xyzw, r3.xxxx, r4.xyzw
 247:   add r2.xyzw, r2.xyzw, r3.xyzw
 248: endif 

#line 161
 249: ineg r1.w, r0.y
 250: ilt r1.w, l(4), r1.w
 251: ilt r3.x, r0.y, l(4)
 252: or r1.w, r1.w, r3.x
 253: if_nz r1.w

#line 162
 254:   iadd r3.x, l(1), l(4)  // r3.x <- i
 255: else 
 256:   mov r3.x, l(4)  // r3.x <- i
 257: endif 

#line 164
 258: if_z r1.w
 259:   iadd r1.w, r1.x, r3.x  // r1.w <- k

#line 165
 260:   iadd r0.x, r0.x, r3.x
 261:   mov r0.x, x0[r0.x + 0].x
 262:   ld_structured r3.x, r1.w, l(0), g0.xxxx
 263:   ld_structured r3.y, r1.w, l(4), g0.xxxx
 264:   ld_structured r3.z, r1.w, l(8), g0.xxxx
 265:   ld_structured r3.w, r1.w, l(12), g0.xxxx
 266:   mul r3.xyzw, r0.xxxx, r3.xyzw
 267:   add r2.xyzw, r2.xyzw, r3.xyzw
 268: endif 

#line 161
 269: ineg r0.x, r0.y
 270: ilt r0.x, l(5), r0.x
 271: ilt r0.y, r0.y, l(5)
 272: or r0.x, r0.y, r0.x
 273: if_nz r0.x

#line 162
 274:   iadd r0.y, l(1), l(5)  // r0.y <- i
 275: else 
 276:   mov r0.y, l(5)  // r0.y <- i
 277: endif 

#line 164
 278: if_z r0.x
 279:   iadd r0.x, r0.y, r1.x  // r0.x <- k

#line 165
 280:   mov r0.y, x0[10].x
 281:   ld_structured r3.x, r0.x, l(0), g0.xxxx
 282:   ld_structured r3.y, r0.x, l(4), g0.xxxx
 283:   ld_structured r3.z, r0.x, l(8), g0.xxxx
 284:   ld_structured r3.w, r0.x, l(12), g0.xxxx
 285:   mul r3.xyzw, r0.yyyy, r3.xyzw
 286:   add r2.xyzw, r2.xyzw, r3.xyzw
 287: endif 

#line 170
 288: imax r0.x, r1.y, l(0)
 289: imin r3.x, r0.z, r0.x  // r3.x <- x

#line 171
 290: imax r0.x, r1.z, l(0)
 291: imin r3.yzw, r0.wwww, r0.xxxx  // r3.w <- y

#line 172
 292: store_uav_typed u0.xyzw, r3.xyzw, r2.xyzw

#line 174
 293: ret 
// Approximately 294 instruction slots used
 