//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  448
//       float FalloffStart;            // Offset:  460
//       float3 Direction;              // Offset:  464
//       float FalloffEnd;              // Offset:  476
//       float3 Position;               // Offset:  480
//       float SpotPower;               // Offset:  492
//
//   } gLights[16];                     // Offset:  448 Size:   768
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// cbMaterial                        cbuffer      NA          NA     CB0            cb1      1 
// cbPass                            cbuffer      NA          NA     CB1            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_1
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[1:1][2], immediateIndexed, space=0
      dcl_constantbuffer CB1[2:2][43], immediateIndexed, space=0
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xyz
      dcl_output o0.xyzw
      dcl_temps 17
      dcl_indexableTemp x0[30], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 97 "C:\cg\DX12\Solution\Chap8\Chap8_LitColumns\Shaders\Default.hlsl"
   0: dp3 r0.x, v2.xyzx, v2.xyzx
   1: rsq r0.x, r0.x
   2: mul r0.xyz, r0.xxxx, v2.xyzx  // r0.x <- pin.NormalW.x; r0.y <- pin.NormalW.y; r0.z <- pin.NormalW.z

#line 100
   3: mov r1.xyz, -v1.xyzx
   4: add r1.xyz, r1.xyzx, CB1[2][24].xyzx
   5: dp3 r0.w, r1.xyzx, r1.xyzx
   6: rsq r0.w, r0.w
   7: mul r1.xyz, r0.wwww, r1.xyzx  // r1.x <- toEyeW.x; r1.y <- toEyeW.y; r1.z <- toEyeW.z

#line 103
   8: mul r2.xyz, CB0[1][0].xyzx, CB1[2][27].xyzx  // r2.x <- ambient.x; r2.y <- ambient.y; r2.z <- ambient.z

#line 105
   9: mov r0.w, -CB0[1][1].w
  10: add r3.w, r0.w, l(1.000000)  // r3.w <- shininess

#line 106
  11: mov r4.xyz, CB0[1][0].xyzx  // r4.x <- mat.DiffuseAlbedo.x; r4.y <- mat.DiffuseAlbedo.y; r4.z <- mat.DiffuseAlbedo.z
  12: mov r3.xyz, CB0[1][1].xyzx  // r3.x <- mat.FresnelR0.x; r3.y <- mat.FresnelR0.y; r3.z <- mat.FresnelR0.z
  13: mov r3.w, r3.w  // r3.w <- mat.Shininess

#line 108
  14: nop 
  15: mov x0[0].xyz, CB1[2][28].xyzx
  16: mov x0[1].x, CB1[2][28].w
  17: mov x0[2].xyz, CB1[2][29].xyzx
  18: mov x0[3].x, CB1[2][29].w
  19: mov x0[4].xyz, CB1[2][30].xyzx
  20: mov x0[5].x, CB1[2][30].w
  21: mov x0[6].xyz, CB1[2][31].xyzx
  22: mov x0[7].x, CB1[2][31].w
  23: mov x0[8].xyz, CB1[2][32].xyzx
  24: mov x0[9].x, CB1[2][32].w
  25: mov x0[10].xyz, CB1[2][33].xyzx
  26: mov x0[11].x, CB1[2][33].w
  27: mov x0[12].xyz, CB1[2][34].xyzx
  28: mov x0[13].x, CB1[2][34].w
  29: mov x0[14].xyz, CB1[2][35].xyzx
  30: mov x0[15].x, CB1[2][35].w
  31: mov x0[16].xyz, CB1[2][36].xyzx
  32: mov x0[17].x, CB1[2][36].w
  33: mov x0[18].xyz, CB1[2][37].xyzx
  34: mov x0[19].x, CB1[2][37].w
  35: mov x0[20].xyz, CB1[2][38].xyzx
  36: mov x0[21].x, CB1[2][38].w
  37: mov x0[22].xyz, CB1[2][39].xyzx
  38: mov x0[23].x, CB1[2][39].w
  39: mov x0[24].xyz, CB1[2][40].xyzx
  40: mov x0[25].x, CB1[2][40].w
  41: mov x0[26].xyz, CB1[2][41].xyzx
  42: mov x0[27].x, CB1[2][41].w
  43: mov x0[28].xyz, CB1[2][42].xyzx
  44: mov x0[29].x, CB1[2][42].w
  45: mov r4.xyz, r4.xyzx
  46: mov r3.x, r3.x
  47: mov r3.yzw, r3.yyzw
  48: mov r5.xyz, v1.xyzx
  49: mov r0.xyz, r0.xyzx
  50: mov r1.xyz, r1.xyzx

#line 143 "LightingUtil.hlsl"
  51: mov r6.xyz, l(0,0,0,0)  // r6.x <- result.x; r6.y <- result.y; r6.z <- result.z

#line 162
  52: mov r0.w, l(0)  // r0.w <- i
  53: mov r7.xyz, r6.xyzx  // r7.x <- result.x; r7.y <- result.y; r7.z <- result.z
  54: mov r1.w, r0.w  // r1.w <- i
  55: loop 
  56:   ilt r2.w, r1.w, l(4)
  57:   breakc_z r2.w

#line 164
  58:   nop 
  59:   imul null, r2.w, r1.w, l(6)
  60:   mov r8.xyz, x0[r2.w + 0].xyzx
  61:   mov r4.w, x0[r2.w + 1].x
  62:   mov r9.xyz, x0[r2.w + 2].xyzx
  63:   mov r5.w, x0[r2.w + 3].x
  64:   mov r10.xyz, x0[r2.w + 4].xyzx
  65:   mov r2.w, x0[r2.w + 5].x
  66:   mov r11.x, r3.x
  67:   mov r11.yzw, r3.yyzw
  68:   mov r12.xyz, r4.xyzx
  69:   mov r13.xyz, r5.xyzx
  70:   mov r14.xyz, r0.xyzx
  71:   mov r15.xyz, r1.xyzx

#line 111
  72:   mov r13.xyz, -r13.xyzx
  73:   add r10.xyz, r10.xyzx, r13.xyzx  // r10.x <- lightVec.x; r10.y <- lightVec.y; r10.z <- lightVec.z

#line 114
  74:   dp3 r6.w, r10.xyzx, r10.xyzx
  75:   sqrt r6.w, r6.w  // r6.w <- d

#line 117
  76:   lt r7.w, r5.w, r6.w
  77:   if_nz r7.w

#line 118
  78:     mov r13.xyz, l(0,0,0,0)
  79:   endif   // r13.x <- <ComputeSpotLight return value>.x; r13.y <- <ComputeSpotLight return value>.y; r13.z <- <ComputeSpotLight return value>.z

#line 121
  80:   if_z r7.w
  81:     div r10.xyz, r10.xyzx, r6.wwww

#line 124
  82:     dp3 r7.w, r10.xyzx, r14.xyzx
  83:     max r7.w, r7.w, l(0.000000)  // r7.w <- ndotl

#line 125
  84:     mul r8.xyz, r7.wwww, r8.xyzx  // r8.x <- lightStrength.x; r8.y <- lightStrength.y; r8.z <- lightStrength.z

#line 128
  85:     nop 
  86:     mov r6.w, r6.w
  87:     mov r4.w, r4.w
  88:     mov r5.w, r5.w

#line 29
  89:     mov r6.w, -r6.w
  90:     add r6.w, r5.w, r6.w
  91:     mov r4.w, -r4.w
  92:     add r4.w, r4.w, r5.w
  93:     div r4.w, r6.w, r4.w
  94:     max r4.w, r4.w, l(0.000000)
  95:     min r4.w, r4.w, l(1.000000)  // r4.w <- <CalcAttenuation return value>

#line 128
  96:     mov r4.w, r4.w  // r4.w <- att

#line 129
  97:     mul r8.xyz, r4.wwww, r8.xyzx

#line 132
  98:     dp3 r4.w, r9.xyzx, r9.xyzx
  99:     rsq r4.w, r4.w
 100:     mul r9.xyz, r4.wwww, r9.xyzx  // r9.x <- Dir.x; r9.y <- Dir.y; r9.z <- Dir.z

#line 133
 101:     mov r16.xyz, -r10.xyzx
 102:     dp3 r4.w, r16.xyzx, r9.xyzx
 103:     max r4.w, r4.w, l(0.000000)
 104:     log r4.w, r4.w
 105:     mul r2.w, r2.w, r4.w
 106:     exp r2.w, r2.w  // r2.w <- spotFactor

#line 134
 107:     mul r8.xyz, r2.wwww, r8.xyzx

#line 136
 108:     nop 
 109:     mov r8.xyz, r8.xyzx
 110:     mov r10.xyz, r10.xyzx
 111:     mov r14.xyz, r14.xyzx
 112:     mov r15.xyz, r15.xyzx
 113:     mov r12.xyz, r12.xyzx
 114:     mov r11.xyzw, r11.xyzw

#line 46
 115:     mul r2.w, r11.w, l(256.000000)  // r2.w <- m

#line 47
 116:     add r9.xyz, r10.xyzx, r15.xyzx
 117:     dp3 r4.w, r9.xyzx, r9.xyzx
 118:     rsq r4.w, r4.w
 119:     mul r9.xyz, r4.wwww, r9.xyzx  // r9.x <- halfVec.x; r9.y <- halfVec.y; r9.z <- halfVec.z

#line 49
 120:     add r4.w, r2.w, l(8.000000)
 121:     dp3 r5.w, r9.xyzx, r14.xyzx
 122:     max r5.w, r5.w, l(0.000000)
 123:     log r5.w, r5.w
 124:     mul r2.w, r2.w, r5.w
 125:     exp r2.w, r2.w
 126:     mul r2.w, r2.w, r4.w
 127:     div r2.w, r2.w, l(8.000000)  // r2.w <- roughnessFactor

#line 50
 128:     nop 
 129:     mov r11.xyz, r11.xyzx
 130:     mov r9.xyz, r9.xyzx
 131:     mov r10.xyz, r10.xyzx

#line 36
 132:     dp3 r4.w, r9.xyzx, r10.xyzx
 133:     max r4.w, r4.w, l(0.000000)
 134:     min r4.w, r4.w, l(1.000000)  // r4.w <- cosIncidentAngle

#line 38
 135:     mov r4.w, -r4.w
 136:     add r4.w, r4.w, l(1.000000)  // r4.w <- f0

#line 39
 137:     mov r9.xyz, -r11.xyzx
 138:     add r9.xyz, r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 139:     mul r5.w, r4.w, r4.w
 140:     mul r5.w, r4.w, r5.w
 141:     mul r5.w, r4.w, r5.w
 142:     mul r4.w, r4.w, r5.w
 143:     mul r9.xyz, r4.wwww, r9.xyzx
 144:     add r9.xyz, r9.xyzx, r11.xyzx  // r9.x <- reflectPercent.x; r9.y <- reflectPercent.y; r9.z <- reflectPercent.z

#line 41
 145:     mov r9.xyz, r9.xyzx  // r9.x <- <SchlickFresnel return value>.x; r9.y <- <SchlickFresnel return value>.y; r9.z <- <SchlickFresnel return value>.z

#line 50
 146:     mov r9.xyz, r9.xyzx  // r9.x <- fresnelFactor.x; r9.y <- fresnelFactor.y; r9.z <- fresnelFactor.z

#line 52
 147:     mul r9.xyz, r2.wwww, r9.xyzx  // r9.x <- specAlbedo.x; r9.y <- specAlbedo.y; r9.z <- specAlbedo.z

#line 56
 148:     add r10.xyz, r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 149:     div r9.xyz, r9.xyzx, r10.xyzx

#line 58
 150:     add r9.xyz, r9.xyzx, r12.xyzx
 151:     mul r13.xyz, r8.xyzx, r9.xyzx  // r13.x <- <BlinnPhong return value>.x; r13.y <- <BlinnPhong return value>.y; r13.z <- <BlinnPhong return value>.z

#line 136
 152:     mov r13.xyz, r13.xyzx  // r13.x <- <ComputeSpotLight return value>.x; r13.y <- <ComputeSpotLight return value>.y; r13.z <- <ComputeSpotLight return value>.z
 153:   endif 

#line 164
 154:   add r7.xyz, r7.xyzx, r13.xyzx

#line 165
 155:   iadd r1.w, r1.w, l(1)
 156: endloop 

#line 168
 157: mov r7.xyz, r7.xyzx  // r7.x <- <ComputeLighting return value>.x; r7.y <- <ComputeLighting return value>.y; r7.z <- <ComputeLighting return value>.z

#line 108 "C:\cg\DX12\Solution\Chap8\Chap8_LitColumns\Shaders\Default.hlsl"
 158: mov r7.xyz, r7.xyzx  // r7.x <- directLight.x; r7.y <- directLight.y; r7.z <- directLight.z

#line 111
 159: add r0.xyz, r2.xyzx, r7.xyzx  // r0.x <- litColor.x; r0.y <- litColor.y; r0.z <- litColor.z

#line 114
 160: mov r0.w, CB0[1][0].w  // r0.w <- litColor.w

#line 116
 161: mov o0.xyz, r0.xyzx
 162: mov o0.w, r0.w
 163: ret 
// Approximately 164 instruction slots used
 