//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64 [unused]
//   float4x4 gTexTransform;            // Offset:   64 Size:    64 [unused]
//   uint gMaterialIndex;               // Offset:  128 Size:     4
//   uint gObjPad0;                     // Offset:  132 Size:     4 [unused]
//   uint gObjPad1;                     // Offset:  136 Size:     4 [unused]
//   uint gObjPad2;                     // Offset:  140 Size:     4 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  448
//       float FalloffStart;            // Offset:  460
//       float3 Direction;              // Offset:  464
//       float FalloffEnd;              // Offset:  476
//       float3 Position;               // Offset:  480
//       float SpotPower;               // Offset:  492
//
//   } gLights[16];                     // Offset:  448 Size:   768
//
// }
//
// Resource bind info for gMaterialData
// {
//
//   struct MaterialData
//   {
//       
//       float4 DiffuseAlbedo;          // Offset:    0
//       float3 FresnelR0;              // Offset:   16
//       float Roughness;               // Offset:   28
//       float4x4 MatTransform;         // Offset:   32
//       uint DiffuseMapIndex;          // Offset:   96
//       uint MatPad0;                  // Offset:  100
//       uint MatPad1;                  // Offset:  104
//       uint MatPad2;                  // Offset:  108
//
//   } $Element;                        // Offset:    0 Size:   112
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// gsamLinearWrap                    sampler      NA          NA      S0             s2      1 
// gDiffuseMap                       texture  float4          2d      T0             t0      4 
// gMaterialData                     texture  struct         r/o      T1      t0,space1      1 
// cbPerObject                       cbuffer      NA          NA     CB0            cb0      1 
// cbPass                            cbuffer      NA          NA     CB1            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_1
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[0:0][9], immediateIndexed, space=0
      dcl_constantbuffer CB1[1:1][39], immediateIndexed, space=0
      dcl_sampler S0[2:2], mode_default, space=0
      dcl_resource_texture2d (float,float,float,float) T0[0:3], space=0
      dcl_resource_structured T1[0:0], 112, space=1
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xyz
      dcl_input_ps linear v3.xy
      dcl_output o0.xyzw
      dcl_temps 13
      dcl_indexableTemp x0[21], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   v3.x <- pin.TexC.x; v3.y <- pin.TexC.y; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 129 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap15\CameraAndDynamicIndexing\Shaders\Default.hlsl"
   0: ld_structured r0.x, CB0[0][8].x, l(0), T1[0].xxxx  // r0.x <- matData.DiffuseAlbedo.x
   1: ld_structured r0.y, CB0[0][8].x, l(4), T1[0].xxxx  // r0.y <- matData.DiffuseAlbedo.y
   2: ld_structured r0.z, CB0[0][8].x, l(8), T1[0].xxxx  // r0.z <- matData.DiffuseAlbedo.z
   3: ld_structured r0.w, CB0[0][8].x, l(12), T1[0].xxxx  // r0.w <- matData.DiffuseAlbedo.w
   4: ld_structured r1.x, CB0[0][8].x, l(16), T1[0].xxxx  // r1.x <- matData.FresnelR0.x
   5: ld_structured r1.y, CB0[0][8].x, l(20), T1[0].xxxx  // r1.y <- matData.FresnelR0.y
   6: ld_structured r1.z, CB0[0][8].x, l(24), T1[0].xxxx  // r1.z <- matData.FresnelR0.z
   7: ld_structured r2.x, CB0[0][8].x, l(28), T1[0].xxxx  // r2.x <- matData.Roughness
   8: ld_structured r2.y, CB0[0][8].x, l(96), T1[0].xxxx  // r2.y <- matData.DiffuseMapIndex

#line 130
   9: mov r0.xyzw, r0.xyzw  // r0.x <- diffuseAlbedo.x; r0.y <- diffuseAlbedo.y; r0.z <- diffuseAlbedo.z; r0.w <- diffuseAlbedo.w

#line 131
  10: mov r1.xyz, r1.xyzx  // r1.x <- fresnelR0.x; r1.y <- fresnelR0.y; r1.z <- fresnelR0.z

#line 132
  11: mov r2.x, r2.x  // r2.x <- roughness

#line 133
  12: mov r2.y, r2.y  // r2.y <- diffuseTexIndex

#line 136
  13: sample r3.xyzw, v3.xyxx, T0[r2.y + 0].xyzw, S0[2]
  14: mul r0.xyzw, r0.xyzw, r3.xyzw

#line 139
  15: dp3 r2.y, v2.xyzx, v2.xyzx
  16: rsq r2.y, r2.y
  17: mul r2.yzw, r2.yyyy, v2.xxyz  // r2.y <- pin.NormalW.x; r2.z <- pin.NormalW.y; r2.w <- pin.NormalW.z

#line 142
  18: mov r3.xyz, -v1.xyzx
  19: add r3.xyz, r3.xyzx, CB1[1][24].xyzx
  20: dp3 r3.w, r3.xyzx, r3.xyzx
  21: rsq r3.w, r3.w
  22: mul r3.xyz, r3.wwww, r3.xyzx  // r3.x <- toEyeW.x; r3.y <- toEyeW.y; r3.z <- toEyeW.z

#line 145
  23: mul r4.xyz, r0.xyzx, CB1[1][27].xyzx  // r4.x <- ambient.x; r4.y <- ambient.y; r4.z <- ambient.z

#line 147
  24: mov r2.x, -r2.x
  25: add r1.w, r2.x, l(1.000000)  // r1.w <- shininess

#line 148
  26: mov r5.xyz, r0.xyzx  // r5.x <- mat.DiffuseAlbedo.x; r5.y <- mat.DiffuseAlbedo.y; r5.z <- mat.DiffuseAlbedo.z
  27: mov r5.w, r1.x  // r5.w <- mat.FresnelR0.x
  28: mov r1.yz, r1.yyzy  // r1.y <- mat.FresnelR0.y; r1.z <- mat.FresnelR0.z
  29: mov r1.w, r1.w  // r1.w <- mat.Shininess

#line 150
  30: nop 
  31: mov x0[0].xyz, CB1[1][28].xyzx
  32: mov x0[2].xyz, CB1[1][29].xyzx
  33: mov x0[4].xyz, CB1[1][30].xyzx
  34: mov x0[6].xyz, CB1[1][31].xyzx
  35: mov x0[8].xyz, CB1[1][32].xyzx
  36: mov x0[10].xyz, CB1[1][33].xyzx
  37: mov x0[12].xyz, CB1[1][34].xyzx
  38: mov x0[14].xyz, CB1[1][35].xyzx
  39: mov x0[16].xyz, CB1[1][36].xyzx
  40: mov x0[18].xyz, CB1[1][37].xyzx
  41: mov x0[20].xyz, CB1[1][38].xyzx
  42: mov r5.xyzw, r5.xyzw
  43: mov r1.yzw, r1.yyzw
  44: mov r2.yzw, r2.yyzw
  45: mov r3.xyz, r3.xyzx

#line 142 "LightingUtil.hlsl"
  46: mov r0.xyz, l(0,0,0,0)  // r0.x <- result.x; r0.y <- result.y; r0.z <- result.z

#line 147
  47: mov r1.x, l(0)  // r1.x <- i
  48: mov r6.xyz, r0.xyzx  // r6.x <- result.x; r6.y <- result.y; r6.z <- result.z
  49: mov r2.x, r1.x  // r2.x <- i
  50: loop 
  51:   ilt r3.w, r2.x, l(3)
  52:   breakc_z r3.w

#line 149
  53:   mov r3.w, l(1.000000)  // r3.w <- shadowFactor.x
  54:   nop 
  55:   imul null, r4.w, r2.x, l(6)
  56:   mov r7.xyz, x0[r4.w + 0].xyzx
  57:   mov r8.xyz, x0[r4.w + 2].xyzx
  58:   mov r9.x, r5.w
  59:   mov r9.yzw, r1.yyzw
  60:   mov r10.xyz, r5.xyzx
  61:   mov r11.xyz, r2.yzwy
  62:   mov r12.xyz, r3.xyzx

#line 67
  63:   mov r8.xyz, -r8.xyzx  // r8.x <- lightVec.x; r8.y <- lightVec.y; r8.z <- lightVec.z

#line 70
  64:   dp3 r4.w, r8.xyzx, r11.xyzx
  65:   max r4.w, r4.w, l(0.000000)  // r4.w <- ndotl

#line 71
  66:   mul r7.xyz, r4.wwww, r7.xyzx  // r7.x <- lightStrength.x; r7.y <- lightStrength.y; r7.z <- lightStrength.z

#line 73
  67:   nop 
  68:   mov r7.xyz, r7.xyzx
  69:   mov r8.xyz, r8.xyzx
  70:   mov r11.xyz, r11.xyzx
  71:   mov r12.xyz, r12.xyzx
  72:   mov r10.xyz, r10.xyzx
  73:   mov r9.xyzw, r9.xyzw

#line 46
  74:   mul r4.w, r9.w, l(256.000000)  // r4.w <- m

#line 47
  75:   add r12.xyz, r8.xyzx, r12.xyzx
  76:   dp3 r6.w, r12.xyzx, r12.xyzx
  77:   rsq r6.w, r6.w
  78:   mul r12.xyz, r6.wwww, r12.xyzx  // r12.x <- halfVec.x; r12.y <- halfVec.y; r12.z <- halfVec.z

#line 49
  79:   add r6.w, r4.w, l(8.000000)
  80:   dp3 r7.w, r12.xyzx, r11.xyzx
  81:   max r7.w, r7.w, l(0.000000)
  82:   log r7.w, r7.w
  83:   mul r4.w, r4.w, r7.w
  84:   exp r4.w, r4.w
  85:   mul r4.w, r4.w, r6.w
  86:   div r4.w, r4.w, l(8.000000)  // r4.w <- roughnessFactor

#line 50
  87:   nop 
  88:   mov r9.xyz, r9.xyzx
  89:   mov r12.xyz, r12.xyzx
  90:   mov r8.xyz, r8.xyzx

#line 36
  91:   dp3 r6.w, r12.xyzx, r8.xyzx
  92:   max r6.w, r6.w, l(0.000000)
  93:   min r6.w, r6.w, l(1.000000)  // r6.w <- cosIncidentAngle

#line 38
  94:   mov r6.w, -r6.w
  95:   add r6.w, r6.w, l(1.000000)  // r6.w <- f0

#line 39
  96:   mov r8.xyz, -r9.xyzx
  97:   add r8.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  98:   mul r7.w, r6.w, r6.w
  99:   mul r7.w, r6.w, r7.w
 100:   mul r7.w, r6.w, r7.w
 101:   mul r6.w, r6.w, r7.w
 102:   mul r8.xyz, r6.wwww, r8.xyzx
 103:   add r8.xyz, r8.xyzx, r9.xyzx  // r8.x <- reflectPercent.x; r8.y <- reflectPercent.y; r8.z <- reflectPercent.z

#line 41
 104:   mov r8.xyz, r8.xyzx  // r8.x <- <SchlickFresnel return value>.x; r8.y <- <SchlickFresnel return value>.y; r8.z <- <SchlickFresnel return value>.z

#line 50
 105:   mov r8.xyz, r8.xyzx  // r8.x <- fresnelFactor.x; r8.y <- fresnelFactor.y; r8.z <- fresnelFactor.z

#line 52
 106:   mul r8.xyz, r4.wwww, r8.xyzx  // r8.x <- specAlbedo.x; r8.y <- specAlbedo.y; r8.z <- specAlbedo.z

#line 56
 107:   add r9.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 108:   div r8.xyz, r8.xyzx, r9.xyzx

#line 58
 109:   add r8.xyz, r8.xyzx, r10.xyzx
 110:   mul r7.xyz, r7.xyzx, r8.xyzx  // r7.x <- <BlinnPhong return value>.x; r7.y <- <BlinnPhong return value>.y; r7.z <- <BlinnPhong return value>.z

#line 73
 111:   mov r7.xyz, r7.xyzx  // r7.x <- <ComputeDirectionalLight return value>.x; r7.y <- <ComputeDirectionalLight return value>.y; r7.z <- <ComputeDirectionalLight return value>.z

#line 149
 112:   mul r7.xyz, r3.wwww, r7.xyzx
 113:   add r6.xyz, r6.xyzx, r7.xyzx

#line 150
 114:   iadd r2.x, r2.x, l(1)
 115: endloop 

#line 167
 116: mov r6.xyz, r6.xyzx  // r6.x <- <ComputeLighting return value>.x; r6.y <- <ComputeLighting return value>.y; r6.z <- <ComputeLighting return value>.z

#line 150 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap15\CameraAndDynamicIndexing\Shaders\Default.hlsl"
 117: mov r6.xyz, r6.xyzx  // r6.x <- directLight.x; r6.y <- directLight.y; r6.z <- directLight.z

#line 153
 118: add r0.xyz, r4.xyzx, r6.xyzx  // r0.x <- litColor.x; r0.y <- litColor.y; r0.z <- litColor.z

#line 156
 119: mov r0.w, r0.w  // r0.w <- litColor.w

#line 158
 120: mov o0.xyz, r0.xyzx
 121: mov o0.w, r0.w
 122: ret 
// Approximately 123 instruction slots used
 