//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   float explodeSpeed;                // Offset:  480 Size:     4
//   float gExplodeTime;                // Offset:  484 Size:     4
//   float gExplodeStartTime;           // Offset:  488 Size:     4
//   float padding;                     // Offset:  492 Size:     4 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  496
//       float FalloffStart;            // Offset:  508
//       float3 Direction;              // Offset:  512
//       float FalloffEnd;              // Offset:  524
//       float3 Position;               // Offset:  528
//       float SpotPower;               // Offset:  540
//
//   } gLights[16];                     // Offset:  496 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TEXCOORD                 0   xyz         2     NONE   float       
// SV_PrimitiveID           0    N/A   primID   PRIMID    uint    YES
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
// SV_PrimitiveID           0   x           4   PRIMID    uint   x   
//
      gs_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB1[31], immediateIndexed
      dcl_input v[3][0].xyz
      dcl_input v[3][1].xyz
      dcl_input v[3][2].xyz
      dcl_input vPrim
      dcl_temps 7
      dcl_inputprimitive triangle 
      dcl_stream m0
      dcl_outputtopology trianglestrip 
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xy
      dcl_output_sgv o4.x, primitive_id
      dcl_maxout 3
//
// Initial variable locations:
//   vPrim <- primID; 
//   m0 <- triStream; 
//   v[0][0].x <- gin[0].PosW.x; v[0][0].y <- gin[0].PosW.y; v[0][0].z <- gin[0].PosW.z; 
//   v[0][1].x <- gin[0].normal.x; v[0][1].y <- gin[0].normal.y; v[0][1].z <- gin[0].normal.z; 
//   v[0][2].x <- gin[0].texC.x; v[0][2].y <- gin[0].texC.y; v[0][2].z <- gin[0].texC.z; 
//   v[1][0].x <- gin[1].PosW.x; v[1][0].y <- gin[1].PosW.y; v[1][0].z <- gin[1].PosW.z; 
//   v[1][1].x <- gin[1].normal.x; v[1][1].y <- gin[1].normal.y; v[1][1].z <- gin[1].normal.z; 
//   v[1][2].x <- gin[1].texC.x; v[1][2].y <- gin[1].texC.y; v[1][2].z <- gin[1].texC.z; 
//   v[2][0].x <- gin[2].PosW.x; v[2][0].y <- gin[2].PosW.y; v[2][0].z <- gin[2].PosW.z; 
//   v[2][1].x <- gin[2].normal.x; v[2][1].y <- gin[2].normal.y; v[2][1].z <- gin[2].normal.z; 
//   v[2][2].x <- gin[2].texC.x; v[2][2].y <- gin[2].texC.y; v[2][2].z <- gin[2].texC.z
//
#line 148 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap12\Chap12_3\Shaders\Sphere.hlsl"
   0: mov r0.xyz, v[0][0].xyzx  // r0.x <- a.x; r0.y <- a.y; r0.z <- a.z

#line 149
   1: mov r1.xyz, v[1][0].xyzx  // r1.x <- b.x; r1.y <- b.y; r1.z <- b.z

#line 150
   2: mov r2.xyz, v[2][0].xyzx  // r2.x <- c.x; r2.y <- c.y; r2.z <- c.z

#line 152
   3: nop 
   4: mov r0.xyz, r0.xyzx
   5: mov r1.xyz, r1.xyzx
   6: mov r2.xyz, r2.xyzx
   7: nop 
   8: mov r0.w, vPrim

#line 118
   9: mov r0.w, r0.w  // r0.w <- o.PrimID

#line 123
  10: dp3 r1.w, r2.xyzx, r2.xyzx
  11: rsq r1.w, r1.w
  12: mul r3.xyz, r1.wwww, r2.xyzx  // r3.x <- o.NormalW.x; r3.y <- o.NormalW.y; r3.z <- o.NormalW.z

#line 125
  13: mov r4.xyz, -r0.zxyz
  14: add r4.xyz, r1.zxyz, r4.xyzx
  15: mov r5.xyz, -r0.yzxy
  16: add r5.xyz, r2.yzxy, r5.xyzx
  17: mul r6.xyz, r4.zxyz, r5.yzxy
  18: mul r4.xyz, r4.xyzx, r5.xyzx
  19: mov r4.xyz, -r4.xyzx
  20: add r4.xyz, r4.xyzx, r6.xyzx
  21: dp3 r1.w, r4.xyzx, r4.xyzx
  22: rsq r1.w, r1.w
  23: mul r4.xyz, r1.wwww, r4.xyzx
  24: mul r4.xyz, r4.xyzx, cb1[30].xxxx  // r4.x <- normal.x; r4.y <- normal.y; r4.z <- normal.z

#line 126
  25: mov r1.w, -cb1[30].z
  26: add r1.w, r1.w, cb1[30].y
  27: mul r5.xyz, r4.xyzx, r1.wwww
  28: add r5.xyz, r0.xyzx, r5.xyzx  // r5.x <- a.x; r5.y <- a.y; r5.z <- a.z

#line 127
  29: mov r5.xyz, r5.xyzx  // r5.x <- o.PosW.x; r5.y <- o.PosW.y; r5.z <- o.PosW.z

#line 128
  30: mov r0.xy, l(0,1.000000,0,0)  // r0.x <- o.TexC.x; r0.y <- o.TexC.y

#line 129
  31: mov r5.w, l(1.000000)
  32: dp4 r6.x, r5.xyzw, cb1[16].xyzw  // r6.x <- o.PosH.x
  33: dp4 r6.y, r5.xyzw, cb1[17].xyzw  // r6.y <- o.PosH.y
  34: dp4 r6.z, r5.xyzw, cb1[18].xyzw  // r6.z <- o.PosH.z
  35: dp4 r6.w, r5.xyzw, cb1[19].xyzw  // r6.w <- o.PosH.w

#line 130
  36: mov o0.xyzw, r6.xyzw
  37: mov o1.xyz, r5.xyzx
  38: mov o2.xyz, r3.xyzx
  39: mov o3.xy, r0.xyxx
  40: mov o4.x, r0.w
  41: emit_stream m0

#line 131
  42: mov r0.x, -cb1[30].z
  43: add r0.x, r0.x, cb1[30].y
  44: mul r0.xyz, r4.xyzx, r0.xxxx
  45: add r1.xyz, r0.xyzx, r1.xyzx

#line 132
  46: mov r1.xyz, r1.xyzx  // r1.x <- o.PosW.x; r1.y <- o.PosW.y; r1.z <- o.PosW.z

#line 133
  47: mov r0.xy, l(1.000000,1.000000,0,0)  // r0.x <- o.TexC.x; r0.y <- o.TexC.y

#line 134
  48: mov r1.w, l(1.000000)
  49: dp4 r5.x, r1.xyzw, cb1[16].xyzw  // r5.x <- o.PosH.x
  50: dp4 r5.y, r1.xyzw, cb1[17].xyzw  // r5.y <- o.PosH.y
  51: dp4 r5.z, r1.xyzw, cb1[18].xyzw  // r5.z <- o.PosH.z
  52: dp4 r5.w, r1.xyzw, cb1[19].xyzw  // r5.w <- o.PosH.w

#line 135
  53: mov o0.xyzw, r5.xyzw
  54: mov o1.xyz, r1.xyzx
  55: mov o2.xyz, r3.xyzx
  56: mov o3.xy, r0.xyxx
  57: mov o4.x, r0.w
  58: emit_stream m0

#line 136
  59: mov r0.x, -cb1[30].z
  60: add r0.x, r0.x, cb1[30].y
  61: mul r0.xyz, r4.xyzx, r0.xxxx
  62: add r1.xyz, r0.xyzx, r2.xyzx  // r1.x <- c.x; r1.y <- c.y; r1.z <- c.z

#line 137
  63: mov r1.xyz, r1.xyzx  // r1.x <- o.PosW.x; r1.y <- o.PosW.y; r1.z <- o.PosW.z

#line 138
  64: mov r0.xy, l(0.500000,0,0,0)  // r0.x <- o.TexC.x; r0.y <- o.TexC.y

#line 139
  65: mov r1.w, l(1.000000)
  66: dp4 r2.x, r1.xyzw, cb1[16].xyzw  // r2.x <- o.PosH.x
  67: dp4 r2.y, r1.xyzw, cb1[17].xyzw  // r2.y <- o.PosH.y
  68: dp4 r2.z, r1.xyzw, cb1[18].xyzw  // r2.z <- o.PosH.z
  69: dp4 r2.w, r1.xyzw, cb1[19].xyzw  // r2.w <- o.PosH.w

#line 140
  70: mov o0.xyzw, r2.xyzw
  71: mov o1.xyz, r1.xyzx
  72: mov o2.xyz, r3.xyzx
  73: mov o3.xy, r0.xyxx
  74: mov o4.x, r0.w
  75: emit_stream m0

#line 152
  76: nop 

#line 153
  77: ret 
// Approximately 78 instruction slots used
 