//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPerObject                       cbuffer      NA          NA            cb0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TessFactor            0   x           0 QUADEDGE   float       
// SV_TessFactor            1   x           1 QUADEDGE   float       
// SV_TessFactor            2   x           2 QUADEDGE   float       
// SV_TessFactor            3   x           3 QUADEDGE   float       
// SV_InsideTessFactor      0   x           4  QUADINT   float       
// SV_InsideTessFactor      1   x           5  QUADINT   float       
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
// Tessellation Domain   # of control points
// -------------------- --------------------
// Quadrilateral                          16
//
      ds_5_0
      dcl_input_control_point_count 16
      dcl_tessellator_domain domain_quad
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[20], immediateIndexed
      dcl_input vDomain.xy
      dcl_input vicp[16][0].xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
//
// Initial variable locations:
//   vpc0.x <- patchTess.EdgeTess[0]; 
//   vpc1.x <- patchTess.EdgeTess[1]; 
//   vpc2.x <- patchTess.EdgeTess[2]; 
//   vpc3.x <- patchTess.EdgeTess[3]; 
//   vpc4.x <- patchTess.InsideTess[0]; 
//   vpc5.x <- patchTess.InsideTess[1]; 
//   vDomain.x <- uv.x; vDomain.y <- uv.y; 
//   o0.x <- <DS return value>.PosH.x; o0.y <- <DS return value>.PosH.y; o0.z <- <DS return value>.PosH.z; o0.w <- <DS return value>.PosH.w; 
//   vicp[0][0].x <- bezPatch[0].PosL.x; vicp[0][0].y <- bezPatch[0].PosL.y; vicp[0][0].z <- bezPatch[0].PosL.z; 
//   vicp[1][0].x <- bezPatch[1].PosL.x; vicp[1][0].y <- bezPatch[1].PosL.y; vicp[1][0].z <- bezPatch[1].PosL.z; 
//   vicp[2][0].x <- bezPatch[2].PosL.x; vicp[2][0].y <- bezPatch[2].PosL.y; vicp[2][0].z <- bezPatch[2].PosL.z; 
//   vicp[3][0].x <- bezPatch[3].PosL.x; vicp[3][0].y <- bezPatch[3].PosL.y; vicp[3][0].z <- bezPatch[3].PosL.z; 
//   vicp[4][0].x <- bezPatch[4].PosL.x; vicp[4][0].y <- bezPatch[4].PosL.y; vicp[4][0].z <- bezPatch[4].PosL.z; 
//   vicp[5][0].x <- bezPatch[5].PosL.x; vicp[5][0].y <- bezPatch[5].PosL.y; vicp[5][0].z <- bezPatch[5].PosL.z; 
//   vicp[6][0].x <- bezPatch[6].PosL.x; vicp[6][0].y <- bezPatch[6].PosL.y; vicp[6][0].z <- bezPatch[6].PosL.z; 
//   vicp[7][0].x <- bezPatch[7].PosL.x; vicp[7][0].y <- bezPatch[7].PosL.y; vicp[7][0].z <- bezPatch[7].PosL.z; 
//   vicp[8][0].x <- bezPatch[8].PosL.x; vicp[8][0].y <- bezPatch[8].PosL.y; vicp[8][0].z <- bezPatch[8].PosL.z; 
//   vicp[9][0].x <- bezPatch[9].PosL.x; vicp[9][0].y <- bezPatch[9].PosL.y; vicp[9][0].z <- bezPatch[9].PosL.z; 
//   vicp[10][0].x <- bezPatch[10].PosL.x; vicp[10][0].y <- bezPatch[10].PosL.y; vicp[10][0].z <- bezPatch[10].PosL.z; 
//   vicp[11][0].x <- bezPatch[11].PosL.x; vicp[11][0].y <- bezPatch[11].PosL.y; vicp[11][0].z <- bezPatch[11].PosL.z; 
//   vicp[12][0].x <- bezPatch[12].PosL.x; vicp[12][0].y <- bezPatch[12].PosL.y; vicp[12][0].z <- bezPatch[12].PosL.z; 
//   vicp[13][0].x <- bezPatch[13].PosL.x; vicp[13][0].y <- bezPatch[13].PosL.y; vicp[13][0].z <- bezPatch[13].PosL.z; 
//   vicp[14][0].x <- bezPatch[14].PosL.x; vicp[14][0].y <- bezPatch[14].PosL.y; vicp[14][0].z <- bezPatch[14].PosL.z; 
//   vicp[15][0].x <- bezPatch[15].PosL.x; vicp[15][0].y <- bezPatch[15].PosL.y; vicp[15][0].z <- bezPatch[15].PosL.z
//
#line 178 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap14\BezierPatch\Shaders\BezierTessellation.hlsl"
   0: nop 
   1: mov r0.x, vDomain.x

#line 140
   2: mov r0.y, -r0.x
   3: add r0.y, r0.y, l(1.000000)  // r0.y <- invT

#line 142
   4: mul r0.z, r0.y, r0.y
   5: mul r1.x, r0.y, r0.z  // r1.x <- <BernsteinBasis return value>.x
   6: mul r0.z, r0.x, l(3.000000)
   7: mul r0.z, r0.y, r0.z
   8: mul r1.y, r0.y, r0.z  // r1.y <- <BernsteinBasis return value>.y
   9: mul r0.z, r0.x, l(3.000000)
  10: mul r0.z, r0.x, r0.z
  11: mul r1.z, r0.y, r0.z  // r1.z <- <BernsteinBasis return value>.z
  12: mul r0.y, r0.x, r0.x
  13: mul r1.w, r0.x, r0.y  // r1.w <- <BernsteinBasis return value>.w

#line 178
  14: mov r1.xyzw, r1.xyzw  // r1.x <- basisU.x; r1.y <- basisU.y; r1.z <- basisU.z; r1.w <- basisU.w

#line 179
  15: nop 
  16: mov r0.x, vDomain.y

#line 140
  17: mov r0.y, -r0.x
  18: add r0.y, r0.y, l(1.000000)  // r0.y <- invT

#line 142
  19: mul r0.z, r0.y, r0.y
  20: mul r2.x, r0.y, r0.z  // r2.x <- <BernsteinBasis return value>.x
  21: mul r0.z, r0.x, l(3.000000)
  22: mul r0.z, r0.y, r0.z
  23: mul r2.y, r0.y, r0.z  // r2.y <- <BernsteinBasis return value>.y
  24: mul r0.z, r0.x, l(3.000000)
  25: mul r0.z, r0.x, r0.z
  26: mul r2.z, r0.y, r0.z  // r2.z <- <BernsteinBasis return value>.z
  27: mul r0.y, r0.x, r0.x
  28: mul r2.w, r0.x, r0.y  // r2.w <- <BernsteinBasis return value>.w

#line 179
  29: mov r2.xyzw, r2.xyzw  // r2.x <- basisV.x; r2.y <- basisV.y; r2.z <- basisV.z; r2.w <- basisV.w

#line 181
  30: nop 
  31: mov r1.xyzw, r1.xyzw
  32: mov r2.xyzw, r2.xyzw

#line 151
  33: mul r0.xyz, r1.xxxx, vicp[0][0].xyzx
  34: mul r3.xyz, r1.yyyy, vicp[1][0].xyzx
  35: add r0.xyz, r0.xyzx, r3.xyzx
  36: mul r3.xyz, r1.zzzz, vicp[2][0].xyzx
  37: add r0.xyz, r0.xyzx, r3.xyzx
  38: mul r3.xyz, r1.wwww, vicp[3][0].xyzx
  39: add r0.xyz, r0.xyzx, r3.xyzx
  40: mul r0.xyz, r0.xyzx, r2.xxxx  // r0.x <- sum.x; r0.y <- sum.y; r0.z <- sum.z

#line 152
  41: mul r3.xyz, r1.xxxx, vicp[4][0].xyzx
  42: mul r4.xyz, r1.yyyy, vicp[5][0].xyzx
  43: add r3.xyz, r3.xyzx, r4.xyzx
  44: mul r4.xyz, r1.zzzz, vicp[6][0].xyzx
  45: add r3.xyz, r3.xyzx, r4.xyzx
  46: mul r4.xyz, r1.wwww, vicp[7][0].xyzx
  47: add r3.xyz, r3.xyzx, r4.xyzx
  48: mul r3.xyz, r2.yyyy, r3.xyzx
  49: add r0.xyz, r0.xyzx, r3.xyzx

#line 153
  50: mul r3.xyz, r1.xxxx, vicp[8][0].xyzx
  51: mul r4.xyz, r1.yyyy, vicp[9][0].xyzx
  52: add r3.xyz, r3.xyzx, r4.xyzx
  53: mul r4.xyz, r1.zzzz, vicp[10][0].xyzx
  54: add r3.xyz, r3.xyzx, r4.xyzx
  55: mul r4.xyz, r1.wwww, vicp[11][0].xyzx
  56: add r3.xyz, r3.xyzx, r4.xyzx
  57: mul r2.xyz, r2.zzzz, r3.xyzx
  58: add r0.xyz, r0.xyzx, r2.xyzx

#line 154
  59: mul r2.xyz, r1.xxxx, vicp[12][0].xyzx
  60: mul r3.xyz, r1.yyyy, vicp[13][0].xyzx
  61: add r2.xyz, r2.xyzx, r3.xyzx
  62: mul r1.xyz, r1.zzzz, vicp[14][0].xyzx
  63: add r1.xyz, r1.xyzx, r2.xyzx
  64: mul r2.xyz, r1.wwww, vicp[15][0].xyzx
  65: add r1.xyz, r1.xyzx, r2.xyzx
  66: mul r1.xyz, r1.xyzx, r2.wwww
  67: add r0.xyz, r0.xyzx, r1.xyzx

#line 156
  68: mov r0.xyz, r0.xyzx  // r0.x <- <CubicBezierSum return value>.x; r0.y <- <CubicBezierSum return value>.y; r0.z <- <CubicBezierSum return value>.z

#line 181
  69: mov r0.xyz, r0.xyzx  // r0.x <- p.x; r0.y <- p.y; r0.z <- p.z

#line 183
  70: mov r0.w, l(1.000000)
  71: dp4 r1.x, r0.xyzw, cb0[0].xyzw  // r1.x <- posW.x
  72: dp4 r1.y, r0.xyzw, cb0[1].xyzw  // r1.y <- posW.y
  73: dp4 r1.z, r0.xyzw, cb0[2].xyzw  // r1.z <- posW.z
  74: dp4 r1.w, r0.xyzw, cb0[3].xyzw  // r1.w <- posW.w

#line 184
  75: dp4 r0.x, r1.xyzw, cb1[16].xyzw  // r0.x <- dout.PosH.x
  76: dp4 r0.y, r1.xyzw, cb1[17].xyzw  // r0.y <- dout.PosH.y
  77: dp4 r0.z, r1.xyzw, cb1[18].xyzw  // r0.z <- dout.PosH.z
  78: dp4 r0.w, r1.xyzw, cb1[19].xyzw  // r0.w <- dout.PosH.w

#line 186
  79: mov o0.xyzw, r0.xyzw
  80: ret 
// Approximately 81 instruction slots used
 