//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// SIZE                     0   xy          1     NONE   float   xy  
// SV_PrimitiveID           0    N/A   primID   PRIMID    uint    YES
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
// SV_PrimitiveID           0   x           4   PRIMID    uint   x   
//
      gs_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB1[25], immediateIndexed
      dcl_input v[1][0].xyz
      dcl_input v[1][1].xy
      dcl_input vPrim
      dcl_temps 5
      dcl_indexableTemp x0[4], 4
      dcl_indexableTemp x1[4], 4
      dcl_inputprimitive point 
      dcl_stream m0
      dcl_outputtopology trianglestrip 
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xy
      dcl_output_sgv o4.x, primitive_id
      dcl_maxout 4
//
// Initial variable locations:
//   vPrim <- primID; 
//   m0 <- triStream; 
//   v[0][0].x <- gin[0].CenterW.x; v[0][0].y <- gin[0].CenterW.y; v[0][0].z <- gin[0].CenterW.z; 
//   v[0][1].x <- gin[0].SizeW.x; v[0][1].y <- gin[0].SizeW.y; 
//   x0 <- v; x1 <- texC
//
#line 118 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap12\Chap12_6\Shaders\TreeSprite.hlsl"
   0: mov r0.xyz, l(0,1.000000,0,0)  // r0.x <- up.x; r0.y <- up.y; r0.z <- up.z

#line 119
   1: mov r1.xy, -v[0][0].xzxx
   2: add r1.xz, r1.xxyx, cb1[24].xxzx  // r1.x <- look.x; r1.z <- look.z

#line 120
   3: mov r1.y, l(0)  // r1.y <- look.y

#line 121
   4: dp3 r0.w, r1.xyzx, r1.xyzx
   5: rsq r0.w, r0.w
   6: mul r1.xyz, r0.wwww, r1.xyzx

#line 122
   7: mul r2.xyz, r0.yzxy, r1.zxyz
   8: mul r3.xyz, r0.zxyz, r1.yzxy
   9: mov r3.xyz, -r3.xyzx
  10: add r2.xyz, r2.xyzx, r3.xyzx  // r2.x <- right.x; r2.y <- right.y; r2.z <- right.z

#line 127
  11: mul r0.w, l(0.500000), v[0][1].x  // r0.w <- halfWidth

#line 128
  12: mul r1.w, l(0.500000), v[0][1].y  // r1.w <- halfHeight

#line 131
  13: mul r3.xyz, r2.xyzx, r0.wwww
  14: add r3.xyz, r3.xyzx, v[0][0].xyzx
  15: mul r4.xyz, r0.xyzx, r1.wwww
  16: mov r4.xyz, -r4.xyzx
  17: add r3.xyz, r3.xyzx, r4.xyzx
  18: mov r3.w, l(1.000000)
  19: mov x0[0].xyzw, r3.xyzw

#line 132
  20: mul r3.xyz, r2.xyzx, r0.wwww
  21: add r3.xyz, r3.xyzx, v[0][0].xyzx
  22: mul r4.xyz, r0.xyzx, r1.wwww
  23: add r3.xyz, r3.xyzx, r4.xyzx
  24: mov r3.w, l(1.000000)
  25: mov x0[1].xyzw, r3.xyzw

#line 133
  26: mul r3.xyz, r2.xyzx, r0.wwww
  27: mov r3.xyz, -r3.xyzx
  28: add r3.xyz, r3.xyzx, v[0][0].xyzx
  29: mul r4.xyz, r0.xyzx, r1.wwww
  30: mov r4.xyz, -r4.xyzx
  31: add r3.xyz, r3.xyzx, r4.xyzx
  32: mov r3.w, l(1.000000)
  33: mov x0[2].xyzw, r3.xyzw

#line 134
  34: mul r2.xyz, r2.xyzx, r0.wwww
  35: mov r2.xyz, -r2.xyzx
  36: add r2.xyz, r2.xyzx, v[0][0].xyzx
  37: mul r0.xyz, r0.xyzx, r1.wwww
  38: add r0.xyz, r0.xyzx, r2.xyzx
  39: mov r0.w, l(1.000000)
  40: mov x0[3].xyzw, r0.xyzw

#line 141
  41: mov x1[0].xy, l(0,1.000000,0,0)
  42: mov x1[1].xy, l(0,0,0,0)
  43: mov x1[2].xy, l(1.000000,1.000000,0,0)
  44: mov x1[3].xy, l(1.000000,0,0,0)

#line 153
  45: mov r0.xyzw, x0[0].xyzw
  46: dp4 r2.x, r0.xyzw, cb1[16].xyzw  // r2.x <- gout.PosH.x
  47: dp4 r2.y, r0.xyzw, cb1[17].xyzw  // r2.y <- gout.PosH.y
  48: dp4 r2.z, r0.xyzw, cb1[18].xyzw  // r2.z <- gout.PosH.z
  49: dp4 r2.w, r0.xyzw, cb1[19].xyzw  // r2.w <- gout.PosH.w

#line 154
  50: mov r0.xyz, x0[0].xyzx  // r0.x <- gout.PosW.x; r0.y <- gout.PosW.y; r0.z <- gout.PosW.z

#line 155
  51: mov r1.xyz, r1.xyzx  // r1.x <- gout.NormalW.x; r1.y <- gout.NormalW.y; r1.z <- gout.NormalW.z

#line 156
  52: mov r3.xy, x1[0].xyxx  // r3.x <- gout.TexC.x; r3.y <- gout.TexC.y

#line 157
  53: mov r0.w, vPrim  // r0.w <- gout.PrimID

#line 159
  54: mov o0.xyzw, r2.xyzw
  55: mov o1.xyz, r0.xyzx
  56: mov o2.xyz, r1.xyzx
  57: mov o3.xy, r3.xyxx
  58: mov o4.x, r0.w
  59: emit_stream m0

#line 153
  60: mov r0.xyzw, x0[1].xyzw
  61: dp4 r2.x, r0.xyzw, cb1[16].xyzw
  62: dp4 r2.y, r0.xyzw, cb1[17].xyzw
  63: dp4 r2.z, r0.xyzw, cb1[18].xyzw
  64: dp4 r2.w, r0.xyzw, cb1[19].xyzw

#line 154
  65: mov r0.xyz, x0[1].xyzx  // r0.x <- gout.PosW.x; r0.y <- gout.PosW.y; r0.z <- gout.PosW.z

#line 156
  66: mov r3.xy, x1[1].xyxx

#line 157
  67: mov r0.w, vPrim  // r0.w <- gout.PrimID

#line 159
  68: mov o0.xyzw, r2.xyzw
  69: mov o1.xyz, r0.xyzx
  70: mov o2.xyz, r1.xyzx
  71: mov o3.xy, r3.xyxx
  72: mov o4.x, r0.w
  73: emit_stream m0

#line 153
  74: mov r0.xyzw, x0[2].xyzw
  75: dp4 r2.x, r0.xyzw, cb1[16].xyzw
  76: dp4 r2.y, r0.xyzw, cb1[17].xyzw
  77: dp4 r2.z, r0.xyzw, cb1[18].xyzw
  78: dp4 r2.w, r0.xyzw, cb1[19].xyzw

#line 154
  79: mov r0.xyz, x0[2].xyzx  // r0.x <- gout.PosW.x; r0.y <- gout.PosW.y; r0.z <- gout.PosW.z

#line 156
  80: mov r3.xy, x1[2].xyxx

#line 157
  81: mov r0.w, vPrim  // r0.w <- gout.PrimID

#line 159
  82: mov o0.xyzw, r2.xyzw
  83: mov o1.xyz, r0.xyzx
  84: mov o2.xyz, r1.xyzx
  85: mov o3.xy, r3.xyxx
  86: mov o4.x, r0.w
  87: emit_stream m0

#line 153
  88: mov r0.xyzw, x0[3].xyzw
  89: dp4 r2.x, r0.xyzw, cb1[16].xyzw
  90: dp4 r2.y, r0.xyzw, cb1[17].xyzw
  91: dp4 r2.z, r0.xyzw, cb1[18].xyzw
  92: dp4 r2.w, r0.xyzw, cb1[19].xyzw

#line 154
  93: mov r0.xyz, x0[3].xyzx  // r0.x <- gout.PosW.x; r0.y <- gout.PosW.y; r0.z <- gout.PosW.z

#line 156
  94: mov r3.xy, x1[3].xyxx

#line 157
  95: mov r0.w, vPrim  // r0.w <- gout.PrimID

#line 159
  96: mov o0.xyzw, r2.xyzw
  97: mov o1.xyz, r0.xyzx
  98: mov o2.xyz, r1.xyzx
  99: mov o3.xy, r3.xyxx
 100: mov o4.x, r0.w
 101: emit_stream m0

#line 161
 102: ret 
// Approximately 103 instruction slots used
 