//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  448
//       float FalloffStart;            // Offset:  460
//       float3 Direction;              // Offset:  464
//       float FalloffEnd;              // Offset:  476
//       float3 Position;               // Offset:  480
//       float SpotPower;               // Offset:  492
//
//   } gLights[16];                     // Offset:  448 Size:   768
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gsamLinear                        sampler      NA          NA             s0      1 
// gDiffuseMap1                      texture  float4          2d             t0      1 
// gDiffuseMap2                      texture  float4          2d             t1      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
// cbMaterial                        cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB1[39], immediateIndexed
      dcl_constantbuffer CB2[2], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_resource_texture2d (float,float,float,float) t1
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xyz
      dcl_input_ps linear v3.xy
      dcl_output o0.xyzw
      dcl_temps 13
      dcl_indexableTemp x0[21], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   v3.x <- pin.TexC.x; v3.y <- pin.TexC.y; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 107 "C:\cg\DX12\Solution\Chap9\Chap9_3\Shaders\Default.hlsl"
   0: sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v3.xyxx, t0.xyzw, s0
   1: sample_indexable(texture2d)(float,float,float,float) r1.xyzw, v3.xyxx, t1.xyzw, s0
   2: mul r0.xyzw, r0.xyzw, r1.xyzw
   3: mul r0.xyzw, r0.xyzw, cb2[0].xyzw  // r0.x <- diffuseAlbedo.x; r0.y <- diffuseAlbedo.y; r0.z <- diffuseAlbedo.z; r0.w <- diffuseAlbedo.w

#line 110
   4: dp3 r1.x, v2.xyzx, v2.xyzx
   5: rsq r1.x, r1.x
   6: mul r1.xyz, r1.xxxx, v2.xyzx  // r1.x <- pin.NormalW.x; r1.y <- pin.NormalW.y; r1.z <- pin.NormalW.z

#line 113
   7: mov r2.xyz, -v1.xyzx
   8: add r2.xyz, r2.xyzx, cb1[24].xyzx
   9: dp3 r1.w, r2.xyzx, r2.xyzx
  10: rsq r1.w, r1.w
  11: mul r2.xyz, r1.wwww, r2.xyzx  // r2.x <- toEyeW.x; r2.y <- toEyeW.y; r2.z <- toEyeW.z

#line 116
  12: mul r3.xyz, r0.xyzx, cb1[27].xyzx  // r3.x <- ambient.x; r3.y <- ambient.y; r3.z <- ambient.z

#line 118
  13: mov r1.w, -cb2[1].w
  14: add r4.w, r1.w, l(1.000000)  // r4.w <- shininess

#line 119
  15: mov r5.xyz, r0.xyzx  // r5.x <- mat.DiffuseAlbedo.x; r5.y <- mat.DiffuseAlbedo.y; r5.z <- mat.DiffuseAlbedo.z
  16: mov r5.w, cb2[1].x  // r5.w <- mat.FresnelR0.x
  17: mov r4.yz, cb2[1].yyzy  // r4.y <- mat.FresnelR0.y; r4.z <- mat.FresnelR0.z
  18: mov r4.w, r4.w  // r4.w <- mat.Shininess

#line 121
  19: nop 
  20: mov x0[0].xyz, cb1[28].xyzx
  21: mov x0[2].xyz, cb1[29].xyzx
  22: mov x0[4].xyz, cb1[30].xyzx
  23: mov x0[6].xyz, cb1[31].xyzx
  24: mov x0[8].xyz, cb1[32].xyzx
  25: mov x0[10].xyz, cb1[33].xyzx
  26: mov x0[12].xyz, cb1[34].xyzx
  27: mov x0[14].xyz, cb1[35].xyzx
  28: mov x0[16].xyz, cb1[36].xyzx
  29: mov x0[18].xyz, cb1[37].xyzx
  30: mov x0[20].xyz, cb1[38].xyzx
  31: mov r5.xyzw, r5.xyzw
  32: mov r4.yzw, r4.yyzw
  33: mov r1.xyz, r1.xyzx
  34: mov r2.xyz, r2.xyzx

#line 142 "LightingUtil.hlsl"
  35: mov r0.xyz, l(0,0,0,0)  // r0.x <- result.x; r0.y <- result.y; r0.z <- result.z

#line 147
  36: mov r1.w, l(0)  // r1.w <- i
  37: mov r6.xyz, r0.xyzx  // r6.x <- result.x; r6.y <- result.y; r6.z <- result.z
  38: mov r2.w, r1.w  // r2.w <- i
  39: loop 
  40:   ilt r3.w, r2.w, l(3)
  41:   breakc_z r3.w

#line 149
  42:   mov r3.w, l(1.000000)  // r3.w <- shadowFactor.x
  43:   nop 
  44:   imul null, r4.x, r2.w, l(6)
  45:   mov r7.xyz, x0[r4.x + 0].xyzx
  46:   mov r8.xyz, x0[r4.x + 2].xyzx
  47:   mov r9.x, r5.w
  48:   mov r9.yzw, r4.yyzw
  49:   mov r10.xyz, r5.xyzx
  50:   mov r11.xyz, r1.xyzx
  51:   mov r12.xyz, r2.xyzx

#line 67
  52:   mov r8.xyz, -r8.xyzx  // r8.x <- lightVec.x; r8.y <- lightVec.y; r8.z <- lightVec.z

#line 70
  53:   dp3 r4.x, r8.xyzx, r11.xyzx
  54:   max r4.x, r4.x, l(0.000000)  // r4.x <- ndotl

#line 71
  55:   mul r7.xyz, r4.xxxx, r7.xyzx  // r7.x <- lightStrength.x; r7.y <- lightStrength.y; r7.z <- lightStrength.z

#line 73
  56:   nop 
  57:   mov r7.xyz, r7.xyzx
  58:   mov r8.xyz, r8.xyzx
  59:   mov r11.xyz, r11.xyzx
  60:   mov r12.xyz, r12.xyzx
  61:   mov r10.xyz, r10.xyzx
  62:   mov r9.xyzw, r9.xyzw

#line 46
  63:   mul r4.x, r9.w, l(256.000000)  // r4.x <- m

#line 47
  64:   add r12.xyz, r8.xyzx, r12.xyzx
  65:   dp3 r6.w, r12.xyzx, r12.xyzx
  66:   rsq r6.w, r6.w
  67:   mul r12.xyz, r6.wwww, r12.xyzx  // r12.x <- halfVec.x; r12.y <- halfVec.y; r12.z <- halfVec.z

#line 49
  68:   add r6.w, r4.x, l(8.000000)
  69:   dp3 r7.w, r12.xyzx, r11.xyzx
  70:   max r7.w, r7.w, l(0.000000)
  71:   log r7.w, r7.w
  72:   mul r4.x, r4.x, r7.w
  73:   exp r4.x, r4.x
  74:   mul r4.x, r4.x, r6.w
  75:   div r4.x, r4.x, l(8.000000)  // r4.x <- roughnessFactor

#line 50
  76:   nop 
  77:   mov r9.xyz, r9.xyzx
  78:   mov r12.xyz, r12.xyzx
  79:   mov r8.xyz, r8.xyzx

#line 36
  80:   dp3 r6.w, r12.xyzx, r8.xyzx
  81:   max r6.w, r6.w, l(0.000000)
  82:   min r6.w, r6.w, l(1.000000)  // r6.w <- cosIncidentAngle

#line 38
  83:   mov r6.w, -r6.w
  84:   add r6.w, r6.w, l(1.000000)  // r6.w <- f0

#line 39
  85:   mov r8.xyz, -r9.xyzx
  86:   add r8.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  87:   mul r7.w, r6.w, r6.w
  88:   mul r7.w, r6.w, r7.w
  89:   mul r7.w, r6.w, r7.w
  90:   mul r6.w, r6.w, r7.w
  91:   mul r8.xyz, r6.wwww, r8.xyzx
  92:   add r8.xyz, r8.xyzx, r9.xyzx  // r8.x <- reflectPercent.x; r8.y <- reflectPercent.y; r8.z <- reflectPercent.z

#line 41
  93:   mov r8.xyz, r8.xyzx  // r8.x <- <SchlickFresnel return value>.x; r8.y <- <SchlickFresnel return value>.y; r8.z <- <SchlickFresnel return value>.z

#line 50
  94:   mov r8.xyz, r8.xyzx  // r8.x <- fresnelFactor.x; r8.y <- fresnelFactor.y; r8.z <- fresnelFactor.z

#line 52
  95:   mul r8.xyz, r4.xxxx, r8.xyzx  // r8.x <- specAlbedo.x; r8.y <- specAlbedo.y; r8.z <- specAlbedo.z

#line 56
  96:   add r9.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  97:   div r8.xyz, r8.xyzx, r9.xyzx

#line 58
  98:   add r8.xyz, r8.xyzx, r10.xyzx
  99:   mul r7.xyz, r7.xyzx, r8.xyzx  // r7.x <- <BlinnPhong return value>.x; r7.y <- <BlinnPhong return value>.y; r7.z <- <BlinnPhong return value>.z

#line 73
 100:   mov r7.xyz, r7.xyzx  // r7.x <- <ComputeDirectionalLight return value>.x; r7.y <- <ComputeDirectionalLight return value>.y; r7.z <- <ComputeDirectionalLight return value>.z

#line 149
 101:   mul r7.xyz, r3.wwww, r7.xyzx
 102:   add r6.xyz, r6.xyzx, r7.xyzx

#line 150
 103:   iadd r2.w, r2.w, l(1)
 104: endloop 

#line 167
 105: mov r6.xyz, r6.xyzx  // r6.x <- <ComputeLighting return value>.x; r6.y <- <ComputeLighting return value>.y; r6.z <- <ComputeLighting return value>.z

#line 121 "C:\cg\DX12\Solution\Chap9\Chap9_3\Shaders\Default.hlsl"
 106: mov r6.xyz, r6.xyzx  // r6.x <- directLight.x; r6.y <- directLight.y; r6.z <- directLight.z

#line 124
 107: add r0.xyz, r3.xyzx, r6.xyzx  // r0.x <- litColor.x; r0.y <- litColor.y; r0.z <- litColor.z

#line 127
 108: mov r0.w, r0.w  // r0.w <- litColor.w

#line 129
 109: mov o0.xyz, r0.xyzx
 110: mov o0.w, r0.w
 111: ret 
// Approximately 112 instruction slots used
 