//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// HEIGHT                   0      w        0     NONE   float      w
// SV_PrimitiveID           0    N/A   primID   PRIMID    uint    YES
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
// SV_PrimitiveID           0   x           4   PRIMID    uint   x   
//
      gs_5_0
      dcl_globalFlags refactoringAllowed | skipOptimization
      dcl_constantbuffer CB1[20], immediateIndexed
      dcl_input v[2][0].xyz
      dcl_input v[2][0].w
      dcl_input vPrim
      dcl_temps 4
      dcl_indexableTemp x0[4], 4
      dcl_indexableTemp x1[4], 4
      dcl_inputprimitive line 
      dcl_stream m0
      dcl_outputtopology trianglestrip 
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xy
      dcl_output_sgv o4.x, primitive_id
      dcl_maxout 6
//
// Initial variable locations:
//   vPrim <- primID; 
//   m0 <- triStream; 
//   v[0][0].x <- gin[0].CenterW.x; v[0][0].y <- gin[0].CenterW.y; v[0][0].z <- gin[0].CenterW.z; v[0][0].w <- gin[0].height; 
//   v[1][0].x <- gin[1].CenterW.x; v[1][0].y <- gin[1].CenterW.y; v[1][0].z <- gin[1].CenterW.z; v[1][0].w <- gin[1].height; 
//   x0 <- v; x1 <- texC
//
#line 119 "C:\1.task\5.DirextX12\DX12_practice\Solution\Chap12\Chap12_1\Shaders\Cylinder.hlsl"
   0: mov r0.y, v[0][0].w  // r0.y <- height

#line 120
   1: mov r0.xz, l(0,0,0,0)
   2: mov r0.xyz, r0.xyzx  // r0.x <- up.x; r0.y <- up.y; r0.z <- up.z

#line 122
   3: mov r1.xyz, v[0][0].xyzx
   4: mov r1.w, l(1.000000)
   5: mov x0[0].xyzw, r1.xyzw

#line 123
   6: add r1.xyz, r0.xyzx, v[0][0].xyzx
   7: mov r1.w, l(1.000000)
   8: mov x0[1].xyzw, r1.xyzw

#line 124
   9: mov r1.xyz, v[1][0].xyzx
  10: mov r1.w, l(1.000000)
  11: mov x0[2].xyzw, r1.xyzw

#line 125
  12: add r0.xyz, r0.xyzx, v[1][0].xyzx
  13: mov r0.w, l(1.000000)
  14: mov x0[3].xyzw, r0.xyzw

#line 131
  15: mov r0.xyz, -v[0][0].zxyz
  16: add r0.xyz, r0.xyzx, v[1][0].zxyz
  17: dp3 r0.w, r0.xyzx, r0.xyzx
  18: rsq r0.w, r0.w
  19: mul r0.xyz, r0.wwww, r0.xyzx  // r0.x <- tangent.z; r0.y <- tangent.x; r0.z <- tangent.y

#line 132
  20: mov r1.xyz, l(1.000000,0,0,0)  // r1.x <- upDir.y; r1.y <- upDir.z; r1.z <- upDir.x

#line 133
  21: mul r2.xyz, r0.zxyz, r1.yzxy
  22: mul r0.xyz, r0.xyzx, r1.xyzx
  23: mov r0.xyz, -r0.xyzx
  24: add r0.xyz, r0.xyzx, r2.xyzx
  25: dp3 r0.w, r0.xyzx, r0.xyzx
  26: rsq r0.w, r0.w
  27: mul r0.xyz, r0.wwww, r0.xyzx  // r0.x <- normalW.x; r0.y <- normalW.y; r0.z <- normalW.z

#line 135
  28: mov x1[0].xy, l(0,1.000000,0,0)
  29: mov x1[1].xy, l(0,0,0,0)
  30: mov x1[2].xy, l(1.000000,1.000000,0,0)
  31: mov x1[3].xy, l(1.000000,0,0,0)

#line 147
  32: mov r1.xyzw, x0[0].xyzw
  33: dp4 r2.x, r1.xyzw, cb1[16].xyzw  // r2.x <- gout.PosH.x
  34: dp4 r2.y, r1.xyzw, cb1[17].xyzw  // r2.y <- gout.PosH.y
  35: dp4 r2.z, r1.xyzw, cb1[18].xyzw  // r2.z <- gout.PosH.z
  36: dp4 r2.w, r1.xyzw, cb1[19].xyzw  // r2.w <- gout.PosH.w

#line 148
  37: mov r1.xyz, x0[0].xyzx  // r1.x <- gout.PosW.x; r1.y <- gout.PosW.y; r1.z <- gout.PosW.z

#line 149
  38: mov r0.xyz, r0.xyzx  // r0.x <- gout.NormalW.x; r0.y <- gout.NormalW.y; r0.z <- gout.NormalW.z

#line 150
  39: mov r3.xy, x1[0].xyxx  // r3.x <- gout.TexC.x; r3.y <- gout.TexC.y

#line 151
  40: mov r0.w, vPrim  // r0.w <- gout.PrimID

#line 153
  41: mov o0.xyzw, r2.xyzw
  42: mov o1.xyz, r1.xyzx
  43: mov o2.xyz, r0.xyzx
  44: mov o3.xy, r3.xyxx
  45: mov o4.x, r0.w
  46: emit_stream m0

#line 147
  47: mov r1.xyzw, x0[1].xyzw
  48: dp4 r2.x, r1.xyzw, cb1[16].xyzw
  49: dp4 r2.y, r1.xyzw, cb1[17].xyzw
  50: dp4 r2.z, r1.xyzw, cb1[18].xyzw
  51: dp4 r2.w, r1.xyzw, cb1[19].xyzw

#line 148
  52: mov r1.xyz, x0[1].xyzx  // r1.x <- gout.PosW.x; r1.y <- gout.PosW.y; r1.z <- gout.PosW.z

#line 150
  53: mov r3.xy, x1[1].xyxx

#line 151
  54: mov r0.w, vPrim

#line 153
  55: mov o0.xyzw, r2.xyzw
  56: mov o1.xyz, r1.xyzx
  57: mov o2.xyz, r0.xyzx
  58: mov o3.xy, r3.xyxx
  59: mov o4.x, r0.w
  60: emit_stream m0

#line 147
  61: mov r1.xyzw, x0[2].xyzw
  62: dp4 r2.x, r1.xyzw, cb1[16].xyzw
  63: dp4 r2.y, r1.xyzw, cb1[17].xyzw
  64: dp4 r2.z, r1.xyzw, cb1[18].xyzw
  65: dp4 r2.w, r1.xyzw, cb1[19].xyzw

#line 148
  66: mov r1.xyz, x0[2].xyzx  // r1.x <- gout.PosW.x; r1.y <- gout.PosW.y; r1.z <- gout.PosW.z

#line 150
  67: mov r3.xy, x1[2].xyxx

#line 151
  68: mov r0.w, vPrim

#line 153
  69: mov o0.xyzw, r2.xyzw
  70: mov o1.xyz, r1.xyzx
  71: mov o2.xyz, r0.xyzx
  72: mov o3.xy, r3.xyxx
  73: mov o4.x, r0.w
  74: emit_stream m0

#line 147
  75: mov r1.xyzw, x0[3].xyzw
  76: dp4 r2.x, r1.xyzw, cb1[16].xyzw
  77: dp4 r2.y, r1.xyzw, cb1[17].xyzw
  78: dp4 r2.z, r1.xyzw, cb1[18].xyzw
  79: dp4 r2.w, r1.xyzw, cb1[19].xyzw

#line 148
  80: mov r1.xyz, x0[3].xyzx  // r1.x <- gout.PosW.x; r1.y <- gout.PosW.y; r1.z <- gout.PosW.z

#line 150
  81: mov r3.xy, x1[3].xyxx

#line 151
  82: mov r0.w, vPrim

#line 153
  83: mov o0.xyzw, r2.xyzw
  84: mov o1.xyz, r1.xyzx
  85: mov o2.xyz, r0.xyzx
  86: mov o3.xy, r3.xyxx
  87: mov o4.x, r0.w
  88: emit_stream m0

#line 155
  89: ret 
// Approximately 90 instruction slots used
 